// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package tabbit.fixtures.nullableelements;

import tabbit.TcbReader;

// Generated from test/fixtures/xlsx/nullable-elements/nullable-elements.xlsx : Arrays : B2
/** Every combination of an array and its elements being optional. */
public final class ListingRecord {
    /** primary index */
    public int index;
    /** what the row is about */
    public String name = "";
    /** both required */
    public int[] plain = new int[0];
    /** the array may be absent */
    public int[] maybe = new int[0];
    /**
     * Whether this row has a value for maybe. The value field keeps its type and
     * holds the type's empty value when the row had none; this says which it was.
     */
    public boolean hasMaybe;
    /** an element may be absent */
    public int[] holes = new int[0];
    /**
     * Which of holes's elements have a value. Empty where the file did not carry
     * the column, and then every index is out of range anyway.
     */
    public boolean[] hasHolesAt = new boolean[0];
    /** either may be */
    public int[] both = new int[0];
    /**
     * Whether this row has a value for both. The value field keeps its type and
     * holds the type's empty value when the row had none; this says which it was.
     */
    public boolean hasBoth;
    /**
     * Which of both's elements have a value. Empty where the file did not carry
     * the column, and then every index is out of range anyway.
     */
    public boolean[] hasBothAt = new boolean[0];
    /** where a value comparison cannot see it */
    public String[] words = new String[0];
    /**
     * Which of words's elements have a value. Empty where the file did not carry
     * the column, and then every index is out of range anyway.
     */
    public boolean[] hasWordsAt = new boolean[0];

}
