// ------------------------------------------------------------------------------
// <auto-generated>
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections.Generic;
using System.Threading.Tasks;

// Tabbit's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using Tabbit.Binary;

namespace Tabbit.Fixtures.NullableElements
{
    /// <summary>
    /// Every combination of an array and its elements being optional.
    /// </summary>
    [System.Serializable]
    public partial class ListingTable : IEnumerable<ListingTable.Record>
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Values
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;

            /// <summary>
            /// what the row is about
            /// </summary>
            public string Name => _name;

            /// <summary>
            /// both required
            /// </summary>
            public int[] Plain => _plain;

            /// <summary>
            /// the array may be absent
            /// </summary>
            public int[] Maybe => _maybe;
            /// <summary>Whether this row has a value for <see cref="Maybe"/>.</summary>
            public bool HasMaybe => _maybeHasValue;

            /// <summary>
            /// an element may be absent
            /// </summary>
            public int[] Holes => _holes;
            /// <summary>Whether element <paramref name="index"/> of <see cref="Holes"/> has a value.</summary>
            public bool HasHolesAt(int index)
                => _holesHasValueAt == null
                    || index < 0 || index >= _holesHasValueAt.Length
                    || _holesHasValueAt[index];

            /// <summary>
            /// either may be
            /// </summary>
            public int[] Both => _both;
            /// <summary>Whether this row has a value for <see cref="Both"/>.</summary>
            public bool HasBoth => _bothHasValue;
            /// <summary>Whether element <paramref name="index"/> of <see cref="Both"/> has a value.</summary>
            public bool HasBothAt(int index)
                => _bothHasValueAt == null
                    || index < 0 || index >= _bothHasValueAt.Length
                    || _bothHasValueAt[index];

            /// <summary>
            /// where a value comparison cannot see it
            /// </summary>
            public string[] Words => _words;
            /// <summary>Whether element <paramref name="index"/> of <see cref="Words"/> has a value.</summary>
            public bool HasWordsAt(int index)
                => _wordsHasValueAt == null
                    || index < 0 || index >= _wordsHasValueAt.Length
                    || _wordsHasValueAt[index];
            #endregion

            #region Storage
            internal int _index;
            internal string _name = "";
            internal int[] _plain = System.Array.Empty<int>();
            internal int[] _maybe = System.Array.Empty<int>();
            internal bool _maybeHasValue;
            internal int[] _holes = System.Array.Empty<int>();
            internal bool[] _holesHasValueAt;
            internal int[] _both = System.Array.Empty<int>();
            internal bool _bothHasValue;
            internal bool[] _bothHasValueAt;
            internal string[] _words = System.Array.Empty<string>();
            internal bool[] _wordsHasValueAt;
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Name\":"); ToStringHelper.ToString(Name, sb);
                sb.Append(",\"Plain\":"); ToStringHelper.ToString(Plain, sb);
                sb.Append(",\"Maybe\":"); ToStringHelper.ToString(Maybe, sb);
                sb.Append(",\"Holes\":"); ToStringHelper.ToString(Holes, sb);
                sb.Append(",\"Both\":"); ToStringHelper.ToString(Both, sb);
                sb.Append(",\"Words\":"); ToStringHelper.ToString(Words, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Name", "Plain", "Maybe", "Holes", "Both", "Words" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Name, r.Plain, r.Maybe, r.Holes, r.Both, r.Words });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        /// <remarks>
        /// The list a read publishes, not one a read fills. Whoever holds this reference holds
        /// the rows as they were when they took it, and a refresh underneath them replaces the
        /// reference rather than the contents - so an iteration in progress neither tears nor
        /// throws, and a read that fails leaves the previous rows exactly where they were.
        /// </remarks>
        public List<Record> Records => _records;
        private List<Record> _records = new List<Record>();

        /// <summary>How many rows the table holds.</summary>
        public int Count => _records.Count;

        /// <summary>The rows, in the order the file wrote them.</summary>
        /// <remarks>
        /// A struct enumerator rather than the interface one, because `foreach` binds to this
        /// by name and a boxed enumerator allocates once per loop - which in a project that
        /// walks a table every frame is an allocation every frame. LINQ and anything holding
        /// the table as `IEnumerable` reach the explicit implementations below instead, and
        /// those box exactly as they always would have.
        ///
        /// The list reference is read once, here. A refresh replaces the reference rather than
        /// its contents, so a loop already running keeps the rows it started with - the same
        /// property `Records` documents above, reached without naming the list.
        /// </remarks>
        public List<Record>.Enumerator GetEnumerator() => _records.GetEnumerator();

        IEnumerator<Record> IEnumerable<Record>.GetEnumerator() => _records.GetEnumerator();

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
            => _records.GetEnumerator();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// The row with this `Index`, or null when the table has none.
        /// </summary>
        /// <remarks>
        /// The lookup to reach for when a missing row is an ordinary answer - an optional
        /// reference, a key that came from user input. Every language Tabbit generates has
        /// this one under the same name.
        /// </remarks>
        public Record FindByIndex(int key)
            => _recordsByIndex.TryGetValue(key, out Record record) ? record : null;

        /// <summary>
        /// The row with this `Index`, or a thrown exception naming what was
        /// missing.
        /// </summary>
        /// <remarks>
        /// For a key that has to be there - one from another table, or a constant. The name
        /// says it throws, because a caller reading `GetByIndex(id).Name` at
        /// a glance cannot otherwise tell whether the next line is a null check or a catch.
        /// </remarks>
        public Record GetByIndexOrThrow(int key)
        {
            if (!_recordsByIndex.TryGetValue(key, out Record record))
                throw new TabbitException($"There is no record in table `Listing` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>Whether the table holds a row with this `Index`.</summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>Each row with the `Index` it is keyed by.</summary>
        /// <remarks>
        /// `foreach (var (key, row) in table.Entries)`. What this saves a caller is not the
        /// key value - the row carries it - but having to know which column the key is:
        /// `Index` here, something else in the next table.
        ///
        /// A struct that enumerates itself, so the loop allocates nothing, and the rows in
        /// the order the file wrote them rather than the order a dictionary happens to hold
        /// them - which makes this and a plain `foreach` over the table agree.
        ///
        /// Only the primary key gets this. A table keyed by several columns together has no
        /// single key value to pair a row with.
        /// </remarks>
        public struct EntryEnumerator
        {
            private readonly List<Record> _rows;
            private int _at;

            internal EntryEnumerator(List<Record> rows)
            {
                _rows = rows;
                _at = -1;
            }

            public EntryEnumerator GetEnumerator() => this;

            public bool MoveNext() => ++_at < _rows.Count;

            public (int Key, Record Row) Current
                => (_rows[_at].Index, _rows[_at]);
        }

        /// <summary>Each row with the `Index` it is keyed by.</summary>
        public EntryEnumerator Entries => new EntryEnumerator(_records);

        /// <summary>
        /// The row with this `Index`, or a thrown exception naming what was
        /// missing.
        /// </summary>
        /// <remarks>
        /// `GetByIndexOrThrow` under the spelling the language uses for a
        /// keyed collection. It throws because that is what `Dictionary` does here; a
        /// language whose own map answers with null generates a subscript that answers with
        /// null. spec/targets/table-collection-surface.md section 5.7.
        ///
        /// **This is the key, not the row's position.** `table[0]` is the row whose
        /// `Index` is 0, not the first row - the rows in order are
        /// `Records`. Nothing in the type says which, which is why the table itself is not
        /// subscriptable by position anywhere.
        ///
        /// It does not replace `FindByIndex`: a key that may be absent
        /// wants the one whose name says a miss is an ordinary answer.
        /// </remarks>
        public Record this[int key] => GetByIndexOrThrow(key);

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await NullableElementsAccessor.ReadAllBytesAsync(filename);

            // Unconditionally, and with whatever `NullableElementsAccessor.EncryptionKey` and `NullableElementsAccessor.MacKey`
            // hold - which is null unless the project set them. A file that is neither
            // encrypted nor signed comes back from this untouched, so the load path is the
            // same either way and there is no condition here that could be the wrong way
            // round. spec/wire/tcb-mac-and-signature.md.
            var reader = new TcbReader(TcbTable.Open(
                bytes, NullableElementsAccessor.EncryptionKey, NullableElementsAccessor.MacKey, NullableElementsAccessor.VerifyMac));

            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(TcbReader reader)
        {
            var columns = TcbTable.ReadHeader(reader, out int count);
            TcbColumnCursor cursor;
            byte[] presence;
            byte[] elementPresence;
            int elementAt;

            // Read into storage of its own and published at the end, which is what makes a
            // refresh atomic: nothing here touches what the table is currently holding, so a
            // file that turns out to be truncated - or a column this build cannot read -
            // leaves the previous rows in place and reports why.
            //
            // Sized once. The row count was checked against what the columns declare before
            // this point, so it is a number the file could actually hold rows for - and a
            // list that grows into twenty thousand rows reallocates fifteen times to get
            // there, copying everything each time.
            var records = new List<Record>(count);

            for (int i = 0; i < count; i++)
                records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        TcbTable.CheckColumn(column, "Listing.Index", TcbTable.KindScalar, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Listing.Index");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameI32(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._index = value;
                            } while (--n > 0);
                        }
                        break;

                    case 2:
                        TcbTable.CheckColumn(column, "Listing.Name", TcbTable.KindScalar, false, TcbTable.ElementString);
                        cursor = new TcbColumnCursor(reader, column, count, "Listing.Name");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameString(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._name = value;
                            } while (--n > 0);
                        }
                        break;

                    case 3:
                        TcbTable.CheckColumn(column, "Listing.Plain", TcbTable.KindArray, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Listing.Plain");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            int elementCount;
                            elementCount = cursor.NextLength();
                            record._plain = new int[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._plain[j] = cursor.NextI32();
                            }
                        }
                        break;

                    case 4:
                        TcbTable.CheckColumn(column, "Listing.Maybe", TcbTable.KindArray, true, TcbTable.ElementI32, TcbTable.ElementVarint);
                        presence = TcbTable.ReadPresence(reader, column, count);
                        cursor = new TcbColumnCursor(reader, column, count, "Listing.Maybe");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            int elementCount;
                            elementCount = cursor.NextLength();
                            record._maybe = new int[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._maybe[j] = cursor.NextI32();
                            }
                        }
                        for (int i = 0; i < count; i++)
                        {
                            records[i]._maybeHasValue = TcbTable.IsPresent(presence, i);

                            // The block carries a value for every row, so an absent one has
                            // just been given whatever was there. Putting the empty value
                            // back is what makes this path agree with the JSON one.
                            if (!records[i]._maybeHasValue)
                                records[i]._maybe = System.Array.Empty<int>();
                        }
                        break;

                    case 5:
                        TcbTable.CheckColumn(column, "Listing.Holes", TcbTable.KindArray, false, TcbTable.ElementI32, TcbTable.ElementVarint, elementNullable: true);
                        elementPresence = TcbTable.ReadElementPresence(reader, column);
                        elementAt = 0;
                        cursor = new TcbColumnCursor(reader, column, count, "Listing.Holes");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            int elementCount;
                            elementCount = cursor.NextLength();
                            record._holes = new int[elementCount];
                            record._holesHasValueAt = new bool[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._holesHasValueAt[j] =
                                    TcbTable.IsPresent(elementPresence, elementAt++);
                                record._holes[j] = cursor.NextI32();
                            }
                        }
                        break;

                    case 6:
                        TcbTable.CheckColumn(column, "Listing.Both", TcbTable.KindArray, true, TcbTable.ElementI32, TcbTable.ElementVarint, elementNullable: true);
                        presence = TcbTable.ReadPresence(reader, column, count);
                        elementPresence = TcbTable.ReadElementPresence(reader, column);
                        elementAt = 0;
                        cursor = new TcbColumnCursor(reader, column, count, "Listing.Both");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            int elementCount;
                            elementCount = cursor.NextLength();
                            record._both = new int[elementCount];
                            record._bothHasValueAt = new bool[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._bothHasValueAt[j] =
                                    TcbTable.IsPresent(elementPresence, elementAt++);
                                record._both[j] = cursor.NextI32();
                            }
                        }
                        for (int i = 0; i < count; i++)
                        {
                            records[i]._bothHasValue = TcbTable.IsPresent(presence, i);

                            // The block carries a value for every row, so an absent one has
                            // just been given whatever was there. Putting the empty value
                            // back is what makes this path agree with the JSON one.
                            if (!records[i]._bothHasValue)
                                records[i]._both = System.Array.Empty<int>();
                        }
                        break;

                    case 7:
                        TcbTable.CheckColumn(column, "Listing.Words", TcbTable.KindArray, false, TcbTable.ElementString, elementNullable: true);
                        elementPresence = TcbTable.ReadElementPresence(reader, column);
                        elementAt = 0;
                        cursor = new TcbColumnCursor(reader, column, count, "Listing.Words");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            int elementCount;
                            elementCount = cursor.NextLength();
                            record._words = new string[elementCount];
                            record._wordsHasValueAt = new bool[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._wordsHasValueAt[j] =
                                    TcbTable.IsPresent(elementPresence, elementAt++);
                                record._words[j] = cursor.NextString();
                            }
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                TcbTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping. Sized to the rows, so nothing rehashes on the way in, and a
            // duplicate key throws here - before any of this is visible.
            var recordsByIndex = new Dictionary<int, Record>(count);
            foreach (var record in records)
                recordsByIndex.Add(record.Index, record);

            // Published. Everything above succeeded, and the barrier is what keeps the writes
            // that built these from being seen after the references to them - a reader on
            // another thread gets the whole table or the previous one, never half of either.
            System.Threading.Thread.MemoryBarrier();

            _records = records;
            _recordsByIndex = recordsByIndex;

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }
} // namespace Tabbit.Fixtures.NullableElements
