// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef TABBIT_GENERATED_KEYTYPESACCESSOR_H
#define TABBIT_GENERATED_KEYTYPESACCESSOR_H

#include <cstddef>
#include <string>

#include "enums/KeyTypesAccessor_enum_slot.h"
#include "tables/KeyTypesAccessor_asset.h"
#include "tables/KeyTypesAccessor_ledger.h"
#include "tables/KeyTypesAccessor_slotting.h"
/// Every table, loaded together so cross-table references can be resolved.
class KeyTypesAccessor {
 public:
  const AssetTable& asset() const { return asset_; }
  const LedgerTable& ledger() const { return ledger_; }
  const SlottingTable& slotting() const { return slotting_; }

  /// Reads every table from `base_path`, then links the references between them.
  ///
  /// Safe to call on a loaded accessor. Every file is read into a table of its own and the
  /// references are linked among those, so a read that throws part way through leaves every
  /// table holding the load it already had, and no row points at a row from it.
  void read_all(const std::string& base_path, const std::string& file_extension = ".tcb") {
    AssetTable loaded_asset;
    loaded_asset.read(base_path + "/Asset" + file_extension);
    LedgerTable loaded_ledger;
    loaded_ledger.read(base_path + "/Ledger" + file_extension);
    SlottingTable loaded_slotting;
    loaded_slotting.read(base_path + "/Slotting" + file_extension);

    solve_cross_references(loaded_asset, loaded_ledger, loaded_slotting);

    asset_ = std::move(loaded_asset);
    ledger_ = std::move(loaded_ledger);
    slotting_ = std::move(loaded_slotting);
  }

 private:
  /// The tables arrive as arguments, which is how this links the load being read rather
  /// than the one already published.
  ///
  /// Every table is passed whether or not it takes part in a reference, so the call site
  /// is the same shape for every model. `[[maybe_unused]]` is what says so to the
  /// compiler: the gate builds with `-Wextra -Werror`, and a model where nothing
  /// references anything - which is most of them - otherwise fails to compile on the
  /// unused parameters.
  void solve_cross_references([[maybe_unused]] AssetTable& loaded_asset, [[maybe_unused]] LedgerTable& loaded_ledger, [[maybe_unused]] SlottingTable& loaded_slotting) {
    // No table references another.
  }

  AssetTable asset_;
  LedgerTable ledger_;
  SlottingTable slotting_;
};

#endif  // TABBIT_GENERATED_KEYTYPESACCESSOR_H
