// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

#ifndef TABBIT_GENERATED_MATRIXACCESSOR_ENUM_AFFINITY_H
#define TABBIT_GENERATED_MATRIXACCESSOR_ENUM_AFFINITY_H

#include <cstdint>
// Generated from test/fixtures/xlsx/matrix/matrix.xlsx : Enums : B2
/// What an attack is made of.
enum class Affinity : std::int32_t {
  /// no element
  None = 0,
  /// burns
  Fire = 1,
  /// soaks
  Water = 2,
  /// cuts
  Wind = 3,
};

#endif  // TABBIT_GENERATED_MATRIXACCESSOR_ENUM_AFFINITY_H
