<?php

// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace X;

require_once __DIR__ . '/../tabbit/TcbReader.php';
require_once __DIR__ . '/../enums/Keyword.php';
require_once __DIR__ . '/../A.php';

use Tabbit\TcbReader;
use Tabbit\TcbColumnCursor;
use Tabbit\RecordNotFoundException;
use Tabbit\Uuid;

/**
 * Generated from test/fixtures/xlsx/reserved-words/reserved-words.xlsx : ReservedWords : K2
 *
 * 이름이 TypeScript의 바인딩 예약어인 테이블. 주석은 한글이라 MSVC 코드페이지도 함께 확인합니다.
 */
final class PackageRecord
{
    /** primary index */
    public int $index = 0;
    /** 라벨 — 한글 주석 */
    public string $label = '';
    /** 예약어 라벨을 쓰는 enum 필드 */
    public Keyword $kind = Keyword::None;
}

/** Every row of Package. */
final class PackageTable
{
    /** @var list<PackageRecord> */
    public array $records = [];

    /** @var array<int, PackageRecord> */
    private array $byIndex = [];

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public function findByIndex(int $key): ?PackageRecord
    {
        return $this->byIndex[$key] ?? null;
    }

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex($key)->name at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public function getByIndexOrThrow(int $key): PackageRecord
    {
        $record = $this->byIndex[$key] ?? null;

        if ($record === null) {
            throw new RecordNotFoundException(
                "There is no record in table `Package` that corresponds to " .
                "field `Index` value " . $key . ".");
        }

        return $record;
    }

    /** Whether the table holds a row with this Index. */
    public function containsIndex(int $key): bool
    {
        return isset($this->byIndex[$key]);
    }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public function read(string $filename): void
    {
        // The keys go to fromFile because reading and opening are one call here: the
        // reader's constructor takes the whole file and opens the envelope itself. It does
        // so unconditionally, and with whatever A::$encryptionKey and
        // A::$macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from that untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/wire/tcb-mac-and-signature.md.
        $reader = TcbReader::fromFile(
            $filename, A::$encryptionKey,
            A::$macKey, A::$verifyMac);
        [$count, $columns] = $reader->readTableHeader();

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        $records = [];
        $byIndex = [];

        for ($i = 0; $i < $count; $i++) {
            $records[] = new PackageRecord();
        }

        foreach ($columns as $column) {
            $blockEnd = $reader->position() + $column['byteLength'];

            switch ($column['tag']) {
                case 1:
                    TcbReader::checkColumn($column, 'Package.Index', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Package.Index');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->index = $value;
                        }
                    }
                    break;

                case 2:
                    TcbReader::checkColumn($column, 'Package.Label', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Package.Label');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameString($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->label = $value;
                        }
                    }
                    break;

                case 3:
                    TcbReader::checkColumn($column, 'Package.Kind', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Package.Kind');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->kind = Keyword::tryFrom($value) ?? Keyword::None;
                        }
                    }
                    break;

                default:
                    // A column added after this code was generated.
                    $reader->skip($column['byteLength']);
                    break;
            }

            $reader->checkBlockEnd($column, $blockEnd);
        }

        foreach ($records as $record) {
            $byIndex[$record->index] = $record;
        }

        // Published, now that every column read.
        $this->records = $records;
        $this->byIndex = $byIndex;
    }
}
