// ------------------------------------------------------------------------------
// Code generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package multitarget

import (
	"strconv"
)

// HolderPickTarget was generated from test/fixtures/xlsx/multi-target/multi-target.xlsx : Holders : D4.
// Which table `Holder.Pick` points at. The column carries one id and the tables it may be a row of take separate id bands, so exactly one of them answers.
type HolderPickTarget int32

const (
	// No row of any of them.
	HolderPickTargetNone HolderPickTarget = 0
	// A row of `Weapon`.
	HolderPickTargetWeapon HolderPickTarget = 1
	// A row of `Armour`.
	HolderPickTargetArmour HolderPickTarget = 2
)

// String names the label, or renders the number when the value has none.
func (v HolderPickTarget) String() string {
	switch v {
	case HolderPickTargetNone:
		return "None"
	case HolderPickTargetWeapon:
		return "Weapon"
	case HolderPickTargetArmour:
		return "Armour"
	}

	return strconv.FormatInt(int64(v), 10)
}
