# ------------------------------------------------------------------------------
# Generated by Tabbit. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

import enum
import os

from . import tabbit
from .enum_affinity import Affinity


class ElementChartRecord:
    """Generated from test/fixtures/xlsx/matrix/matrix.xlsx : Grids : B11.

    How much an element does to another.
    """

    __slots__ = ("attacker", "rate")

    def __init__(self):
        self.attacker = Affinity(0)
        self.rate = []

    def __repr__(self):
        return "ElementChartRecord(attacker=%r, rate=%r)" % (self.attacker, self.rate)


class ElementChartTable:
    """Every row of ElementChart."""

    __slots__ = ("records", "by_attacker", "_column_axis")

    def __init__(self):
        self.records = []
        self.by_attacker = {}
        self._column_axis = None

    def __len__(self):
        """How many rows the table holds."""
        return len(self.records)

    def __iter__(self):
        """The rows, in the order the file wrote them.

        The list reference is read once, here. A refresh replaces the reference rather
        than its contents, so a loop already running keeps the rows it started with.
        """
        return iter(self.records)

    def link_column_axis(self, columns):
        """Hands this table the column axis its cells are positioned by.

        Called by the accessor once both files are read, and the length check is here rather
        than in the read. A grid is two files, either can be deployed without the other, and a
        row whose array is a different length from the axis is a row whose cells have moved.
        """
        for record in self.records:
            if len(record.rate) != len(columns.records):
                raise tabbit.TcbError(
                    "table `ElementChart` holds %d cells for `%r` and its column axis "
                    "`ElementChartColumn` holds %d keys; the two files are from different builds"
                    % (len(record.rate), record.attacker, len(columns.records)))

        self._column_axis = columns

    @property
    def row_keys(self):
        """The row axis keys, in the order the file wrote them."""
        return [record.attacker for record in self.records]

    @property
    def col_keys(self):
        """The column axis keys, in the order a row holds its cells."""
        if self._column_axis is None:
            return []

        return [record.defender for record in self._column_axis.records]

    def row(self, attacker):
        """One row of cells, or None when the grid has no such row.

        In the order col_keys is in, which is what makes a position mean something.
        """
        record = self.find_by_attacker(attacker)
        return None if record is None else record.rate

    def at(self, attacker, defender):
        """The cell where the two keys meet, or a raised error naming the one that missed.

        It raises rather than answering with the type's empty value, because a grid's empty
        value is one the sheet can write - 0 in a modifier table is a modifier of zero.
        """
        record, at = self._cell_at(attacker, defender)
        return record.rate[at]


    def _cell_at(self, attacker, defender):
        """Both lookups, done once for the readers above."""
        if self._column_axis is None:
            raise tabbit.TcbError(
                "table `ElementChart` has no column axis yet; "
                "read `ElementChartColumn` before reading a cell")

        record = self.find_by_attacker(attacker)

        if record is None:
            raise tabbit.RecordNotFoundError(
                "table `ElementChart` has no row `%r`" % (attacker,))

        column = self._column_axis.find_by_defender(defender)

        if column is None:
            raise tabbit.RecordNotFoundError(
                "table `ElementChart` has no column `%r`" % (defender,))

        return record, column.at

    def find_by_attacker(self, key):
        """The row with this Attacker, or None when the table has none.

        The lookup to reach for when a missing row is an ordinary answer - an optional
        reference, a key that came from user input.
        """
        return self.by_attacker.get(key)

    def get_by_attacker_or_throw(self, key):
        """The row with this Attacker, or a raised error naming what was missing.

        For a key that has to be there - one from another table, or a constant. The name
        says it raises, because a caller reading `get_by_attacker(key).name` at a
        glance cannot otherwise tell whether the next line is a check or a try.
        """
        record = self.by_attacker.get(key)

        if record is None:
            raise tabbit.RecordNotFoundError(
                "there is no record in table `ElementChart` that corresponds to "
                "field `Attacker` value %r" % (key,))

        return record

    def contains_attacker(self, key):
        """Whether the table holds a row with this Attacker."""
        return key in self.by_attacker


    def __getitem__(self, key):
        """The row with this Attacker, or a raised error naming what was missing.

        get_by_attacker_or_throw under the spelling Python uses for a keyed
        collection. It raises because that is what dict does; a language whose own map
        answers with null generates a subscript that answers with null.
        spec/targets/table-collection-surface.md section 5.7.

        This is the key, not the row's position. table[0] is the row whose
        Attacker is 0, not the first row - the rows in order are .records.
        """
        return self.get_by_attacker_or_throw(key)


    def items(self):
        """Each row with the Attacker it is keyed by.

        What this saves a caller is not the key value - the row carries it - but having to
        know which column the key is: Attacker here, something else in the
        next table.

        The rows come in the order the file wrote them rather than the order the dict holds
        them, which makes this and iterating the table agree. Only the primary key has this:
        a table keyed by several columns together has no single key value to pair a row
        with.
        """
        return ((record.attacker, record) for record in self.records)

    def read(self, filename):
        """Loads the table from a .tcb file written by Tabbit.

        Column by column, matched by tag rather than position: a column this build does
        not know is skipped by its block length, and one whose type changed incompatibly
        fails naming the field.
        """
        # Imported here rather than at the top: `tables` imports this module,
        # so at import time it is half built and at call time it is not.
        from .tables import Tables

        # Opened unconditionally, and with whatever `Tables.encryption_key` and
        # `Tables.mac_key` hold - which is None unless the project set them. A file that is
        # neither encrypted nor signed comes back from this untouched, so the load path is
        # the same either way and there is no condition here that could be the wrong way
        # round. spec/wire/tcb-mac-and-signature.md.
        reader = tabbit.Reader(tabbit.open(
            tabbit.read_all_bytes(filename), Tables.encryption_key,
            Tables.mac_key, Tables.verify_mac))
        count, columns = tabbit.read_table_header(reader)

        # Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        records = [ElementChartRecord() for _ in range(count)]

        for column in columns:
            block_end = reader.position + column.byte_length
            if column.tag == 1:
                tabbit.check_column(column, "ElementChart.Attacker", tabbit.KIND_SCALAR, False, (tabbit.ELEMENT_VARINT,))
                cursor = tabbit.ColumnCursor(reader, column, count, "ElementChart.Attacker")
                at = 0
                while at < count:
                    n, value = cursor.next_same_i32(count - at)
                    for i in range(at, at + n):
                        records[i].attacker = Affinity(value)
                    at += n
            elif column.tag == 2:
                tabbit.check_column(column, "ElementChart.Rate", tabbit.KIND_ARRAY, False, (tabbit.ELEMENT_F32,))
                cursor = tabbit.ColumnCursor(reader, column, count, "ElementChart.Rate")
                for record in records:
                    element_count = cursor.next_length()
                    record.rate = [cursor.next_f32() for _ in range(element_count)]
            else:
                # A column added after this code was generated.
                reader.skip(column.byte_length)

            tabbit.check_block_end(reader, column, block_end)

        by_attacker = {record.attacker: record for record in records}

        # Published, now that every column read.
        self.records = records
        self.by_attacker = by_attacker
