// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package recordref;

import tabbit.TcbReader;

// Generated from test/fixtures/xlsx/record-ref/record-ref.xlsx : Records : J2
/** A record array whose first member is a reference. */
public final class LoadoutRecord {
    /** primary index */
    public int index;
    /** element 1, the reference */
    public SlotEntry[] slot = newSlotEntryArray(2);

    /** One element of slot. */
    public static final class SlotEntry {
        /** element 1, the reference */
        public ItemRecord itemId;
        public int itemIdIndex;
        /** element 1, a second reference to the same table */
        public ItemRecord swapId;
        public int swapIdIndex;
        /** element 1, an ordinary member */
        public int count;
    }

    /**
     * A SlotEntry array with its elements constructed.
     *
     * Java fills an array of objects with nulls, and the length here is the sheet's column
     * count - known at generation - so the row can arrive with the elements already there
     * and each member column simply assigns into them.
     */
    private static SlotEntry[] newSlotEntryArray(int length) {
        SlotEntry[] array = new SlotEntry[length];

        for (int i = 0; i < length; i++) {
            array[i] = new SlotEntry();
        }

        return array;
    }

}
