/* ------------------------------------------------------------------------------
 * Generated by Tabbit. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#ifndef KEY_TYPES_ENUM_SLOT_H
#define KEY_TYPES_ENUM_SLOT_H

/* Generated from test/fixtures/xlsx/key-types/key-types.xlsx : Enums : B2
 *
 * Where a piece of equipment goes.
 */
typedef enum KeyTypes_Slot_t {
  /* no slot */
  KEY_TYPES_SLOT_NONE = 0,
  /* worn on the head */
  KEY_TYPES_SLOT_HEAD = 1,
  /* worn on the body */
  KEY_TYPES_SLOT_BODY = 2,
  /* worn on the feet */
  KEY_TYPES_SLOT_FEET = 3,
} KeyTypes_Slot_t;

#endif /* KEY_TYPES_ENUM_SLOT_H */
