// ------------------------------------------------------------------------------
// <auto-generated>
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections.Generic;
using System.Threading.Tasks;

// Tabbit's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using Tabbit.Binary;

namespace Tabbit.Fixtures.CompositeKey
{
    /// <summary>
    /// A composite primary key of strings, beside a single-column secondary one.
    /// </summary>
    [System.Serializable]
    public partial class RouteTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Values
            /// <summary>
            /// where it starts
            /// </summary>
            public string From => _from;

            /// <summary>
            /// where it ends
            /// </summary>
            public string To => _to;

            /// <summary>
            /// unique on its own
            /// </summary>
            public string Code => _code;

            /// <summary>
            /// anything
            /// </summary>
            public int Distance => _distance;
            #endregion

            #region Storage
            internal string _from = "";
            internal string _to = "";
            internal string _code = "";
            internal int _distance;
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"From\":"); ToStringHelper.ToString(From, sb);
                sb.Append(",\"To\":"); ToStringHelper.ToString(To, sb);
                sb.Append(",\"Code\":"); ToStringHelper.ToString(Code, sb);
                sb.Append(",\"Distance\":"); ToStringHelper.ToString(Distance, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "From", "To", "Code", "Distance" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.From, r.To, r.Code, r.Distance });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        /// <remarks>
        /// The list a read publishes, not one a read fills. Whoever holds this reference holds
        /// the rows as they were when they took it, and a refresh underneath them replaces the
        /// reference rather than the contents - so an iteration in progress neither tears nor
        /// throws, and a read that fails leaves the previous rows exactly where they were.
        /// </remarks>
        public List<Record> Records => _records;
        private List<Record> _records = new List<Record>();

        #region Indexing by 'Code'
        public Dictionary<string, Record> RecordsByCode => _recordsByCode;
        private Dictionary<string, Record> _recordsByCode = new Dictionary<string, Record>();

        /// <summary>
        /// The row with this `Code`, or null when the table has none.
        /// </summary>
        /// <remarks>
        /// The lookup to reach for when a missing row is an ordinary answer - an optional
        /// reference, a key that came from user input. Every language Tabbit generates has
        /// this one under the same name.
        /// </remarks>
        public Record FindByCode(string key)
            => _recordsByCode.TryGetValue(key, out Record record) ? record : null;

        /// <summary>
        /// The row with this `Code`, or a thrown exception naming what was
        /// missing.
        /// </summary>
        /// <remarks>
        /// For a key that has to be there - one from another table, or a constant. The name
        /// says it throws, because a caller reading `GetByCode(id).Name` at
        /// a glance cannot otherwise tell whether the next line is a null check or a catch.
        /// </remarks>
        public Record GetByCodeOrThrow(string key)
        {
            if (!_recordsByCode.TryGetValue(key, out Record record))
                throw new TabbitException($"There is no record in table `Route` that corresponds to field `Code` value {key}");

            return record;
        }

        /// <summary>Whether the table holds a row with this `Code`.</summary>
        public bool ContainsCode(string key) => _recordsByCode.ContainsKey(key);
        #endregion // Indexing by `Code`

        #region Indexing by 'From and To'
        private Dictionary<string, Record> _recordsByFromAndTo = new Dictionary<string, Record>();

        /// <summary>Joins the columns of the `From and To` key into the text the map is keyed by.</summary>
        private static string KeyOfFromAndTo(string fromKey, string toKey)
        {
            var parts = new string[]
            {
                fromKey,
                toKey,
            };

            var text = new StringBuilder();

            foreach (var part in parts)
                text.Append(part.Length).Append(':').Append(part);

            return text.ToString();
        }

        /// <summary>
        /// The row with this `From and To`, or null when the table has none.
        /// </summary>
        /// <remarks>
        /// The lookup to reach for when a missing row is an ordinary answer - an optional
        /// reference, a key that came from user input. Every language Tabbit generates has
        /// this one under the same name.
        /// </remarks>
        public Record FindByFromAndTo(string fromKey, string toKey)
            => _recordsByFromAndTo.TryGetValue(KeyOfFromAndTo(fromKey, toKey), out Record record) ? record : null;

        /// <summary>
        /// The row with this `From and To`, or a thrown exception naming what was
        /// missing.
        /// </summary>
        public Record GetByFromAndToOrThrow(string fromKey, string toKey)
        {
            if (!_recordsByFromAndTo.TryGetValue(KeyOfFromAndTo(fromKey, toKey), out Record record))
                throw new TabbitException($"There is no record in table `Route` that corresponds to field `From and To` value ({fromKey}, {toKey})");

            return record;
        }

        /// <summary>Whether the table holds a row with this `From and To`.</summary>
        public bool ContainsFromAndTo(string fromKey, string toKey) => _recordsByFromAndTo.ContainsKey(KeyOfFromAndTo(fromKey, toKey));
        #endregion // Indexing by `From and To`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await CompositeKeyAccessor.ReadAllBytesAsync(filename);

            // Unconditionally, and with whatever `CompositeKeyAccessor.EncryptionKey` and `CompositeKeyAccessor.MacKey`
            // hold - which is null unless the project set them. A file that is neither
            // encrypted nor signed comes back from this untouched, so the load path is the
            // same either way and there is no condition here that could be the wrong way
            // round. spec/wire/tcb-mac-and-signature.md.
            var reader = new TcbReader(TcbTable.Open(
                bytes, CompositeKeyAccessor.EncryptionKey, CompositeKeyAccessor.MacKey, CompositeKeyAccessor.VerifyMac));

            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(TcbReader reader)
        {
            var columns = TcbTable.ReadHeader(reader, out int count);
            TcbColumnCursor cursor;

            // Read into storage of its own and published at the end, which is what makes a
            // refresh atomic: nothing here touches what the table is currently holding, so a
            // file that turns out to be truncated - or a column this build cannot read -
            // leaves the previous rows in place and reports why.
            //
            // Sized once. The row count was checked against what the columns declare before
            // this point, so it is a number the file could actually hold rows for - and a
            // list that grows into twenty thousand rows reallocates fifteen times to get
            // there, copying everything each time.
            var records = new List<Record>(count);

            for (int i = 0; i < count; i++)
                records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        TcbTable.CheckColumn(column, "Route.From", TcbTable.KindScalar, false, TcbTable.ElementString);
                        cursor = new TcbColumnCursor(reader, column, count, "Route.From");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameString(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._from = value;
                            } while (--n > 0);
                        }
                        break;

                    case 2:
                        TcbTable.CheckColumn(column, "Route.To", TcbTable.KindScalar, false, TcbTable.ElementString);
                        cursor = new TcbColumnCursor(reader, column, count, "Route.To");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameString(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._to = value;
                            } while (--n > 0);
                        }
                        break;

                    case 3:
                        TcbTable.CheckColumn(column, "Route.Code", TcbTable.KindScalar, false, TcbTable.ElementString);
                        cursor = new TcbColumnCursor(reader, column, count, "Route.Code");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameString(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._code = value;
                            } while (--n > 0);
                        }
                        break;

                    case 4:
                        TcbTable.CheckColumn(column, "Route.Distance", TcbTable.KindScalar, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Route.Distance");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameI32(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._distance = value;
                            } while (--n > 0);
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                TcbTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping. Sized to the rows, so nothing rehashes on the way in, and a
            // duplicate key throws here - before any of this is visible.
            var recordsByCode = new Dictionary<string, Record>(count);
            foreach (var record in records)
                recordsByCode.Add(record.Code, record);
            var recordsByFromAndTo = new Dictionary<string, Record>(count);
            foreach (var record in records)
                recordsByFromAndTo.Add(KeyOfFromAndTo(record.From, record.To), record);

            // Published. Everything above succeeded, and the barrier is what keeps the writes
            // that built these from being seen after the references to them - a reader on
            // another thread gets the whole table or the previous one, never half of either.
            System.Threading.Thread.MemoryBarrier();

            _records = records;
            _recordsByCode = recordsByCode;
            _recordsByFromAndTo = recordsByFromAndTo;

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }
} // namespace Tabbit.Fixtures.CompositeKey
