-- ------------------------------------------------------------------------------
-- Generated by Tabbit. DO NOT EDIT.
--
-- Changes to this file may cause incorrect behavior and will be lost if the code is
-- regenerated.
-- ------------------------------------------------------------------------------

local _root = (...):match("^(.-)[^%.]+%.[^%.]+$")
local tcb = require(_root .. "tabbit.tcb_reader")

---@class DeckSlotEntry
---@field id integer
---@field label string
local DeckSlotEntryMeta = tcb.strictType("an element of DeckRecord.slot", { "id", "label" })

---@return DeckSlotEntry
local function newDeckSlotEntry()
  return setmetatable({
    id = 0,
    label = "",
  }, DeckSlotEntryMeta)
end

---@class DeckHomeEntryAt
---@field x number
---@field y number
local DeckHomeEntryAtMeta = tcb.strictType("a record inside DeckRecord.home", { "x", "y" })

---@return DeckHomeEntryAt
local function newDeckHomeEntryAt()
  return setmetatable({
    x = 0.0,
    y = 0.0,
  }, DeckHomeEntryAtMeta)
end

---@class DeckHomeEntry
---@field at DeckHomeEntryAt
local DeckHomeEntryMeta = tcb.strictType("an element of DeckRecord.home", { "at" })

---@return DeckHomeEntry
local function newDeckHomeEntry()
  return setmetatable({
    at = newDeckHomeEntryAt(),
  }, DeckHomeEntryMeta)
end

-- Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Spawn : G2.
-- An array of records, and a record inside a record.
---@class DeckRecord
---@field index integer
---@field slot DeckSlotEntry[]
---@field home DeckHomeEntry
local DeckRecordMeta = tcb.strictType("a `Deck` row", { "index", "slot", "home" })

---@return DeckRecord
local function newDeckRecord()
  return setmetatable({
    index = 0,
    slot = tcb.filledArray(2, newDeckSlotEntry),
    home = newDeckHomeEntry(),
  }, DeckRecordMeta)
end

---@class DeckTable
---@field records DeckRecord[]
local DeckTable = {}

local DeckTableMeta = tcb.strictInstance("the `Deck` table", DeckTable, { "records", "byIndex" })

function DeckTable.new()
  return setmetatable({
    records = {},
    byIndex = {},
  }, DeckTableMeta)
end

-- How many rows the table holds.
--
-- A method rather than `#table`: LuaJIT 2.1 does not call `__len` on a table, so the
-- operator would answer on 5.3+ and not on the other runtime this output has to run on.
function DeckTable:count()
  return #self.records
end

-- The rows, in the order the file wrote them - `for row in table:iter() do`.
--
-- The list is read once, here. A refresh replaces it rather than its contents, so a loop
-- already running keeps the rows it started with.
function DeckTable:iter()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    return records[i]
  end
end

-- The row with this Index, or nil when the table has none: the lookup to
-- reach for when a missing row is an ordinary answer.
function DeckTable:findByIndex(key)
  return self.byIndex[key]
end

-- The row with this Index, or a raised error naming what was missing -
-- for a key that has to be there.
function DeckTable:getByIndexOrThrow(key)
  local record = self:findByIndex(key)

  if record == nil then
    tcb.fail("there is no record in table `Deck` that corresponds to " ..
      "field `Index` value %s", tostring(key))
  end

  return record
end

-- Whether the table holds a row with this Index.
function DeckTable:containsIndex(key)
  return self:findByIndex(key) ~= nil
end


-- Each row with the Index it is keyed by -
-- `for key, row in table:entries() do`.
--
-- What this saves a caller is not the key value - the row carries it - but having to know
-- which column the key is: Index here, something else in the next table.
--
-- The rows come in the order the file wrote them rather than the order the map holds them,
-- which makes this and `iter` agree. Only the primary key has this: a table keyed by
-- several columns together has no single key value to pair a row with.
function DeckTable:entries()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    local record = records[i]

    if record == nil then
      return nil
    end

    return record.index, record
  end
end


-- Loads the table from the bytes of a .tcb file written by Tabbit. Column by column,
-- matched by tag rather than position: a column this build does not know is skipped by
-- its block length, and one whose type changed incompatibly fails naming the field.
function DeckTable:readBytes(data)
  -- Required here rather than at the top: the accessor requires this module, so at load
  -- time it is half built and at call time it is not.
  local accessor = require(_root .. "tables")

  -- Opened unconditionally, with whatever keys the accessor holds - nil unless the
  -- project set them. A file that is neither encrypted nor signed comes back untouched,
  -- so the load path is the same either way. spec/wire/tcb-mac-and-signature.md.
  local reader = tcb.newReader(tcb.open(
    data, accessor.encryptionKey, accessor.macKey, accessor.verifyMac))
  local count, columns = tcb.readTableHeader(reader)

  -- Read into storage of its own and published at the end: reading a table that is
  -- already loaded is a refresh, and one that turns out to be unreadable has to leave
  -- the rows already there alone.
  local records = {}

  for i = 1, count do
    records[i] = newDeckRecord()
  end

  for c = 1, #columns do
    local column = columns[c]
    local blockEnd = reader.position + column.byteLength

    if column.tag == 1 then
      tcb.checkColumn(column, "Deck.Index", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Deck.Index")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].index = value
        end

        at = at + n
      end
    elseif column.tag == 2 then
      tcb.checkColumn(column, "Deck.Slot.Id", tcb.KIND_ARRAY, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Deck.Slot.Id")
      for i = 1, count do
        local record = records[i]
        local elementCount = cursor:nextLength()
        -- The first member builds the list; the rest check. Building it again would
        -- discard what the members before it wrote, and taking the shorter of two
        -- counts would shift every value after it.
        record.slot = tcb.filledArray(elementCount, newDeckSlotEntry)

        for element = 1, elementCount do
          record.slot[element].id = cursor:nextI32()
        end
      end
    elseif column.tag == 3 then
      tcb.checkColumn(column, "Deck.Slot.Label", tcb.KIND_ARRAY, false, { tcb.ELEMENT_STRING })
      local cursor = tcb.newCursor(reader, column, count, "Deck.Slot.Label")
      for i = 1, count do
        local record = records[i]
        local elementCount = cursor:nextLength()
        if #record.slot ~= elementCount then
          tcb.fail("Deck: the file gives one member of this record a " ..
            "different element count than another")
        end

        for element = 1, elementCount do
          record.slot[element].label = cursor:nextString()
        end
      end
    elseif column.tag == 4 then
      tcb.checkColumn(column, "Deck.Home.At.X", tcb.KIND_SCALAR, false, { tcb.ELEMENT_F32 })
      local cursor = tcb.newCursor(reader, column, count, "Deck.Home.At.X")
      for i = 1, count do
        local record = records[i]
        record.home.at.x = cursor:nextF32()
      end
    elseif column.tag == 5 then
      tcb.checkColumn(column, "Deck.Home.At.Y", tcb.KIND_SCALAR, false, { tcb.ELEMENT_F32 })
      local cursor = tcb.newCursor(reader, column, count, "Deck.Home.At.Y")
      for i = 1, count do
        local record = records[i]
        record.home.at.y = cursor:nextF32()
      end
    else
      -- A column added after this code was generated.
      reader:skip(column.byteLength)
    end

    tcb.checkBlockEnd(reader, column, blockEnd)
  end

  local byIndex = {}

  for i = 1, #records do
    byIndex[records[i].index] = records[i]
  end

  -- Published, now that every column read.
  self.records = records
  self.byIndex = byIndex
end

-- The same load from a file on disk.
function DeckTable:read(filename)
  self:readBytes(tcb.readAllBytes(filename))
end

return DeckTable
