-- ------------------------------------------------------------------------------
-- Generated by Tabbit. DO NOT EDIT.
--
-- Changes to this file may cause incorrect behavior and will be lost if the code is
-- regenerated.
-- ------------------------------------------------------------------------------

local _root = (...):match("^(.-)[^%.]+%.[^%.]+$")
local tcb = require(_root .. "tabbit.tcb_reader")
local Effect = require(_root .. "structs.struct_effect")

---@class SkillEffectEntry
---@field type integer
---@field chance integer
---@field damage integer
---@field amount integer
local SkillEffectEntryMeta = tcb.strictType("an element of SkillRecord.effect", { "type", "chance", "damage", "amount" })

---@return SkillEffectEntry
local function newSkillEffectEntry()
  return setmetatable({
    type = 0,
    chance = 0,
    damage = 0,
    amount = 0,
  }, SkillEffectEntryMeta)
end

-- Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Skill : B2.
-- Every variant's members side by side; a row fills its own.
---@class SkillRecord
---@field index integer
---@field name string
---@field effect SkillEffectEntry
local SkillRecordMeta = tcb.strictType("a `Skill` row", { "index", "name", "effect" })

---@return SkillRecord
local function newSkillRecord()
  return setmetatable({
    index = 0,
    name = "",
    effect = newSkillEffectEntry(),
  }, SkillRecordMeta)
end

---@class SkillTable
---@field records SkillRecord[]
local SkillTable = {}

local SkillTableMeta = tcb.strictInstance("the `Skill` table", SkillTable, { "records", "byIndex" })

function SkillTable.new()
  return setmetatable({
    records = {},
    byIndex = {},
  }, SkillTableMeta)
end

-- How many rows the table holds.
--
-- A method rather than `#table`: LuaJIT 2.1 does not call `__len` on a table, so the
-- operator would answer on 5.3+ and not on the other runtime this output has to run on.
function SkillTable:count()
  return #self.records
end

-- The rows, in the order the file wrote them - `for row in table:iter() do`.
--
-- The list is read once, here. A refresh replaces it rather than its contents, so a loop
-- already running keeps the rows it started with.
function SkillTable:iter()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    return records[i]
  end
end

-- The row with this Index, or nil when the table has none: the lookup to
-- reach for when a missing row is an ordinary answer.
function SkillTable:findByIndex(key)
  return self.byIndex[key]
end

-- The row with this Index, or a raised error naming what was missing -
-- for a key that has to be there.
function SkillTable:getByIndexOrThrow(key)
  local record = self:findByIndex(key)

  if record == nil then
    tcb.fail("there is no record in table `Skill` that corresponds to " ..
      "field `Index` value %s", tostring(key))
  end

  return record
end

-- Whether the table holds a row with this Index.
function SkillTable:containsIndex(key)
  return self:findByIndex(key) ~= nil
end


-- Each row with the Index it is keyed by -
-- `for key, row in table:entries() do`.
--
-- What this saves a caller is not the key value - the row carries it - but having to know
-- which column the key is: Index here, something else in the next table.
--
-- The rows come in the order the file wrote them rather than the order the map holds them,
-- which makes this and `iter` agree. Only the primary key has this: a table keyed by
-- several columns together has no single key value to pair a row with.
function SkillTable:entries()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    local record = records[i]

    if record == nil then
      return nil
    end

    return record.index, record
  end
end


-- Loads the table from the bytes of a .tcb file written by Tabbit. Column by column,
-- matched by tag rather than position: a column this build does not know is skipped by
-- its block length, and one whose type changed incompatibly fails naming the field.
function SkillTable:readBytes(data)
  -- Required here rather than at the top: the accessor requires this module, so at load
  -- time it is half built and at call time it is not.
  local accessor = require(_root .. "tables")

  -- Opened unconditionally, with whatever keys the accessor holds - nil unless the
  -- project set them. A file that is neither encrypted nor signed comes back untouched,
  -- so the load path is the same either way. spec/wire/tcb-mac-and-signature.md.
  local reader = tcb.newReader(tcb.open(
    data, accessor.encryptionKey, accessor.macKey, accessor.verifyMac))
  local count, columns = tcb.readTableHeader(reader)

  -- Read into storage of its own and published at the end: reading a table that is
  -- already loaded is a refresh, and one that turns out to be unreadable has to leave
  -- the rows already there alone.
  local records = {}

  for i = 1, count do
    records[i] = newSkillRecord()
  end

  for c = 1, #columns do
    local column = columns[c]
    local blockEnd = reader.position + column.byteLength

    if column.tag == 1 then
      tcb.checkColumn(column, "Skill.Index", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Skill.Index")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].index = value
        end

        at = at + n
      end
    elseif column.tag == 2 then
      tcb.checkColumn(column, "Skill.Name", tcb.KIND_SCALAR, false, { tcb.ELEMENT_STRING })
      local cursor = tcb.newCursor(reader, column, count, "Skill.Name")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameString(count - at)

        for i = at + 1, at + n do
          records[i].name = value
        end

        at = at + n
      end
    elseif column.tag == 3 then
      tcb.checkColumn(column, "Skill.Effect.Type", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Skill.Effect.Type")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].effect.type = value
        end

        at = at + n
      end
    elseif column.tag == 4 then
      tcb.checkColumn(column, "Skill.Effect.Chance", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Skill.Effect.Chance")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].effect.chance = value
        end

        at = at + n
      end
    elseif column.tag == 5 then
      tcb.checkColumn(column, "Skill.Effect.Damage", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Skill.Effect.Damage")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].effect.damage = value
        end

        at = at + n
      end
    elseif column.tag == 6 then
      tcb.checkColumn(column, "Skill.Effect.Amount", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Skill.Effect.Amount")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].effect.amount = value
        end

        at = at + n
      end
    else
      -- A column added after this code was generated.
      reader:skip(column.byteLength)
    end

    tcb.checkBlockEnd(reader, column, blockEnd)
  end

  local byIndex = {}

  for i = 1, #records do
    byIndex[records[i].index] = records[i]
  end

  -- Published, now that every column read.
  self.records = records
  self.byIndex = byIndex
end

-- The same load from a file on disk.
function SkillTable:read(filename)
  self:readBytes(tcb.readAllBytes(filename))
end


--- What one row's Effect is. Narrow it on `.kind`.
---@param row SkillRecord
function SkillTable.effectOf(row)
  return SkillTable.effectElement(row.effect)
end

--- Builds one value from the entry the read filled.
function SkillTable.effectElement(entry)
  local built

  if entry.type == 1 then
    built = Effect.newDamageEffect()
    built.chance = entry.chance
    built.damage = entry.damage
  elseif entry.type == 2 then
    built = Effect.newHealEffect()
    built.chance = entry.chance
    built.amount = entry.amount
  elseif entry.type == 3 then
    built = Effect.newNoEffect()
    built.chance = entry.chance
  else
    error("Effect: no variant is numbered "
          .. tostring(entry.type))
  end

  return built
end

return SkillTable
