// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package tabbit.fixtures.docshowcase;

import tabbit.TcbReader;

// Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Shop : F2
/** What each shop sells. */
public final class ShopEntryRecord {
    /** primary index */
    public int index;
    /** which shop */
    public int shopId;
    public ShopRecord shopByShopId;
    /** which potion */
    public int potionId;
    public PotionRecord potionByPotionId;
    /** how many */
    public int stock;

}
