/* ------------------------------------------------------------------------------
 * Generated by Tabbit. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#include "tables/RecordRef_Pose.h"

#include <string.h>

static bool RecordRef_PoseParse(RecordRef_PoseTable_t* table, tb_reader* reader) {
  int32_t row;
  int32_t at;
  tb_column* columns = NULL;
  int32_t column_count = 0;
  tb_cursor cursor;

  if (!tb_read_table_header(reader, &table->count, &columns, &column_count))
    return false;

  if (table->count > 0) {
    table->records = (RecordRef_PoseRecord_t*)tb_arena_alloc(
      &table->arena, (size_t)table->count * sizeof *table->records);

    if (table->records == NULL)
      return tb_fail_with(reader, "out of memory allocating the rows");

    table->by_index = (tb_index_entry*)tb_arena_alloc(
      &table->arena, (size_t)table->count * sizeof *table->by_index);

    if (table->by_index == NULL)
      return tb_fail_with(reader, "out of memory allocating the Index index");
  }

  /* Column by column, matched by tag rather than by position: a column this build has
   * no member for is skipped by its declared length, and one whose type no longer fits
   * the member stops the read naming the field. Rows arrive with every member at an
   * empty value, so one the file has nothing for keeps it. */
  for (at = 0; at < column_count && !tb_failed(reader); ++at) {
    const tb_column* column = &columns[at];
    int32_t block_end = reader->position + column->byte_length;

    switch (column->tag) {

    case 1:
      (void)tb_check_column(reader, column, "Pose.Index", TB_KIND_SCALAR, false, TB_ELEMENT_MASK(TB_ELEMENT_I32) | TB_ELEMENT_MASK(TB_ELEMENT_VARINT));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Pose.Index");

      for (row = 0; row < table->count && !tb_failed(reader); ++row) {
        RecordRef_PoseRecord_t* record = &table->records[row];

        (void)tb_cursor_next_i32(&cursor, &record->index);
      }
      break;

    case 2:
      (void)tb_check_column(reader, column, "Pose.Step.ClipId", TB_KIND_ARRAY, false, TB_ELEMENT_MASK(TB_ELEMENT_STRING));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Pose.Step.ClipId");

      for (row = 0; row < table->count && !tb_failed(reader); ++row) {
        RecordRef_PoseRecord_t* record = &table->records[row];
        int32_t element_count = 0;
        int32_t element;

        (void)tb_cursor_next_length(&cursor, &element_count);

        /* The first member allocates; the rest check. Allocating again would discard what
         * the members before it wrote, and taking the shorter of two counts would shift
         * every value after it. */
        record->step_count = element_count;
        record->step = (struct RecordRef_PoseRecord_t_step_entry*)tb_arena_alloc(
          &table->arena, (size_t)element_count * sizeof *record->step);

        if (element_count > 0 && record->step == NULL)
          return tb_fail_with(reader, "out of memory allocating a record array");

        for (element = 0; element < element_count && !tb_failed(reader); ++element)
          (void)tb_cursor_next_string(&cursor, &record->step[element].clip_id_index);
      }
      break;

    case 3:
      (void)tb_check_column(reader, column, "Pose.Step.Weight", TB_KIND_ARRAY, false, TB_ELEMENT_MASK(TB_ELEMENT_I32) | TB_ELEMENT_MASK(TB_ELEMENT_VARINT));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Pose.Step.Weight");

      for (row = 0; row < table->count && !tb_failed(reader); ++row) {
        RecordRef_PoseRecord_t* record = &table->records[row];
        int32_t element_count = 0;
        int32_t element;

        (void)tb_cursor_next_length(&cursor, &element_count);

        if (record->step_count != element_count)
          return tb_fail_with(reader,
            "the file gives one member of a record a different element count than another");

        for (element = 0; element < element_count && !tb_failed(reader); ++element)
          (void)tb_cursor_next_i32(&cursor, &record->step[element].weight);
      }
      break;

    default:
      /* A column this build has no member for: added to the schema after the code
       * was generated, or removed from the code while the data still carries it.
       * The block's declared length is the whole of what skipping needs to know. */
      (void)tb_skip(reader, column->byte_length);
      break;
    }

    if (!tb_check_block_end(reader, column, block_end))
      return false;
  }

  if (tb_failed(reader))
    return false;

  /* The keys can only be gathered once every column has been read: the column that
   * carries one arrives wherever the file happens to put it. */
  for (row = 0; row < table->count; ++row) {
    table->by_index[row].key = table->records[row].index;
    table->by_index[row].position = row;
  }

  tb_index_sort(table->by_index, table->count);

  return true;
}

bool RecordRef_PoseLoad(RecordRef_PoseTable_t* table, const char* filename,
                   char* error, size_t error_size) {
  uint8_t* bytes = NULL;
  int32_t length = 0;
  const uint8_t* opened = NULL;
  int32_t opened_length = 0;
  tb_reader reader;
  bool ok;

  /* Loaded beside whatever the table is already holding, arena and all, and swapped in
   * only if it worked. That is what makes a reload safe: reading a patched file that
   * turns out to be truncated - or to carry a column this build cannot read - leaves the
   * rows the caller has pointers to exactly where they were.
   *
   * It also has to be this way round for the memory. The table owns its arena, and
   * zeroing the table before reading - which is what this did - dropped that arena
   * without freeing it, so every reload leaked the whole of the previous load. */
  RecordRef_PoseTable_t loaded;

  memset(&loaded, 0, sizeof loaded);

  if (!tb_read_all_bytes(filename, &bytes, &length)) {
    tb_copy_error(error, error_size, filename, "cannot be read");
    return false;
  }

  /* Opened unconditionally, with whatever RecordRef_EncryptionKey and
   * RecordRef_MacKey hold - NULL unless the project set them. A file that is
   * neither encrypted nor signed comes back from this untouched, so the load path is the
   * same either way and there is no condition here that could be the wrong way round.
   * spec/tcb-mac-and-signature.md.
   *
   * What comes back is a window onto `bytes` rather than a copy of it, which is why the
   * buffer is still what tb_free_bytes is given below. */
  if (!tb_open(bytes, length, RecordRef_EncryptionKey,
        RecordRef_EncryptionKeyLength, RecordRef_MacKey,
        RecordRef_MacKeyLength, RecordRef_VerifyMac,
        &opened, &opened_length, error, error_size)) {
    tb_free_bytes(bytes);
    return false;
  }

  tb_reader_init(&reader, opened, opened_length, &loaded.arena);

  ok = RecordRef_PoseParse(&loaded, &reader);

  if (ok) {
    /* The previous load goes now, and not before: its arena holds the strings and
     * arrays the caller was reading up to this line. */
    RecordRef_PoseFree(table);
    *table = loaded;
  } else {
    tb_copy_error(error, error_size, filename, tb_error(&reader));

    /* Nothing half-read is kept, and the table is untouched. */
    RecordRef_PoseFree(&loaded);
  }

  /* The strings were copied into the arena, so the file buffer goes either way. */
  tb_free_bytes(bytes);

  return ok;
}

void RecordRef_PoseFree(RecordRef_PoseTable_t* table) {
  tb_arena_free(&table->arena);

  memset(table, 0, sizeof *table);
}

const RecordRef_PoseRecord_t* RecordRef_PoseFindByIndex(
  const RecordRef_PoseTable_t* table, int32_t key) {
  int32_t position = tb_index_find(table->by_index, table->count, key);

  return position < 0 ? NULL : &table->records[position];
}

bool RecordRef_PoseContainsIndex(
  const RecordRef_PoseTable_t* table, int32_t key) {
  return tb_index_find(table->by_index, table->count, key) >= 0;
}
