// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package tabbit.fixtures.declared;

/** One thing a row hands out. */
public final class Reward {
    /** Which item, as that table's key. */
    public int itemId;
    /** How many of it. */
    public int count;
    /** Shown beside the count. Blank where there is nothing to show. */
    public String icon = "";
}
