-- ------------------------------------------------------------------------------
-- Generated by Tabbit. DO NOT EDIT.
--
-- Changes to this file may cause incorrect behavior and will be lost if the code is
-- regenerated.
-- ------------------------------------------------------------------------------

local _root = (...):match("^(.-)[^%.]+%.[^%.]+$")
local tcb = require(_root .. "tabbit.tcb_reader")
local Rarity = require(_root .. "enums.enum_rarity")

-- Generated from test/fixtures/xlsx/optional/optional.xlsx : Optional : F2.
-- Optional columns, each beside the same type left required.
---@class DropRecord
---@field index integer
---@field hp integer
---@field bonus integer
---@field hasBonus boolean
---@field weight number
---@field hasWeight boolean
---@field ratio number
---@field hasRatio boolean
---@field count integer
---@field hasCount boolean
---@field openAt integer
---@field hasOpenAt boolean
---@field cooldown integer
---@field hasCooldown boolean
---@field batch string
---@field hasBatch boolean
---@field grade integer
---@field hasGrade boolean
---@field costs integer[]
---@field hasCosts boolean
---@field label string
---@field hasLabel boolean
---@field hidden boolean
---@field hasHidden boolean
local DropRecordMeta = tcb.strictType("a `Drop` row", { "index", "hp", "bonus", "hasBonus", "weight", "hasWeight", "ratio", "hasRatio", "count", "hasCount", "openAt", "hasOpenAt", "cooldown", "hasCooldown", "batch", "hasBatch", "grade", "hasGrade", "costs", "hasCosts", "label", "hasLabel", "hidden", "hasHidden" })

---@return DropRecord
local function newDropRecord()
  return setmetatable({
    index = 0,
    hp = 0,
    bonus = 0,
    hasBonus = false,
    weight = 0.0,
    hasWeight = false,
    ratio = 0.0,
    hasRatio = false,
    count = 0,
    hasCount = false,
    openAt = 0,
    hasOpenAt = false,
    cooldown = 0,
    hasCooldown = false,
    batch = tcb.UUID_EMPTY,
    hasBatch = false,
    grade = 0,
    hasGrade = false,
    costs = {},
    hasCosts = false,
    label = "",
    hasLabel = false,
    hidden = false,
    hasHidden = false,
  }, DropRecordMeta)
end

---@class DropTable
---@field records DropRecord[]
local DropTable = {}

local DropTableMeta = tcb.strictInstance("the `Drop` table", DropTable, { "records", "byIndex" })

function DropTable.new()
  return setmetatable({
    records = {},
    byIndex = {},
  }, DropTableMeta)
end

-- The row with this Index, or nil when the table has none: the lookup to
-- reach for when a missing row is an ordinary answer.
function DropTable:findByIndex(key)
  return self.byIndex[key]
end

-- The row with this Index, or a raised error naming what was missing -
-- for a key that has to be there.
function DropTable:getByIndexOrThrow(key)
  local record = self:findByIndex(key)

  if record == nil then
    tcb.fail("there is no record in table `Drop` that corresponds to " ..
      "field `Index` value %s", tostring(key))
  end

  return record
end

-- Whether the table holds a row with this Index.
function DropTable:containsIndex(key)
  return self:findByIndex(key) ~= nil
end

-- Loads the table from the bytes of a .tcb file written by Tabbit. Column by column,
-- matched by tag rather than position: a column this build does not know is skipped by
-- its block length, and one whose type changed incompatibly fails naming the field.
function DropTable:readBytes(data)
  -- Required here rather than at the top: the accessor requires this module, so at load
  -- time it is half built and at call time it is not.
  local accessor = require(_root .. "tables")

  -- Opened unconditionally, with whatever keys the accessor holds - nil unless the
  -- project set them. A file that is neither encrypted nor signed comes back untouched,
  -- so the load path is the same either way. spec/tcb-mac-and-signature.md.
  local reader = tcb.newReader(tcb.open(
    data, accessor.encryptionKey, accessor.macKey, accessor.verifyMac))
  local count, columns = tcb.readTableHeader(reader)

  -- Read into storage of its own and published at the end: reading a table that is
  -- already loaded is a refresh, and one that turns out to be unreadable has to leave
  -- the rows already there alone.
  local records = {}

  for i = 1, count do
    records[i] = newDropRecord()
  end

  for c = 1, #columns do
    local column = columns[c]
    local blockEnd = reader.position + column.byteLength

    if column.tag == 1 then
      tcb.checkColumn(column, "Drop.Index", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Drop.Index")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].index = value
        end

        at = at + n
      end
    elseif column.tag == 2 then
      tcb.checkColumn(column, "Drop.Hp", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Drop.Hp")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].hp = value
        end

        at = at + n
      end
    elseif column.tag == 3 then
      tcb.checkColumn(column, "Drop.Bonus", tcb.KIND_SCALAR, true, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Bonus")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].bonus = value
        end

        at = at + n
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasBonus = tcb.isPresent(presence, i - 1)

        if not record.hasBonus then
          record.bonus = 0
        end
      end
    elseif column.tag == 4 then
      tcb.checkColumn(column, "Drop.Weight", tcb.KIND_SCALAR, true, { tcb.ELEMENT_F64, tcb.ELEMENT_F32, tcb.ELEMENT_I32 })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Weight")
      for i = 1, count do
        local record = records[i]
        record.weight = cursor:nextF64()
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasWeight = tcb.isPresent(presence, i - 1)

        if not record.hasWeight then
          record.weight = 0.0
        end
      end
    elseif column.tag == 5 then
      tcb.checkColumn(column, "Drop.Ratio", tcb.KIND_SCALAR, true, { tcb.ELEMENT_F32 })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Ratio")
      for i = 1, count do
        local record = records[i]
        record.ratio = cursor:nextF32()
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasRatio = tcb.isPresent(presence, i - 1)

        if not record.hasRatio then
          record.ratio = 0.0
        end
      end
    elseif column.tag == 6 then
      tcb.checkColumn(column, "Drop.Count", tcb.KIND_SCALAR, true, { tcb.ELEMENT_I64, tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Count")
      for i = 1, count do
        local record = records[i]
        record.count = cursor:nextI64()
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasCount = tcb.isPresent(presence, i - 1)

        if not record.hasCount then
          record.count = 0
        end
      end
    elseif column.tag == 7 then
      tcb.checkColumn(column, "Drop.OpenAt", tcb.KIND_SCALAR, true, { tcb.ELEMENT_I64 })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.OpenAt")
      for i = 1, count do
        local record = records[i]
        record.openAt = cursor:nextI64()
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasOpenAt = tcb.isPresent(presence, i - 1)

        if not record.hasOpenAt then
          record.openAt = 0
        end
      end
    elseif column.tag == 8 then
      tcb.checkColumn(column, "Drop.Cooldown", tcb.KIND_SCALAR, true, { tcb.ELEMENT_I64 })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Cooldown")
      for i = 1, count do
        local record = records[i]
        record.cooldown = cursor:nextI64()
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasCooldown = tcb.isPresent(presence, i - 1)

        if not record.hasCooldown then
          record.cooldown = 0
        end
      end
    elseif column.tag == 9 then
      tcb.checkColumn(column, "Drop.Batch", tcb.KIND_SCALAR, true, { tcb.ELEMENT_UUID })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      for i = 1, count do
        local record = records[i]
        record.batch = reader:readUuid()
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasBatch = tcb.isPresent(presence, i - 1)

        if not record.hasBatch then
          record.batch = tcb.UUID_EMPTY
        end
      end
    elseif column.tag == 10 then
      tcb.checkColumn(column, "Drop.Grade", tcb.KIND_SCALAR, true, { tcb.ELEMENT_VARINT })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Grade")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].grade = value
        end

        at = at + n
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasGrade = tcb.isPresent(presence, i - 1)

        if not record.hasGrade then
          record.grade = 0
        end
      end
    elseif column.tag == 11 then
      tcb.checkColumn(column, "Drop.Costs", tcb.KIND_ARRAY, true, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Costs")
      for i = 1, count do
        local record = records[i]
        local elementCount = cursor:nextLength()
        local values = {}

        for element = 1, elementCount do
          values[element] = cursor:nextI32()
        end

        record.costs = values
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasCosts = tcb.isPresent(presence, i - 1)

        if not record.hasCosts then
          record.costs = {}
        end
      end
    elseif column.tag == 12 then
      tcb.checkColumn(column, "Drop.Label", tcb.KIND_SCALAR, true, { tcb.ELEMENT_STRING })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Label")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameString(count - at)

        for i = at + 1, at + n do
          records[i].label = value
        end

        at = at + n
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasLabel = tcb.isPresent(presence, i - 1)

        if not record.hasLabel then
          record.label = ""
        end
      end
    elseif column.tag == 13 then
      tcb.checkColumn(column, "Drop.Hidden", tcb.KIND_SCALAR, true, { tcb.ELEMENT_BOOL })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Drop.Hidden")
      for i = 1, count do
        local record = records[i]
        record.hidden = cursor:nextBool()
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasHidden = tcb.isPresent(presence, i - 1)

        if not record.hasHidden then
          record.hidden = false
        end
      end
    else
      -- A column added after this code was generated.
      reader:skip(column.byteLength)
    end

    tcb.checkBlockEnd(reader, column, blockEnd)
  end

  local byIndex = {}

  for i = 1, #records do
    byIndex[records[i].index] = records[i]
  end

  -- Published, now that every column read.
  self.records = records
  self.byIndex = byIndex
end

-- The same load from a file on disk.
function DropTable:read(filename)
  self:readBytes(tcb.readAllBytes(filename))
end

return DropTable
