-- ------------------------------------------------------------------------------
-- Generated by Tabbit. DO NOT EDIT.
--
-- Changes to this file may cause incorrect behavior and will be lost if the code is
-- regenerated.
-- ------------------------------------------------------------------------------

local _root = (...):match("^(.-)[^%.]+%.[^%.]+$")
local tcb = require(_root .. "tabbit.tcb_reader")

-- Generated from test/fixtures/xlsx/matrix/matrix.xlsx : Grids : B2.
-- Price modifier by town and goods.
---@class TownPriceColumnRecord
---@field goods integer
---@field goodsByGoods GoodsRecord|nil
---@field at integer
local TownPriceColumnRecordMeta = tcb.strictType("a `TownPriceColumn` row", { "goods", "goodsByGoods", "at" })

---@return TownPriceColumnRecord
local function newTownPriceColumnRecord()
  return setmetatable({
    goods = 0,
    at = 0,
  }, TownPriceColumnRecordMeta)
end

---@class TownPriceColumnTable
---@field records TownPriceColumnRecord[]
local TownPriceColumnTable = {}

local TownPriceColumnTableMeta = tcb.strictInstance("the `TownPriceColumn` table", TownPriceColumnTable, { "records", "byGoods" })

function TownPriceColumnTable.new()
  return setmetatable({
    records = {},
    byGoods = {},
  }, TownPriceColumnTableMeta)
end

-- How many rows the table holds.
--
-- A method rather than `#table`: LuaJIT 2.1 does not call `__len` on a table, so the
-- operator would answer on 5.3+ and not on the other runtime this output has to run on.
function TownPriceColumnTable:count()
  return #self.records
end

-- The rows, in the order the file wrote them - `for row in table:iter() do`.
--
-- The list is read once, here. A refresh replaces it rather than its contents, so a loop
-- already running keeps the rows it started with.
function TownPriceColumnTable:iter()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    return records[i]
  end
end

-- The row with this Goods, or nil when the table has none: the lookup to
-- reach for when a missing row is an ordinary answer.
function TownPriceColumnTable:findByGoods(key)
  return self.byGoods[key]
end

-- The row with this Goods, or a raised error naming what was missing -
-- for a key that has to be there.
function TownPriceColumnTable:getByGoodsOrThrow(key)
  local record = self:findByGoods(key)

  if record == nil then
    tcb.fail("there is no record in table `TownPriceColumn` that corresponds to " ..
      "field `Goods` value %s", tostring(key))
  end

  return record
end

-- Whether the table holds a row with this Goods.
function TownPriceColumnTable:containsGoods(key)
  return self:findByGoods(key) ~= nil
end


-- Each row with the Goods it is keyed by -
-- `for key, row in table:entries() do`.
--
-- What this saves a caller is not the key value - the row carries it - but having to know
-- which column the key is: Goods here, something else in the next table.
--
-- The rows come in the order the file wrote them rather than the order the map holds them,
-- which makes this and `iter` agree. Only the primary key has this: a table keyed by
-- several columns together has no single key value to pair a row with.
function TownPriceColumnTable:entries()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    local record = records[i]

    if record == nil then
      return nil
    end

    return record.goods, record
  end
end


-- Loads the table from the bytes of a .tcb file written by Tabbit. Column by column,
-- matched by tag rather than position: a column this build does not know is skipped by
-- its block length, and one whose type changed incompatibly fails naming the field.
function TownPriceColumnTable:readBytes(data)
  -- Required here rather than at the top: the accessor requires this module, so at load
  -- time it is half built and at call time it is not.
  local accessor = require(_root .. "tables")

  -- Opened unconditionally, with whatever keys the accessor holds - nil unless the
  -- project set them. A file that is neither encrypted nor signed comes back untouched,
  -- so the load path is the same either way. spec/wire/tcb-mac-and-signature.md.
  local reader = tcb.newReader(tcb.open(
    data, accessor.encryptionKey, accessor.macKey, accessor.verifyMac))
  local count, columns = tcb.readTableHeader(reader)

  -- Read into storage of its own and published at the end: reading a table that is
  -- already loaded is a refresh, and one that turns out to be unreadable has to leave
  -- the rows already there alone.
  local records = {}

  for i = 1, count do
    records[i] = newTownPriceColumnRecord()
  end

  for c = 1, #columns do
    local column = columns[c]
    local blockEnd = reader.position + column.byteLength

    if column.tag == 1 then
      tcb.checkColumn(column, "TownPriceColumn.Goods", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32 })
      local cursor = tcb.newCursor(reader, column, count, "TownPriceColumn.Goods")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].goods = value
        end

        at = at + n
      end
    elseif column.tag == 2 then
      tcb.checkColumn(column, "TownPriceColumn.At", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "TownPriceColumn.At")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].at = value
        end

        at = at + n
      end
    else
      -- A column added after this code was generated.
      reader:skip(column.byteLength)
    end

    tcb.checkBlockEnd(reader, column, blockEnd)
  end

  local byGoods = {}

  for i = 1, #records do
    byGoods[records[i].goods] = records[i]
  end

  -- Published, now that every column read.
  self.records = records
  self.byGoods = byGoods
end

-- The same load from a file on disk.
function TownPriceColumnTable:read(filename)
  self:readBytes(tcb.readAllBytes(filename))
end

return TownPriceColumnTable
