// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------


// Tables
export { PieceRecord } from './tables/piece'
export { PieceTable } from './tables/piece'
export { KitRecord } from './tables/kit'
export { KitTable } from './tables/kit'
export { BitRecord } from './tables/bit'
export { BitTable } from './tables/bit'
export { TrimKitRecord } from './tables/trim-kit'
export { TrimKitTable } from './tables/trim-kit'

export { Tables } from './tables'
