// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

// Generated from test/fixtures/xlsx/optional/optional.xlsx : Optional : B2
/** Rarity of a drop. */
export enum Rarity {
  /** no value */
  None = 0,
  /** common */
  Common = 1,
  /** rare */
  Rare = 2
}
