# ------------------------------------------------------------------------------
# Generated by Tabbit. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------


module DocShowcase
  # Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Basics : G2
  # What a potion is made of.
  module Element
    # no element
    NONE = 0
    # burns
    FIRE_BALL = 1
    # chills
    ICE_SHARD = 2

    # Every declared label, by value.
    NAMES = {
      0 => :none,
      1 => :fire_ball,
      2 => :ice_shard,
    }.freeze

    # The label's name, or nil when the sheet declared no such value.
    def self.name_of(value)
      NAMES[value]
    end
  end
end
