// ------------------------------------------------------------------------------
// <auto-generated>
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections.Generic;
using System.Threading.Tasks;

// Tabbit's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using Tabbit.Binary;

namespace Tabbit.Fixtures.Declared
{
    /// <summary>
    /// One thing a row hands out.
    /// </summary>
    [System.Serializable]
    public struct Reward
    {
        /// Which item, as that table's key.
        public int ItemId;
        /// How many of it.
        public int Count;
        /// Shown beside the count. Blank where there is nothing to show.
        public string Icon;

        public override string ToString()
        {
            var sb = new StringBuilder("{");
            sb.Append("\"ItemId\":"); ToStringHelper.ToString(ItemId, sb);
            sb.Append(",\"Count\":"); ToStringHelper.ToString(Count, sb);
            sb.Append(",\"Icon\":"); ToStringHelper.ToString(Icon, sb);
            sb.Append("}");
            return sb.ToString();
        }
    }
} // namespace Tabbit.Fixtures.Declared
