// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

#include "FSerialRefData.h"

#include "Misc/FileHelper.h"
#include "Misc/Paths.h"


const FPieceRow* FPieceTable::FindByIndex(int32 Key) const
{
    const int32* Position = ByIndex.Find(Key);
    return Position != nullptr ? &RecordsStorage[*Position] : nullptr;
}

bool FPieceTable::ContainsIndex(int32 Key) const
{
    return ByIndex.Contains(Key);
}

bool FPieceTable::Read(const FString& Filename)
{
    TArray<uint8> Buffer;

    // FFileHelper rather than the platform's own file API, and that is what makes this work
    // in a packaged build: it goes through IPlatformFile, which mounts the .pak and reads
    // out of it as though the file were loose on disk. The same call therefore works in the
    // editor, in a cooked build, and inside an Android .obb.
    //
    // What it cannot do is find a file the packaging step never took. A .tcb is not an
    // asset, so Unreal ignores it unless the project lists its directory under
    // Project Settings -> Packaging -> "Additional Non-Asset Directories to Package".
    // Miss that and this works in the editor and reports a missing file the moment anybody
    // runs the build - which is the failure this message exists to name.
    if (!FFileHelper::LoadFileToArray(Buffer, *Filename))
    {
        UE_LOG(LogTemp, Error,
            TEXT("Tabbit: could not read %s. In a packaged build, check that its directory is "
                 "listed under Packaging -> Additional Non-Asset Directories to Package."),
            *Filename);

        return false;
    }

    // Opened unconditionally, with whatever FSerialRefData::EncryptionKey and
    // FSerialRefData::MacKey hold - empty unless the project set them. A file that is
    // neither encrypted nor signed comes back from this untouched, so the load path is the
    // same either way and there is no condition here that could be the wrong way round.
    // spec/tcb-mac-and-signature.md.
    //
    // A view over Buffer rather than a copy of it: decryption happens in place, so Buffer is
    // what has to stay alive for as long as the reader below is used.
    TArrayView<const uint8> Bytes;
    FString OpenError;

    if (!Tabbit::Open(Buffer, FSerialRefData::EncryptionKey, Bytes, OpenError,
            FSerialRefData::MacKey, FSerialRefData::bVerifyMac))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s could not be opened. %s"),
            *Filename, *OpenError);

        return false;
    }

    // A view over the bytes already in memory, so the file is read once and not copied
    // a second time - a localization table is megabytes.
    Tabbit::FTabbitBinaryReader Reader(Bytes);

    Tabbit::FTabbitTableHeader Header;
    if (!Tabbit::ReadTableHeader(Reader, Header))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is not a table this build can read. %s"),
            *Filename, *Reader.GetError());

        return false;
    }

    // Read beside whatever this table is already holding and swapped in at the end. Reading
    // again is a refresh - a patched .pak, a downloaded table - and one that turns out to be
    // unreadable has to leave the rows already there, which Blueprint graphs and gameplay
    // code are holding by value and by pointer.
    //
    // The header has already checked the row count against what the columns declare, so this
    // allocation is the size the file can actually hold rows for.
    TArray<FPieceRow> Loaded;

    Loaded.Empty(Header.RowCount);
    Loaded.SetNum(Header.RowCount);

    // One cursor for the whole read: the switch's cases share a scope, and C++ does
    // not allow a jump past a live constructor, so each encodable column opens this
    // one rather than declaring its own.
    Tabbit::FTabbitColumnCursor Cursor;

    // Column by column, matched by tag rather than by position: a column this build has no
    // member for is skipped by its declared length, and one whose type no longer fits the
    // member stops the read naming the field. Rows arrive default constructed, so a member
    // the file carries nothing for keeps its default.
    for (const Tabbit::FTabbitColumn& Column : Header.Columns)
    {
        const int32 BlockEnd = Reader.Tell() + Column.ByteLength;

        switch (Column.Tag)
        {
        case 1:
            Tabbit::CheckColumn(Reader, Column, TEXT("Piece.Index"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementI32) | Tabbit::ElementMask(Tabbit::ElementVarint));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Piece.Index"));

            {
                int32 RunValue = 0;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameI32(Header.RowCount - Row, RunLength, RunValue))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Index = RunValue;
                    }
                }
            }

            break;

        case 2:
            Tabbit::CheckColumn(Reader, Column, TEXT("Piece.Name"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementString));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Piece.Name"));

            {
                FString RunText;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameString(Header.RowCount - Row, RunLength, RunText))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Name = RunText;
                    }
                }
            }

            break;

        case 3:
            Tabbit::CheckColumn(Reader, Column, TEXT("Piece.Tier"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementI32) | Tabbit::ElementMask(Tabbit::ElementVarint));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Piece.Tier"));

            {
                int32 RunValue = 0;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameI32(Header.RowCount - Row, RunLength, RunValue))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Tier = RunValue;
                    }
                }
            }

            break;

        default:
            // A column this build has no member for: added to the schema after the code
            // was generated, or removed from the code while the data still carries it.
            Reader.Skip(Column.ByteLength);
            break;
        }

        Tabbit::CheckBlockEnd(Reader, Column, BlockEnd);
    }

    // Asked once, for the whole table. Anything short or malformed anywhere in it has
    // left its reason here, and a half-read table is not one this returns true for - nor
    // is it one that replaces what the table was holding.
    if (Reader.HasFailed())
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is malformed. %s"), *Filename, *Reader.GetError());

        return false;
    }

    TMap<int32, int32> LoadedByIndex;
    LoadedByIndex.Empty(Loaded.Num());

    for (int32 Position = 0; Position < Loaded.Num(); ++Position)
    {
        LoadedByIndex.Add(Loaded[Position].Index, Position);
    }

    // Published together: rows holding this load and an index built from the last one would
    // answer a lookup with a row that has moved.
    RecordsStorage = MoveTemp(Loaded);
    ByIndex = MoveTemp(LoadedByIndex);

    return true;
}


const FKitRow* FKitTable::FindByIndex(int32 Key) const
{
    const int32* Position = ByIndex.Find(Key);
    return Position != nullptr ? &RecordsStorage[*Position] : nullptr;
}

bool FKitTable::ContainsIndex(int32 Key) const
{
    return ByIndex.Contains(Key);
}

bool FKitTable::Read(const FString& Filename)
{
    TArray<uint8> Buffer;

    // FFileHelper rather than the platform's own file API, and that is what makes this work
    // in a packaged build: it goes through IPlatformFile, which mounts the .pak and reads
    // out of it as though the file were loose on disk. The same call therefore works in the
    // editor, in a cooked build, and inside an Android .obb.
    //
    // What it cannot do is find a file the packaging step never took. A .tcb is not an
    // asset, so Unreal ignores it unless the project lists its directory under
    // Project Settings -> Packaging -> "Additional Non-Asset Directories to Package".
    // Miss that and this works in the editor and reports a missing file the moment anybody
    // runs the build - which is the failure this message exists to name.
    if (!FFileHelper::LoadFileToArray(Buffer, *Filename))
    {
        UE_LOG(LogTemp, Error,
            TEXT("Tabbit: could not read %s. In a packaged build, check that its directory is "
                 "listed under Packaging -> Additional Non-Asset Directories to Package."),
            *Filename);

        return false;
    }

    // Opened unconditionally, with whatever FSerialRefData::EncryptionKey and
    // FSerialRefData::MacKey hold - empty unless the project set them. A file that is
    // neither encrypted nor signed comes back from this untouched, so the load path is the
    // same either way and there is no condition here that could be the wrong way round.
    // spec/tcb-mac-and-signature.md.
    //
    // A view over Buffer rather than a copy of it: decryption happens in place, so Buffer is
    // what has to stay alive for as long as the reader below is used.
    TArrayView<const uint8> Bytes;
    FString OpenError;

    if (!Tabbit::Open(Buffer, FSerialRefData::EncryptionKey, Bytes, OpenError,
            FSerialRefData::MacKey, FSerialRefData::bVerifyMac))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s could not be opened. %s"),
            *Filename, *OpenError);

        return false;
    }

    // A view over the bytes already in memory, so the file is read once and not copied
    // a second time - a localization table is megabytes.
    Tabbit::FTabbitBinaryReader Reader(Bytes);

    Tabbit::FTabbitTableHeader Header;
    if (!Tabbit::ReadTableHeader(Reader, Header))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is not a table this build can read. %s"),
            *Filename, *Reader.GetError());

        return false;
    }

    // Read beside whatever this table is already holding and swapped in at the end. Reading
    // again is a refresh - a patched .pak, a downloaded table - and one that turns out to be
    // unreadable has to leave the rows already there, which Blueprint graphs and gameplay
    // code are holding by value and by pointer.
    //
    // The header has already checked the row count against what the columns declare, so this
    // allocation is the size the file can actually hold rows for.
    TArray<FKitRow> Loaded;

    Loaded.Empty(Header.RowCount);
    Loaded.SetNum(Header.RowCount);

    // One cursor for the whole read: the switch's cases share a scope, and C++ does
    // not allow a jump past a live constructor, so each encodable column opens this
    // one rather than declaring its own.
    Tabbit::FTabbitColumnCursor Cursor;

    // Column by column, matched by tag rather than by position: a column this build has no
    // member for is skipped by its declared length, and one whose type no longer fits the
    // member stops the read naming the field. Rows arrive default constructed, so a member
    // the file carries nothing for keeps its default.
    for (const Tabbit::FTabbitColumn& Column : Header.Columns)
    {
        const int32 BlockEnd = Reader.Tell() + Column.ByteLength;

        switch (Column.Tag)
        {
        case 1:
            Tabbit::CheckColumn(Reader, Column, TEXT("Kit.Index"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementI32) | Tabbit::ElementMask(Tabbit::ElementVarint));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Kit.Index"));

            {
                int32 RunValue = 0;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameI32(Header.RowCount - Row, RunLength, RunValue))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Index = RunValue;
                    }
                }
            }

            break;

        case 2:
            Tabbit::CheckColumn(Reader, Column, TEXT("Kit.Slot"), Tabbit::KindArray, false, Tabbit::ElementMask(Tabbit::ElementI32));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Kit.Slot"));

            for (FKitRow& Record : Loaded)
            {
                int32 ElementCount = 0;
                Cursor.NextLength(ElementCount);

                Record.Slot.Empty(Tabbit::ReserveBound(ElementCount));

                while (Record.Slot.Num() < ElementCount && !Reader.HasFailed())
                {
                    Cursor.NextAs(Column.Element, Record.Slot.AddDefaulted_GetRef());
                }
            }

            break;

        case 3:
            Tabbit::CheckColumn(Reader, Column, TEXT("Kit.Tier"), Tabbit::KindArray, false, Tabbit::ElementMask(Tabbit::ElementI32));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Kit.Tier"));

            for (FKitRow& Record : Loaded)
            {
                int32 ElementCount = 0;
                Cursor.NextLength(ElementCount);

                Record.Tier.Empty(Tabbit::ReserveBound(ElementCount));

                while (Record.Tier.Num() < ElementCount && !Reader.HasFailed())
                {
                    Cursor.NextAs(Column.Element, Record.Tier.AddDefaulted_GetRef());
                }
            }

            break;

        default:
            // A column this build has no member for: added to the schema after the code
            // was generated, or removed from the code while the data still carries it.
            Reader.Skip(Column.ByteLength);
            break;
        }

        Tabbit::CheckBlockEnd(Reader, Column, BlockEnd);
    }

    // Asked once, for the whole table. Anything short or malformed anywhere in it has
    // left its reason here, and a half-read table is not one this returns true for - nor
    // is it one that replaces what the table was holding.
    if (Reader.HasFailed())
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is malformed. %s"), *Filename, *Reader.GetError());

        return false;
    }

    TMap<int32, int32> LoadedByIndex;
    LoadedByIndex.Empty(Loaded.Num());

    for (int32 Position = 0; Position < Loaded.Num(); ++Position)
    {
        LoadedByIndex.Add(Loaded[Position].Index, Position);
    }

    // Published together: rows holding this load and an index built from the last one would
    // answer a lookup with a row that has moved.
    RecordsStorage = MoveTemp(Loaded);
    ByIndex = MoveTemp(LoadedByIndex);

    return true;
}


const FBitRow* FBitTable::FindByIndex(int32 Key) const
{
    const int32* Position = ByIndex.Find(Key);
    return Position != nullptr ? &RecordsStorage[*Position] : nullptr;
}

bool FBitTable::ContainsIndex(int32 Key) const
{
    return ByIndex.Contains(Key);
}

bool FBitTable::Read(const FString& Filename)
{
    TArray<uint8> Buffer;

    // FFileHelper rather than the platform's own file API, and that is what makes this work
    // in a packaged build: it goes through IPlatformFile, which mounts the .pak and reads
    // out of it as though the file were loose on disk. The same call therefore works in the
    // editor, in a cooked build, and inside an Android .obb.
    //
    // What it cannot do is find a file the packaging step never took. A .tcb is not an
    // asset, so Unreal ignores it unless the project lists its directory under
    // Project Settings -> Packaging -> "Additional Non-Asset Directories to Package".
    // Miss that and this works in the editor and reports a missing file the moment anybody
    // runs the build - which is the failure this message exists to name.
    if (!FFileHelper::LoadFileToArray(Buffer, *Filename))
    {
        UE_LOG(LogTemp, Error,
            TEXT("Tabbit: could not read %s. In a packaged build, check that its directory is "
                 "listed under Packaging -> Additional Non-Asset Directories to Package."),
            *Filename);

        return false;
    }

    // Opened unconditionally, with whatever FSerialRefData::EncryptionKey and
    // FSerialRefData::MacKey hold - empty unless the project set them. A file that is
    // neither encrypted nor signed comes back from this untouched, so the load path is the
    // same either way and there is no condition here that could be the wrong way round.
    // spec/tcb-mac-and-signature.md.
    //
    // A view over Buffer rather than a copy of it: decryption happens in place, so Buffer is
    // what has to stay alive for as long as the reader below is used.
    TArrayView<const uint8> Bytes;
    FString OpenError;

    if (!Tabbit::Open(Buffer, FSerialRefData::EncryptionKey, Bytes, OpenError,
            FSerialRefData::MacKey, FSerialRefData::bVerifyMac))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s could not be opened. %s"),
            *Filename, *OpenError);

        return false;
    }

    // A view over the bytes already in memory, so the file is read once and not copied
    // a second time - a localization table is megabytes.
    Tabbit::FTabbitBinaryReader Reader(Bytes);

    Tabbit::FTabbitTableHeader Header;
    if (!Tabbit::ReadTableHeader(Reader, Header))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is not a table this build can read. %s"),
            *Filename, *Reader.GetError());

        return false;
    }

    // Read beside whatever this table is already holding and swapped in at the end. Reading
    // again is a refresh - a patched .pak, a downloaded table - and one that turns out to be
    // unreadable has to leave the rows already there, which Blueprint graphs and gameplay
    // code are holding by value and by pointer.
    //
    // The header has already checked the row count against what the columns declare, so this
    // allocation is the size the file can actually hold rows for.
    TArray<FBitRow> Loaded;

    Loaded.Empty(Header.RowCount);
    Loaded.SetNum(Header.RowCount);

    // One cursor for the whole read: the switch's cases share a scope, and C++ does
    // not allow a jump past a live constructor, so each encodable column opens this
    // one rather than declaring its own.
    Tabbit::FTabbitColumnCursor Cursor;

    // Column by column, matched by tag rather than by position: a column this build has no
    // member for is skipped by its declared length, and one whose type no longer fits the
    // member stops the read naming the field. Rows arrive default constructed, so a member
    // the file carries nothing for keeps its default.
    for (const Tabbit::FTabbitColumn& Column : Header.Columns)
    {
        const int32 BlockEnd = Reader.Tell() + Column.ByteLength;

        switch (Column.Tag)
        {
        case 1:
            Tabbit::CheckColumn(Reader, Column, TEXT("Bit.Index"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementI32) | Tabbit::ElementMask(Tabbit::ElementVarint));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Bit.Index"));

            {
                int32 RunValue = 0;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameI32(Header.RowCount - Row, RunLength, RunValue))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Index = RunValue;
                    }
                }
            }

            break;

        case 2:
            Tabbit::CheckColumn(Reader, Column, TEXT("Bit.Name"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementString));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Bit.Name"));

            {
                FString RunText;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameString(Header.RowCount - Row, RunLength, RunText))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Name = RunText;
                    }
                }
            }

            break;

        case 3:
            Tabbit::CheckColumn(Reader, Column, TEXT("Bit.Tier"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementI32) | Tabbit::ElementMask(Tabbit::ElementVarint));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("Bit.Tier"));

            {
                int32 RunValue = 0;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameI32(Header.RowCount - Row, RunLength, RunValue))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Tier = RunValue;
                    }
                }
            }

            break;

        default:
            // A column this build has no member for: added to the schema after the code
            // was generated, or removed from the code while the data still carries it.
            Reader.Skip(Column.ByteLength);
            break;
        }

        Tabbit::CheckBlockEnd(Reader, Column, BlockEnd);
    }

    // Asked once, for the whole table. Anything short or malformed anywhere in it has
    // left its reason here, and a half-read table is not one this returns true for - nor
    // is it one that replaces what the table was holding.
    if (Reader.HasFailed())
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is malformed. %s"), *Filename, *Reader.GetError());

        return false;
    }

    TMap<int32, int32> LoadedByIndex;
    LoadedByIndex.Empty(Loaded.Num());

    for (int32 Position = 0; Position < Loaded.Num(); ++Position)
    {
        LoadedByIndex.Add(Loaded[Position].Index, Position);
    }

    // Published together: rows holding this load and an index built from the last one would
    // answer a lookup with a row that has moved.
    RecordsStorage = MoveTemp(Loaded);
    ByIndex = MoveTemp(LoadedByIndex);

    return true;
}


const FTrimKitRow* FTrimKitTable::FindByIndex(int32 Key) const
{
    const int32* Position = ByIndex.Find(Key);
    return Position != nullptr ? &RecordsStorage[*Position] : nullptr;
}

bool FTrimKitTable::ContainsIndex(int32 Key) const
{
    return ByIndex.Contains(Key);
}

bool FTrimKitTable::Read(const FString& Filename)
{
    TArray<uint8> Buffer;

    // FFileHelper rather than the platform's own file API, and that is what makes this work
    // in a packaged build: it goes through IPlatformFile, which mounts the .pak and reads
    // out of it as though the file were loose on disk. The same call therefore works in the
    // editor, in a cooked build, and inside an Android .obb.
    //
    // What it cannot do is find a file the packaging step never took. A .tcb is not an
    // asset, so Unreal ignores it unless the project lists its directory under
    // Project Settings -> Packaging -> "Additional Non-Asset Directories to Package".
    // Miss that and this works in the editor and reports a missing file the moment anybody
    // runs the build - which is the failure this message exists to name.
    if (!FFileHelper::LoadFileToArray(Buffer, *Filename))
    {
        UE_LOG(LogTemp, Error,
            TEXT("Tabbit: could not read %s. In a packaged build, check that its directory is "
                 "listed under Packaging -> Additional Non-Asset Directories to Package."),
            *Filename);

        return false;
    }

    // Opened unconditionally, with whatever FSerialRefData::EncryptionKey and
    // FSerialRefData::MacKey hold - empty unless the project set them. A file that is
    // neither encrypted nor signed comes back from this untouched, so the load path is the
    // same either way and there is no condition here that could be the wrong way round.
    // spec/tcb-mac-and-signature.md.
    //
    // A view over Buffer rather than a copy of it: decryption happens in place, so Buffer is
    // what has to stay alive for as long as the reader below is used.
    TArrayView<const uint8> Bytes;
    FString OpenError;

    if (!Tabbit::Open(Buffer, FSerialRefData::EncryptionKey, Bytes, OpenError,
            FSerialRefData::MacKey, FSerialRefData::bVerifyMac))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s could not be opened. %s"),
            *Filename, *OpenError);

        return false;
    }

    // A view over the bytes already in memory, so the file is read once and not copied
    // a second time - a localization table is megabytes.
    Tabbit::FTabbitBinaryReader Reader(Bytes);

    Tabbit::FTabbitTableHeader Header;
    if (!Tabbit::ReadTableHeader(Reader, Header))
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is not a table this build can read. %s"),
            *Filename, *Reader.GetError());

        return false;
    }

    // Read beside whatever this table is already holding and swapped in at the end. Reading
    // again is a refresh - a patched .pak, a downloaded table - and one that turns out to be
    // unreadable has to leave the rows already there, which Blueprint graphs and gameplay
    // code are holding by value and by pointer.
    //
    // The header has already checked the row count against what the columns declare, so this
    // allocation is the size the file can actually hold rows for.
    TArray<FTrimKitRow> Loaded;

    Loaded.Empty(Header.RowCount);
    Loaded.SetNum(Header.RowCount);

    // One cursor for the whole read: the switch's cases share a scope, and C++ does
    // not allow a jump past a live constructor, so each encodable column opens this
    // one rather than declaring its own.
    Tabbit::FTabbitColumnCursor Cursor;
    TArray<uint8> ElementPresence;
    int32 ElementAt = 0;

    // Column by column, matched by tag rather than by position: a column this build has no
    // member for is skipped by its declared length, and one whose type no longer fits the
    // member stops the read naming the field. Rows arrive default constructed, so a member
    // the file carries nothing for keeps its default.
    for (const Tabbit::FTabbitColumn& Column : Header.Columns)
    {
        const int32 BlockEnd = Reader.Tell() + Column.ByteLength;

        switch (Column.Tag)
        {
        case 1:
            Tabbit::CheckColumn(Reader, Column, TEXT("TrimKit.Index"), Tabbit::KindScalar, false, Tabbit::ElementMask(Tabbit::ElementI32) | Tabbit::ElementMask(Tabbit::ElementVarint));
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("TrimKit.Index"));

            {
                int32 RunValue = 0;
                int32 RunLength = 0;

                for (int32 Row = 0; Row < Header.RowCount; )
                {
                    if (!Cursor.NextSameI32(Header.RowCount - Row, RunLength, RunValue))
                    {
                        break;
                    }

                    for (; RunLength > 0; --RunLength, ++Row)
                    {
                        Loaded[Row].Index = RunValue;
                    }
                }
            }

            break;

        case 2:
            Tabbit::CheckColumn(Reader, Column, TEXT("TrimKit.Slot"), Tabbit::KindArray, false, Tabbit::ElementMask(Tabbit::ElementI32));
            // Behind the row bitmap and in front of the values, walked with a counter that
            // steps once per element of every row. spec/nullable-array-elements.md.
            Tabbit::ReadElementPresence(Reader, Column, ElementPresence);
            ElementAt = 0;
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("TrimKit.Slot"));

            for (FTrimKitRow& Record : Loaded)
            {
                int32 ElementCount = 0;
                Cursor.NextLength(ElementCount);

                Record.Slot.Empty(Tabbit::ReserveBound(ElementCount));

                while (Record.Slot.Num() < ElementCount && !Reader.HasFailed())
                {
                    Cursor.NextAs(Column.Element, Record.Slot.AddDefaulted_GetRef());
                }
                Record.bHasSlotAt.Empty(
                    Tabbit::ReserveBound(ElementCount));

                for (int32 ElementIndex = 0; ElementIndex < ElementCount; ++ElementIndex)
                {
                    Record.bHasSlotAt.Add(
                        Tabbit::IsPresent(ElementPresence, ElementAt + ElementIndex));
                }

                ElementAt += ElementCount;
            }

            break;

        case 3:
            Tabbit::CheckColumn(Reader, Column, TEXT("TrimKit.Tier"), Tabbit::KindArray, false, Tabbit::ElementMask(Tabbit::ElementI32));
            // Behind the row bitmap and in front of the values, walked with a counter that
            // steps once per element of every row. spec/nullable-array-elements.md.
            Tabbit::ReadElementPresence(Reader, Column, ElementPresence);
            ElementAt = 0;
            Cursor.Open(Reader, Column, Header.RowCount, TEXT("TrimKit.Tier"));

            for (FTrimKitRow& Record : Loaded)
            {
                int32 ElementCount = 0;
                Cursor.NextLength(ElementCount);

                Record.Tier.Empty(Tabbit::ReserveBound(ElementCount));

                while (Record.Tier.Num() < ElementCount && !Reader.HasFailed())
                {
                    Cursor.NextAs(Column.Element, Record.Tier.AddDefaulted_GetRef());
                }
                Record.bHasTierAt.Empty(
                    Tabbit::ReserveBound(ElementCount));

                for (int32 ElementIndex = 0; ElementIndex < ElementCount; ++ElementIndex)
                {
                    Record.bHasTierAt.Add(
                        Tabbit::IsPresent(ElementPresence, ElementAt + ElementIndex));
                }

                ElementAt += ElementCount;
            }

            break;

        default:
            // A column this build has no member for: added to the schema after the code
            // was generated, or removed from the code while the data still carries it.
            Reader.Skip(Column.ByteLength);
            break;
        }

        Tabbit::CheckBlockEnd(Reader, Column, BlockEnd);
    }

    // Asked once, for the whole table. Anything short or malformed anywhere in it has
    // left its reason here, and a half-read table is not one this returns true for - nor
    // is it one that replaces what the table was holding.
    if (Reader.HasFailed())
    {
        UE_LOG(LogTemp, Error, TEXT("Tabbit: %s is malformed. %s"), *Filename, *Reader.GetError());

        return false;
    }

    TMap<int32, int32> LoadedByIndex;
    LoadedByIndex.Empty(Loaded.Num());

    for (int32 Position = 0; Position < Loaded.Num(); ++Position)
    {
        LoadedByIndex.Add(Loaded[Position].Index, Position);
    }

    // Published together: rows holding this load and an index built from the last one would
    // answer a lookup with a row that has moved.
    RecordsStorage = MoveTemp(Loaded);
    ByIndex = MoveTemp(LoadedByIndex);

    return true;
}

FPieceTable FSerialRefData::PieceStorage;
FKitTable FSerialRefData::KitStorage;
FBitTable FSerialRefData::BitStorage;
FTrimKitTable FSerialRefData::TrimKitStorage;

TArray<uint8> FSerialRefData::EncryptionKey;
TArray<uint8> FSerialRefData::MacKey;
bool FSerialRefData::bVerifyMac = true;



FPieceRow USerialRefDataLibrary::GetPieceRow(int32 Key, bool& bFound)
{
    const FPieceRow* Found = FSerialRefData::Piece().FindByIndex(Key);

    bFound = Found != nullptr;

    // A copy, because Blueprint takes a struct by value and the row belongs to the table.
    // A default one when the key is not there, which is why bFound is not decoration.
    return Found != nullptr ? *Found : FPieceRow();
}

int32 USerialRefDataLibrary::GetPieceRowCount()
{
    return FSerialRefData::Piece().Records().Num();
}

FPieceRow USerialRefDataLibrary::GetPieceRowAt(int32 Position, bool& bFound)
{
    const TArray<FPieceRow>& Rows = FSerialRefData::Piece().Records();

    bFound = Rows.IsValidIndex(Position);

    return bFound ? Rows[Position] : FPieceRow();
}


FKitRow USerialRefDataLibrary::GetKitRow(int32 Key, bool& bFound)
{
    const FKitRow* Found = FSerialRefData::Kit().FindByIndex(Key);

    bFound = Found != nullptr;

    // A copy, because Blueprint takes a struct by value and the row belongs to the table.
    // A default one when the key is not there, which is why bFound is not decoration.
    return Found != nullptr ? *Found : FKitRow();
}

int32 USerialRefDataLibrary::GetKitRowCount()
{
    return FSerialRefData::Kit().Records().Num();
}

FKitRow USerialRefDataLibrary::GetKitRowAt(int32 Position, bool& bFound)
{
    const TArray<FKitRow>& Rows = FSerialRefData::Kit().Records();

    bFound = Rows.IsValidIndex(Position);

    return bFound ? Rows[Position] : FKitRow();
}


FBitRow USerialRefDataLibrary::GetBitRow(int32 Key, bool& bFound)
{
    const FBitRow* Found = FSerialRefData::Bit().FindByIndex(Key);

    bFound = Found != nullptr;

    // A copy, because Blueprint takes a struct by value and the row belongs to the table.
    // A default one when the key is not there, which is why bFound is not decoration.
    return Found != nullptr ? *Found : FBitRow();
}

int32 USerialRefDataLibrary::GetBitRowCount()
{
    return FSerialRefData::Bit().Records().Num();
}

FBitRow USerialRefDataLibrary::GetBitRowAt(int32 Position, bool& bFound)
{
    const TArray<FBitRow>& Rows = FSerialRefData::Bit().Records();

    bFound = Rows.IsValidIndex(Position);

    return bFound ? Rows[Position] : FBitRow();
}


FTrimKitRow USerialRefDataLibrary::GetTrimKitRow(int32 Key, bool& bFound)
{
    const FTrimKitRow* Found = FSerialRefData::TrimKit().FindByIndex(Key);

    bFound = Found != nullptr;

    // A copy, because Blueprint takes a struct by value and the row belongs to the table.
    // A default one when the key is not there, which is why bFound is not decoration.
    return Found != nullptr ? *Found : FTrimKitRow();
}

int32 USerialRefDataLibrary::GetTrimKitRowCount()
{
    return FSerialRefData::TrimKit().Records().Num();
}

FTrimKitRow USerialRefDataLibrary::GetTrimKitRowAt(int32 Position, bool& bFound)
{
    const TArray<FTrimKitRow>& Rows = FSerialRefData::TrimKit().Records();

    bFound = Rows.IsValidIndex(Position);

    return bFound ? Rows[Position] : FTrimKitRow();
}


bool USerialRefDataLibrary::ReadAll(const FString& BasePath, const FString& FileExtension)
{
    return FSerialRefData::ReadAll(BasePath, FileExtension);
}

bool FSerialRefData::ReadAll(const FString& BasePath, const FString& FileExtension)
{
    // Read into tables of their own and moved into place at the end. Reading again is a
    // refresh - a patched .pak, a downloaded table - and one that fails on the third file
    // must not leave the first two replaced and the rest as they were.
    FPieceTable LoadedPiece;

    if (!LoadedPiece.Read(FPaths::Combine(BasePath, TEXT("Piece") + FileExtension)))
    {
        return false;
    }
    FKitTable LoadedKit;

    if (!LoadedKit.Read(FPaths::Combine(BasePath, TEXT("Kit") + FileExtension)))
    {
        return false;
    }
    FBitTable LoadedBit;

    if (!LoadedBit.Read(FPaths::Combine(BasePath, TEXT("Bit") + FileExtension)))
    {
        return false;
    }
    FTrimKitTable LoadedTrimKit;

    if (!LoadedTrimKit.Read(FPaths::Combine(BasePath, TEXT("TrimKit") + FileExtension)))
    {
        return false;
    }

    PieceStorage = MoveTemp(LoadedPiece);
    KitStorage = MoveTemp(LoadedKit);
    BitStorage = MoveTemp(LoadedBit);
    TrimKitStorage = MoveTemp(LoadedTrimKit);

    return true;
}
