// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef TABBIT_GENERATED_COMPOSITEKEYACCESSOR_H
#define TABBIT_GENERATED_COMPOSITEKEYACCESSOR_H

#include <cstddef>
#include <string>

#include "enums/CompositeKeyAccessor_enum_slot.h"
#include "tables/CompositeKeyAccessor_loadout.h"
#include "tables/CompositeKeyAccessor_route.h"
#include "tables/CompositeKeyAccessor_grid.h"
/// Every table, loaded together so cross-table references can be resolved.
class CompositeKeyAccessor {
 public:
  const LoadoutTable& loadout() const { return loadout_; }
  const RouteTable& route() const { return route_; }
  const GridTable& grid() const { return grid_; }

  /// Reads every table from `base_path`, then links the references between them.
  ///
  /// Safe to call on a loaded accessor. Every file is read into a table of its own and the
  /// references are linked among those, so a read that throws part way through leaves every
  /// table holding the load it already had, and no row points at a row from it.
  void read_all(const std::string& base_path, const std::string& file_extension = ".tcb") {
    LoadoutTable loaded_loadout;
    loaded_loadout.read(base_path + "/Loadout" + file_extension);
    RouteTable loaded_route;
    loaded_route.read(base_path + "/Route" + file_extension);
    GridTable loaded_grid;
    loaded_grid.read(base_path + "/Grid" + file_extension);

    solve_cross_references(loaded_loadout, loaded_route, loaded_grid);

    loadout_ = std::move(loaded_loadout);
    route_ = std::move(loaded_route);
    grid_ = std::move(loaded_grid);
  }

 private:
  /// The tables arrive as arguments, which is how this links the load being read rather
  /// than the one already published.
  ///
  /// Every table is passed whether or not it takes part in a reference, so the call site
  /// is the same shape for every model. `[[maybe_unused]]` is what says so to the
  /// compiler: the gate builds with `-Wextra -Werror`, and a model where nothing
  /// references anything - which is most of them - otherwise fails to compile on the
  /// unused parameters.
  void solve_cross_references([[maybe_unused]] LoadoutTable& loaded_loadout, [[maybe_unused]] RouteTable& loaded_route, [[maybe_unused]] GridTable& loaded_grid) {
    // No table references another.
  }

  LoadoutTable loadout_;
  RouteTable route_;
  GridTable grid_;
};

#endif  // TABBIT_GENERATED_COMPOSITEKEYACCESSOR_H
