# ------------------------------------------------------------------------------
# Generated by Tabbit. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

require_relative '../tabbit/tcb_reader'

require_relative '../enums/holder_pick_target'

require_relative '../enums/holder_wide_target'

require_relative '../enums/holder_maybe_target'


module MultiTarget
  # Generated from test/fixtures/xlsx/multi-target/multi-target.xlsx : Holders : B2
  # One column per case the spec states.
  class HolderRecord
    attr_accessor :index, :pick, :wide, :only, :only_index, :maybe, :has_maybe, :pick_row, :pick_target, :wide_row, :wide_target, :maybe_row, :maybe_target

    def initialize
      @index = 0
      @pick = 0
      @wide = 0
      @only = nil
      @only_index = 0
      @maybe = 0
      @has_maybe = false
      @pick_row = nil
      @pick_target = HolderPickTarget::NONE
      @wide_row = nil
      @wide_target = HolderWideTarget::NONE
      @maybe_row = nil
      @maybe_target = HolderMaybeTarget::NONE
    end


    # The weapon row this column names, or nil when it names a row of one of the others.
    def weapon_by_pick
      return nil unless @pick_target == HolderPickTarget::WEAPON

      @pick_row
    end

    # The armour row this column names, or nil when it names a row of one of the others.
    def armour_by_pick
      return nil unless @pick_target == HolderPickTarget::ARMOUR

      @pick_row
    end


    # The weapon row this column names, or nil when it names a row of one of the others.
    def weapon_by_wide
      return nil unless @wide_target == HolderWideTarget::WEAPON

      @wide_row
    end

    # The armour row this column names, or nil when it names a row of one of the others.
    def armour_by_wide
      return nil unless @wide_target == HolderWideTarget::ARMOUR

      @wide_row
    end

    # The trinket row this column names, or nil when it names a row of one of the others.
    def trinket_by_wide
      return nil unless @wide_target == HolderWideTarget::TRINKET

      @wide_row
    end

    # The mount row this column names, or nil when it names a row of one of the others.
    def mount_by_wide
      return nil unless @wide_target == HolderWideTarget::MOUNT

      @wide_row
    end

    # The banner row this column names, or nil when it names a row of one of the others.
    def banner_by_wide
      return nil unless @wide_target == HolderWideTarget::BANNER

      @wide_row
    end


    # The weapon row this column names, or nil when it names a row of one of the others.
    def weapon_by_maybe
      return nil unless @maybe_target == HolderMaybeTarget::WEAPON

      @maybe_row
    end

    # The armour row this column names, or nil when it names a row of one of the others.
    def armour_by_maybe
      return nil unless @maybe_target == HolderMaybeTarget::ARMOUR

      @maybe_row
    end

  end

  # Every row of Holder.
  class HolderTable
    attr_accessor :records

    def initialize
      @records = []
      @by_index = {}
    end

    # The row with this Index, or nil when the table has none.
    #
    # The lookup to reach for when a missing row is an ordinary answer - an optional
    # reference, a key that came from user input.
    def find_by_index(key)
      @by_index[key]
    end

    # The row with this Index, or a raised error naming what was missing.
    #
    # For a key that has to be there - one from another table, or a constant. The name
    # says it raises, because a caller reading `get_by_index(key).name` at a
    # glance cannot otherwise tell whether the next line is a check or a rescue.
    def get_by_index_or_throw(key)
      record = @by_index[key]

      if record.nil?
        raise Tabbit::RecordNotFoundError,
              "there is no record in table `Holder` that corresponds to " \
              "field `Index` value #{key.inspect}"
      end

      record
    end

    # Whether the table holds a row with this Index.
    def contains_index?(key)
      @by_index.key?(key)
    end

    # Loads the table from a .tcb file written by Tabbit.
    # Column by column, matched by tag rather than position: a column this build does
    # not know is skipped by its block length, and one whose type changed incompatibly
    # fails naming the field.
    def read(filename)
      # Opened unconditionally, and with whatever Tables.encryption_key and Tables.mac_key
      # hold - which is nil unless the project set them. A file that is neither encrypted
      # nor signed comes back from this untouched, so the load path is the same either way
      # and there is no condition here that could be the wrong way round.
      # spec/tcb-mac-and-signature.md.
      reader = Tabbit::Reader.new(
        Tabbit.open(Tabbit.read_all_bytes(filename), Tables.encryption_key,
                      Tables.mac_key, verify_mac: Tables.verify_mac)
      )
      count, columns = Tabbit.read_table_header(reader)

      # Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
      records = Array.new(count) { HolderRecord.new }

      columns.each do |column|
        block_end = reader.position + column.byte_length

        case column.tag
        when 1
          Tabbit.check_column(column, 'Holder.Index', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Holder.Index')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].index = value
            end
            at += n
          end
        when 2
          Tabbit.check_column(column, 'Holder.Pick', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Holder.Pick')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].pick = value
            end
            at += n
          end
        when 3
          Tabbit.check_column(column, 'Holder.Wide', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Holder.Wide')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].wide = value
            end
            at += n
          end
        when 4
          Tabbit.check_column(column, 'Holder.Only', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Holder.Only')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].only_index = value
            end
            at += n
          end
        when 5
          Tabbit.check_column(column, 'Holder.Maybe', Tabbit::KIND_SCALAR, true, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          # The bitmap is at the front of the block, so it is read before the values. The
          # values are written for every row either way, which is what lets the read shapes
          # below stay as they are.
          presence = Tabbit.read_presence(reader, column, count)
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Holder.Maybe')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].maybe = value
            end
            at += n
          end

          # A pass of its own rather than a line inside each read shape, so the row index is
          # worked out once. The block carries a value for every row, so an absent one has
          # just been given whatever was there; putting the empty value back is what makes
          # this path agree with the JSON one.
          records.each_with_index do |record, row|
            record.has_maybe = Tabbit.present?(presence, row)
            record.maybe = 0 unless record.has_maybe
          end
        else
          # A column added after this code was generated.
          reader.skip(column.byte_length)
        end

        Tabbit.check_block_end(reader, column, block_end)
      end

      by_index = records.to_h { |record| [record.index, record] }

      # Published, now that every column read.
      @records = records
      @by_index = by_index
    end
  end
end
