// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as tabbit from '../tabbit/tcb-reader'

// The accessor, for the encryption key it holds. `tables` imports this module back, and
// that cycle is only ever read from inside a method - by which point both modules have
// finished evaluating - so neither one is half built when the binding is used.
import { Tables } from '../tables'

// Automatically import to handle external type references.
import { Slot } from '../enums/slot'

/** A type for handling rows when parsing .json. */
interface IDataRow {
  stage: number
  slot: Slot
  power: number
  label: string
}

// Generated from test/fixtures/xlsx/composite-key/composite-key.xlsx : Loadout : B2
/** One row per stage and slot; neither column is unique on its own. */
export class LoadoutRecord {
  /** Default constructor */
  constructor() {
  }

  /** which stage */
  public get stage(): number { return this._stage }

  /** which slot */
  public get slot(): Slot { return this._slot }

  /** anything */
  public get power(): number { return this._power }

  /** anything */
  public get label(): string { return this._label }

  public _stage: number = 0
  public _slot: Slot = 0 as Slot
  public _power: number = 0
  public _label: string = ''

  /** Populate field values. */
  public populateFieldValues(dataRow: IDataRow): void {
    this._stage = dataRow.stage
    this._slot = dataRow.slot
    this._power = dataRow.power
    this._label = dataRow.label
  }

  /** Populate field values. */
  public populateFieldValuesCompact(dataRow: any[]): void {
    let offset = 0
    this._stage = dataRow[offset++]
    this._slot = dataRow[offset++]
    this._power = dataRow[offset++]
    this._label = dataRow[offset++]
  }
}

// Generated from test/fixtures/xlsx/composite-key/composite-key.xlsx : Loadout : B2
/** One row per stage and slot; neither column is unique on its own. */
export class LoadoutTable {
  /** Default constructor. */
  constructor() {
  }

  /** All records. */
  public get records(): LoadoutRecord[] { return this._records }
  private _records: LoadoutRecord[] = []

  // Indexing by 'Stage and Slot'
  private _recordsByStageAndSlot: Map<string, LoadoutRecord> = new Map<string, LoadoutRecord>()

  /** Joins the columns of the Stage and Slot key into the text the map is keyed by. */
  private static keyOfStageAndSlot(stageKey: number, slotKey: Slot): string {
    const parts: string[] = [
      String(stageKey),
      String(slotKey),
    ]

    let text = ""

    for (const part of parts)
      text += `${part.length}:${part}`

    return text
  }

  /**
   * The row with this Stage and Slot, or undefined when the table has none.
   *
   * The lookup to reach for when a missing row is an ordinary answer.
   */
  public findByStageAndSlot(stageKey: number, slotKey: Slot): LoadoutRecord | undefined {
    return this._recordsByStageAndSlot.get(LoadoutTable.keyOfStageAndSlot(stageKey, slotKey))
  }

  /**
   * The row with this Stage and Slot, or a thrown Error naming what was missing.
   */
  public getByStageAndSlotOrThrow(stageKey: number, slotKey: Slot): LoadoutRecord {
    const found = this._recordsByStageAndSlot.get(LoadoutTable.keyOfStageAndSlot(stageKey, slotKey))
    if (!found)
      throw new Error(`There is no record in table "Loadout" that corresponds to field "Stage and Slot" value (${stageKey}, ${slotKey})`)

    return found
  }

  /** Whether the table holds a row with this Stage and Slot. */
  public containsStageAndSlot(stageKey: number, slotKey: Slot): boolean {
    return this._recordsByStageAndSlot.has(LoadoutTable.keyOfStageAndSlot(stageKey, slotKey))
  }

  /** Read a table from specified file. */
  public async read(filename: string): Promise<void> {
    const json = await fs.promises.readFile(filename, "utf8")
    this.readFromJson(json)
  }

  /** Read a table from specified file synchronously. */
  public readSync(filename: string): void {
    const json = fs.readFileSync(filename, "utf8")
    this.readFromJson(json)
  }

  private readFromJson(json: string): void {
    const dataRows: any[] = JSON.parse(json)
    const records: LoadoutRecord[] = []

    if (this.isCompactRowFormatted(dataRows)) {
      for (const dataRow of dataRows) {
        const record = new LoadoutRecord()
        record.populateFieldValuesCompact(dataRow)
        records.push(record)
      }
    } else {
      for (const dataRow of dataRows as IDataRow[]) {
        const record = new LoadoutRecord()
        record.populateFieldValues(dataRow)
        records.push(record)
      }
    }

    this.publish(records)
  }

  private isCompactRowFormatted(rows: any[]): boolean {
    return rows.length > 0 && Array.isArray(rows[0])
  }

  /** Read a table from a binary .tcb file. */
  public readBinarySync(filename: string): void {
    // Unconditionally, and with whatever `Tables.encryptionKey` and `Tables.macKey` hold -
    // which is null unless the project set them. A file that is neither encrypted nor signed
    // comes back from this untouched, so the load path is the same either way and there is
    // no condition here that could be the wrong way round. spec/tcb-mac-and-signature.md.
    this.readBinaryFrom(tabbit.open(
      tabbit.readAllBytes(filename),
      Tables.encryptionKey, Tables.macKey, Tables.verifyMac))
  }

  /**
   * Read a table from binary data already in memory.
   *
   * Column by column, matched by tag rather than position: a column this build does not
   * know is skipped by its block length, and one whose type changed incompatibly fails
   * naming the field.
   */
  public readBinaryFrom(data: Uint8Array): void {
    const reader = new tabbit.TcbReader(data)
    const { rowCount, columns } = tabbit.readTableHeader(reader)
    let cursor: tabbit.TcbColumnCursor

    // Built here and published at the end, so a file that turns out to be truncated - or
    // a column this build cannot read - leaves the rows already loaded exactly as they are.
    const records: LoadoutRecord[] = []
    for (let i = 0; i < rowCount; ++i)
      records.push(new LoadoutRecord())

    for (const column of columns) {
      const blockEnd = reader.position + column.byteLength

      switch (column.tag) {
        case 1:
          tabbit.checkColumn(column, 'Loadout.Stage', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_I32, tabbit.ELEMENT_VARINT])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Loadout.Stage')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameI32(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._stage = value
          }
          break
        case 2:
          tabbit.checkColumn(column, 'Loadout.Slot', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_VARINT])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Loadout.Slot')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameI32(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._slot = value as Slot
          }
          break
        case 3:
          tabbit.checkColumn(column, 'Loadout.Power', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_I32, tabbit.ELEMENT_VARINT])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Loadout.Power')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameI32(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._power = value
          }
          break
        case 4:
          tabbit.checkColumn(column, 'Loadout.Label', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_STRING])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Loadout.Label')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameString(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._label = value
          }
          break
        default:
          // A column added after this code was generated.
          reader.skip(column.byteLength)
          break
      }

      tabbit.checkBlockEnd(reader, column, blockEnd)
    }

    this.publish(records)
  }

  /** Index mapping. */
  /**
   * Publishes one whole load: the rows and the lookups built from them, together.
   *
   * Reading a table that is already loaded - a refresh, a patched file - used to mutate what
   * consumers were holding: the rows were appended to or emptied first, so a read that threw
   * partway left the table holding some of the new data and none of the old. Everything above
   * builds its own arrays and gets here only if it finished, and this replaces the references
   * in one step. Whoever took `records` before still has the previous load, whole.
   */
  private publish(records: LoadoutRecord[]): void {
    const recordsByStageAndSlot = new Map<string, LoadoutRecord>()

    for (const record of records) {
      recordsByStageAndSlot.set(LoadoutTable.keyOfStageAndSlot(record.stage, record.slot), record)
    }

    this._records = records
    this._recordsByStageAndSlot = recordsByStageAndSlot
  }
}
