// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as tabbit from '../tabbit/tcb-reader'

// The accessor, for the encryption key it holds. `tables` imports this module back, and
// that cycle is only ever read from inside a method - by which point both modules have
// finished evaluating - so neither one is half built when the binding is used.
import { Tables } from '../tables'

/** A type for handling rows when parsing .json. */
interface IDataRow {
  from: string
  to: string
  code: string
  distance: number
}

// Generated from test/fixtures/xlsx/composite-key/composite-key.xlsx : Route : B2
/** A composite primary key of strings, beside a single-column secondary one. */
export class RouteRecord {
  /** Default constructor */
  constructor() {
  }

  /** where it starts */
  public get from(): string { return this._from }

  /** where it ends */
  public get to(): string { return this._to }

  /** unique on its own */
  public get code(): string { return this._code }

  /** anything */
  public get distance(): number { return this._distance }

  public _from: string = ''
  public _to: string = ''
  public _code: string = ''
  public _distance: number = 0

  /** Populate field values. */
  public populateFieldValues(dataRow: IDataRow): void {
    this._from = dataRow.from
    this._to = dataRow.to
    this._code = dataRow.code
    this._distance = dataRow.distance
  }

  /** Populate field values. */
  public populateFieldValuesCompact(dataRow: any[]): void {
    let offset = 0
    this._from = dataRow[offset++]
    this._to = dataRow[offset++]
    this._code = dataRow[offset++]
    this._distance = dataRow[offset++]
  }
}

// Generated from test/fixtures/xlsx/composite-key/composite-key.xlsx : Route : B2
/** A composite primary key of strings, beside a single-column secondary one. */
export class RouteTable {
  /** Default constructor. */
  constructor() {
  }

  /** All records. */
  public get records(): RouteRecord[] { return this._records }
  private _records: RouteRecord[] = []

  /** How many rows the table holds. */
  public get count(): number { return this._records.length }

  /**
   * The rows, in the order the file wrote them.
   *
   * The array reference is read once, here. A refresh replaces the reference rather
   * than its contents, so a loop already running keeps the rows it started with.
   */
  public [Symbol.iterator](): IterableIterator<RouteRecord> {
    return this._records[Symbol.iterator]()
  }

  // Indexing by 'code'
  public get recordsByCode(): Map<string, RouteRecord> { return this._recordsByCode }
  private _recordsByCode: Map<string, RouteRecord> = new Map<string, RouteRecord>()

  /**
   * The row with this code, or undefined when the table has none.
   *
   * The lookup to reach for when a missing row is an ordinary answer.
   */
  public findByCode(key: string): RouteRecord | undefined {
    return this._recordsByCode.get(key)
  }

  /**
   * The row with this code, or a thrown Error naming what was missing.
   *
   * For a key that has to be there. The name says it throws, because a caller reading
   * `getByCode(id).name` at a glance cannot otherwise tell whether the
   * next line is a check or a catch.
   */
  public getByCodeOrThrow(key: string): RouteRecord {
    const found = this._recordsByCode.get(key)
    if (!found)
      throw new Error(`There is no record in table "Route" that corresponds to field "code" value ${key}`)

    return found
  }

  /** Whether the table holds a row with this code. */
  public containsCode(key: string): boolean {
    return this._recordsByCode.has(key)
  }

  // Indexing by 'From and To'
  private _recordsByFromAndTo: Map<string, RouteRecord> = new Map<string, RouteRecord>()

  /** Joins the columns of the From and To key into the text the map is keyed by. */
  private static keyOfFromAndTo(fromKey: string, toKey: string): string {
    const parts: string[] = [
      fromKey,
      toKey,
    ]

    let text = ""

    for (const part of parts)
      text += `${part.length}:${part}`

    return text
  }

  /**
   * The row with this From and To, or undefined when the table has none.
   *
   * The lookup to reach for when a missing row is an ordinary answer.
   */
  public findByFromAndTo(fromKey: string, toKey: string): RouteRecord | undefined {
    return this._recordsByFromAndTo.get(RouteTable.keyOfFromAndTo(fromKey, toKey))
  }

  /**
   * The row with this From and To, or a thrown Error naming what was missing.
   */
  public getByFromAndToOrThrow(fromKey: string, toKey: string): RouteRecord {
    const found = this._recordsByFromAndTo.get(RouteTable.keyOfFromAndTo(fromKey, toKey))
    if (!found)
      throw new Error(`There is no record in table "Route" that corresponds to field "From and To" value (${fromKey}, ${toKey})`)

    return found
  }

  /** Whether the table holds a row with this From and To. */
  public containsFromAndTo(fromKey: string, toKey: string): boolean {
    return this._recordsByFromAndTo.has(RouteTable.keyOfFromAndTo(fromKey, toKey))
  }

  /** Read a table from specified file. */
  public async read(filename: string): Promise<void> {
    const json = await fs.promises.readFile(filename, "utf8")
    this.readFromJson(json)
  }

  /** Read a table from specified file synchronously. */
  public readSync(filename: string): void {
    const json = fs.readFileSync(filename, "utf8")
    this.readFromJson(json)
  }

  private readFromJson(json: string): void {
    const dataRows: any[] = JSON.parse(json)
    const records: RouteRecord[] = []

    if (this.isCompactRowFormatted(dataRows)) {
      for (const dataRow of dataRows) {
        const record = new RouteRecord()
        record.populateFieldValuesCompact(dataRow)
        records.push(record)
      }
    } else {
      for (const dataRow of dataRows as IDataRow[]) {
        const record = new RouteRecord()
        record.populateFieldValues(dataRow)
        records.push(record)
      }
    }

    this.publish(records)
  }

  private isCompactRowFormatted(rows: any[]): boolean {
    return rows.length > 0 && Array.isArray(rows[0])
  }

  /** Read a table from a binary .tcb file. */
  public readBinarySync(filename: string): void {
    // Unconditionally, and with whatever `Tables.encryptionKey` and `Tables.macKey` hold -
    // which is null unless the project set them. A file that is neither encrypted nor signed
    // comes back from this untouched, so the load path is the same either way and there is
    // no condition here that could be the wrong way round. spec/wire/tcb-mac-and-signature.md.
    this.readBinaryFrom(tabbit.open(
      tabbit.readAllBytes(filename),
      Tables.encryptionKey, Tables.macKey, Tables.verifyMac))
  }

  /**
   * Read a table from binary data already in memory.
   *
   * Column by column, matched by tag rather than position: a column this build does not
   * know is skipped by its block length, and one whose type changed incompatibly fails
   * naming the field.
   */
  public readBinaryFrom(data: Uint8Array): void {
    const reader = new tabbit.TcbReader(data)
    const { rowCount, columns } = tabbit.readTableHeader(reader)
    let cursor: tabbit.TcbColumnCursor

    // Built here and published at the end, so a file that turns out to be truncated - or
    // a column this build cannot read - leaves the rows already loaded exactly as they are.
    const records: RouteRecord[] = []
    for (let i = 0; i < rowCount; ++i)
      records.push(new RouteRecord())

    for (const column of columns) {
      const blockEnd = reader.position + column.byteLength

      switch (column.tag) {
        case 1:
          tabbit.checkColumn(column, 'Route.From', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_STRING])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Route.From')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameString(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._from = value
          }
          break
        case 2:
          tabbit.checkColumn(column, 'Route.To', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_STRING])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Route.To')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameString(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._to = value
          }
          break
        case 3:
          tabbit.checkColumn(column, 'Route.Code', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_STRING])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Route.Code')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameString(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._code = value
          }
          break
        case 4:
          tabbit.checkColumn(column, 'Route.Distance', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_I32, tabbit.ELEMENT_VARINT])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'Route.Distance')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameI32(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._distance = value
          }
          break
        default:
          // A column added after this code was generated.
          reader.skip(column.byteLength)
          break
      }

      tabbit.checkBlockEnd(reader, column, blockEnd)
    }

    this.publish(records)
  }

  /** Index mapping. */
  /**
   * Publishes one whole load: the rows and the lookups built from them, together.
   *
   * Reading a table that is already loaded - a refresh, a patched file - used to mutate what
   * consumers were holding: the rows were appended to or emptied first, so a read that threw
   * partway left the table holding some of the new data and none of the old. Everything above
   * builds its own arrays and gets here only if it finished, and this replaces the references
   * in one step. Whoever took `records` before still has the previous load, whole.
   */
  private publish(records: RouteRecord[]): void {
    const recordsByCode = new Map<string, RouteRecord>()
    const recordsByFromAndTo = new Map<string, RouteRecord>()

    for (const record of records) {
      recordsByCode.set(record.code, record)
      recordsByFromAndTo.set(RouteTable.keyOfFromAndTo(record.from, record.to), record)
    }

    this._records = records
    this._recordsByCode = recordsByCode
    this._recordsByFromAndTo = recordsByFromAndTo
  }
}
