// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package serialref;

import tabbit.TcbReader;

// Generated from test/fixtures/xlsx/serial-ref-trim/serial-ref-trim.xlsx : Refs : J2
/** Numbered reference columns folded into an array the row's length. */
public final class TrimKitRecord {
    /** primary index */
    public int index;
    /** element 1 - the row it points at */
    public BitRecord[] slotArray = new BitRecord[0];
    public int[] slotArrayIndex = new int[0];
    /**
     * Which of slotArray's elements have a value. Empty where the file did not carry
     * the column, and then every index is out of range anyway.
     */
    public boolean[] hasSlotArrayAt = new boolean[0];
    /** element 1 - the target's own value */
    public int[] tierArray = new int[0];
    public int[] tierArrayIndex = new int[0];
    /**
     * Which of tierArray's elements have a value. Empty where the file did not carry
     * the column, and then every index is out of range anyway.
     */
    public boolean[] hasTierArrayAt = new boolean[0];

}
