// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------


// Tables
export { ColourRecord } from './tables/colour'
export { ColourTable } from './tables/colour'
export { BrushRecord } from './tables/brush'
export { BrushTable } from './tables/brush'
export { NarrowRecord } from './tables/narrow'
export { NarrowTable } from './tables/narrow'
export { PaintRecord } from './tables/paint'
export { PaintTable } from './tables/paint'

export { Tables } from './tables'
