// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

import { PotionTable } from './tables/potion'
import { SampleTable } from './tables/sample'
import { MarkerTable } from './tables/marker'
import { AccessTable } from './tables/access'
import { LineTable } from './tables/line'
import { AnimationTable } from './tables/animation'
import { WireTable } from './tables/wire'
import { ShopTable } from './tables/shop'
import { ShopEntryTable } from './tables/shop-entry'
import { CraftTable } from './tables/craft'
import { LootTable } from './tables/loot'
import { DropTable } from './tables/drop'
import { SpawnTable } from './tables/spawn'
import { DeckTable } from './tables/deck'
import { QuestTable } from './tables/quest'
import { StageRewardTable } from './tables/stage-reward'
import { ServerTuningTable } from './tables/server-tuning'
import { PriceTable } from './tables/price'
import { SkillTable } from './tables/skill'

/** Tables */
export class Tables {
  /**
   * The key the table files were sealed with, or null when they were not sealed.
   *
   * Beside the load calls because it is the same kind of thing: one decision the consuming
   * project makes once, at start-up, before the first table is read. A key threaded through
   * every read signature would be the same value written out at every call site, and every
   * call site is somewhere it could be wrong.
   *
   * Thirty-two bytes, the key the converter was given. Null - the default - is a project
   * that does not encrypt, and it costs that project nothing: the load path opens the
   * envelope either way, and a file that is not encrypted comes back from that unchanged. A
   * project that does encrypt and leaves this null gets the reader's own message saying the
   * file is encrypted and no key was given, rather than a failure somewhere inside the
   * format.
   *
   * Where the key comes from is the one thing about this layer worth being careful with. It
   * is a secret only until it reaches a repository, a build log or an issue, and it cannot
   * be taken back afterwards - so it is read at start-up from wherever this project keeps
   * secrets, not written into a source file and not bundled into anything a browser can
   * fetch. What the layer is for, and therefore what is and is not worth defending, is
   * spec/wire/tcb-v104-composed-encodings.md section 4.
   */
  public static encryptionKey: Uint8Array | null = null

  /**
   * The key the table files were signed with, or null when they were not signed.
   *
   * A different key from `encryptionKey` and independent of it: a file can be signed without
   * being encrypted, and encrypted without being signed.
   *
   * What it buys is the thing encryption does not. The cipher is a keystream XOR, so a bit
   * flipped in the file is a bit flipped in the value it decrypts to - no key needed - and
   * every structural check the format makes still passes, because a four-byte float accepts
   * any four bytes. With this set, a file altered after export stops loading instead.
   *
   * Setting it makes the reader stricter in a second way: a file that carries no MAC is
   * refused, because otherwise the check could be removed by zeroing sixteen bytes. So the
   * order to turn this on in is data first, key second.
   * spec/wire/tcb-mac-and-signature.md.
   */
  public static macKey: Uint8Array | null = null

  /**
   * Whether to check the MAC at all. True by default.
   *
   * For tools that read exported files without the key, and for measuring what the check
   * costs at load. It is not a security boundary - anyone who can flip a flag in a shipped
   * bundle can read `macKey` out of the same bundle.
   */
  public static verifyMac = true

  /** Peroperty for table Potion */
  public get potion(): PotionTable { return this._potion }
  private _potion: PotionTable = new PotionTable()

  /** Peroperty for table Sample */
  public get sample(): SampleTable { return this._sample }
  private _sample: SampleTable = new SampleTable()

  /** Peroperty for table Marker */
  public get marker(): MarkerTable { return this._marker }
  private _marker: MarkerTable = new MarkerTable()

  /** Peroperty for table Access */
  public get access(): AccessTable { return this._access }
  private _access: AccessTable = new AccessTable()

  /** Peroperty for table Line */
  public get line(): LineTable { return this._line }
  private _line: LineTable = new LineTable()

  /** Peroperty for table Animation */
  public get animation(): AnimationTable { return this._animation }
  private _animation: AnimationTable = new AnimationTable()

  /** Peroperty for table Wire */
  public get wire(): WireTable { return this._wire }
  private _wire: WireTable = new WireTable()

  /** Peroperty for table Shop */
  public get shop(): ShopTable { return this._shop }
  private _shop: ShopTable = new ShopTable()

  /** Peroperty for table ShopEntry */
  public get shopEntry(): ShopEntryTable { return this._shopEntry }
  private _shopEntry: ShopEntryTable = new ShopEntryTable()

  /** Peroperty for table Craft */
  public get craft(): CraftTable { return this._craft }
  private _craft: CraftTable = new CraftTable()

  /** Peroperty for table Loot */
  public get loot(): LootTable { return this._loot }
  private _loot: LootTable = new LootTable()

  /** Peroperty for table Drop */
  public get drop(): DropTable { return this._drop }
  private _drop: DropTable = new DropTable()

  /** Peroperty for table Spawn */
  public get spawn(): SpawnTable { return this._spawn }
  private _spawn: SpawnTable = new SpawnTable()

  /** Peroperty for table Deck */
  public get deck(): DeckTable { return this._deck }
  private _deck: DeckTable = new DeckTable()

  /** Peroperty for table Quest */
  public get quest(): QuestTable { return this._quest }
  private _quest: QuestTable = new QuestTable()

  /** Peroperty for table StageReward */
  public get stageReward(): StageRewardTable { return this._stageReward }
  private _stageReward: StageRewardTable = new StageRewardTable()

  /** Peroperty for table ServerTuning */
  public get serverTuning(): ServerTuningTable { return this._serverTuning }
  private _serverTuning: ServerTuningTable = new ServerTuningTable()

  /** Peroperty for table Price */
  public get price(): PriceTable { return this._price }
  private _price: PriceTable = new PriceTable()

  /** Peroperty for table Skill */
  public get skill(): SkillTable { return this._skill }
  private _skill: SkillTable = new SkillTable()

  /**
   * Read all tables from the JSON export, asynchronously.
   *
   * `load` is given a file name - `Item.json`, say - and returns
   * that file's text. Where it looks is the caller's: a directory under Node, a URL in a
   * browser, an asset store in an engine. Nothing here names a runtime module, which is
   * what lets the same generated code load in all three.
   *
   * `fileExtension` defaults to what the JSON exporter writes. Pass a different one when the
   * data files were renamed after export.
   */
  public async readAll(load: (fileName: string) => Promise<string>, fileExtension: string = '.json'): Promise<void> {
    const potion = new PotionTable()
    potion.readJsonFrom(await load(`Potion${fileExtension}`))
    const sample = new SampleTable()
    sample.readJsonFrom(await load(`Sample${fileExtension}`))
    const marker = new MarkerTable()
    marker.readJsonFrom(await load(`Marker${fileExtension}`))
    const access = new AccessTable()
    access.readJsonFrom(await load(`Access${fileExtension}`))
    const line = new LineTable()
    line.readJsonFrom(await load(`Line${fileExtension}`))
    const animation = new AnimationTable()
    animation.readJsonFrom(await load(`Animation${fileExtension}`))
    const wire = new WireTable()
    wire.readJsonFrom(await load(`Wire${fileExtension}`))
    const shop = new ShopTable()
    shop.readJsonFrom(await load(`Shop${fileExtension}`))
    const shopEntry = new ShopEntryTable()
    shopEntry.readJsonFrom(await load(`ShopEntry${fileExtension}`))
    const craft = new CraftTable()
    craft.readJsonFrom(await load(`Craft${fileExtension}`))
    const loot = new LootTable()
    loot.readJsonFrom(await load(`Loot${fileExtension}`))
    const drop = new DropTable()
    drop.readJsonFrom(await load(`Drop${fileExtension}`))
    const spawn = new SpawnTable()
    spawn.readJsonFrom(await load(`Spawn${fileExtension}`))
    const deck = new DeckTable()
    deck.readJsonFrom(await load(`Deck${fileExtension}`))
    const quest = new QuestTable()
    quest.readJsonFrom(await load(`Quest${fileExtension}`))
    const stageReward = new StageRewardTable()
    stageReward.readJsonFrom(await load(`StageReward${fileExtension}`))
    const serverTuning = new ServerTuningTable()
    serverTuning.readJsonFrom(await load(`ServerTuning${fileExtension}`))
    const price = new PriceTable()
    price.readJsonFrom(await load(`Price${fileExtension}`))
    const skill = new SkillTable()
    skill.readJsonFrom(await load(`Skill${fileExtension}`))

    this.publish(potion, sample, marker, access, line, animation, wire, shop, shopEntry, craft, loot, drop, spawn, deck, quest, stageReward, serverTuning, price, skill)
  }

  /** Read all tables from the JSON export, synchronously. `load` returns a file's text. */
  public readAllSync(load: (fileName: string) => string, fileExtension: string = '.json'): void {
    const potion = new PotionTable()
    potion.readJsonFrom(load(`Potion${fileExtension}`))
    const sample = new SampleTable()
    sample.readJsonFrom(load(`Sample${fileExtension}`))
    const marker = new MarkerTable()
    marker.readJsonFrom(load(`Marker${fileExtension}`))
    const access = new AccessTable()
    access.readJsonFrom(load(`Access${fileExtension}`))
    const line = new LineTable()
    line.readJsonFrom(load(`Line${fileExtension}`))
    const animation = new AnimationTable()
    animation.readJsonFrom(load(`Animation${fileExtension}`))
    const wire = new WireTable()
    wire.readJsonFrom(load(`Wire${fileExtension}`))
    const shop = new ShopTable()
    shop.readJsonFrom(load(`Shop${fileExtension}`))
    const shopEntry = new ShopEntryTable()
    shopEntry.readJsonFrom(load(`ShopEntry${fileExtension}`))
    const craft = new CraftTable()
    craft.readJsonFrom(load(`Craft${fileExtension}`))
    const loot = new LootTable()
    loot.readJsonFrom(load(`Loot${fileExtension}`))
    const drop = new DropTable()
    drop.readJsonFrom(load(`Drop${fileExtension}`))
    const spawn = new SpawnTable()
    spawn.readJsonFrom(load(`Spawn${fileExtension}`))
    const deck = new DeckTable()
    deck.readJsonFrom(load(`Deck${fileExtension}`))
    const quest = new QuestTable()
    quest.readJsonFrom(load(`Quest${fileExtension}`))
    const stageReward = new StageRewardTable()
    stageReward.readJsonFrom(load(`StageReward${fileExtension}`))
    const serverTuning = new ServerTuningTable()
    serverTuning.readJsonFrom(load(`ServerTuning${fileExtension}`))
    const price = new PriceTable()
    price.readJsonFrom(load(`Price${fileExtension}`))
    const skill = new SkillTable()
    skill.readJsonFrom(load(`Skill${fileExtension}`))

    this.publish(potion, sample, marker, access, line, animation, wire, shop, shopEntry, craft, loot, drop, spawn, deck, quest, stageReward, serverTuning, price, skill)
  }

  /**
   * Read all tables from the binary export, asynchronously.
   *
   * The counterpart of `readAll`, and the one to use when the data is binary: reading a
   * table on its own with `readBinaryFrom` leaves its references unlinked, because linking
   * needs every table. Both formats produce the same values.
   *
   * `load` returns a file's bytes as the file holds them; each table opens its own envelope.
   * Asynchronous because that is what a fetch and an engine's asset loader are.
   */
  public async readAllBinary(load: (fileName: string) => Promise<Uint8Array>, fileExtension: string = '.tcb'): Promise<void> {
    const potion = new PotionTable()
    potion.readBinaryFrom(await load(`Potion${fileExtension}`))
    const sample = new SampleTable()
    sample.readBinaryFrom(await load(`Sample${fileExtension}`))
    const marker = new MarkerTable()
    marker.readBinaryFrom(await load(`Marker${fileExtension}`))
    const access = new AccessTable()
    access.readBinaryFrom(await load(`Access${fileExtension}`))
    const line = new LineTable()
    line.readBinaryFrom(await load(`Line${fileExtension}`))
    const animation = new AnimationTable()
    animation.readBinaryFrom(await load(`Animation${fileExtension}`))
    const wire = new WireTable()
    wire.readBinaryFrom(await load(`Wire${fileExtension}`))
    const shop = new ShopTable()
    shop.readBinaryFrom(await load(`Shop${fileExtension}`))
    const shopEntry = new ShopEntryTable()
    shopEntry.readBinaryFrom(await load(`ShopEntry${fileExtension}`))
    const craft = new CraftTable()
    craft.readBinaryFrom(await load(`Craft${fileExtension}`))
    const loot = new LootTable()
    loot.readBinaryFrom(await load(`Loot${fileExtension}`))
    const drop = new DropTable()
    drop.readBinaryFrom(await load(`Drop${fileExtension}`))
    const spawn = new SpawnTable()
    spawn.readBinaryFrom(await load(`Spawn${fileExtension}`))
    const deck = new DeckTable()
    deck.readBinaryFrom(await load(`Deck${fileExtension}`))
    const quest = new QuestTable()
    quest.readBinaryFrom(await load(`Quest${fileExtension}`))
    const stageReward = new StageRewardTable()
    stageReward.readBinaryFrom(await load(`StageReward${fileExtension}`))
    const serverTuning = new ServerTuningTable()
    serverTuning.readBinaryFrom(await load(`ServerTuning${fileExtension}`))
    const price = new PriceTable()
    price.readBinaryFrom(await load(`Price${fileExtension}`))
    const skill = new SkillTable()
    skill.readBinaryFrom(await load(`Skill${fileExtension}`))

    this.publish(potion, sample, marker, access, line, animation, wire, shop, shopEntry, craft, loot, drop, spawn, deck, quest, stageReward, serverTuning, price, skill)
  }

  /** Read all tables from the binary export, synchronously. `load` returns a file's bytes. */
  public readAllBinarySync(load: (fileName: string) => Uint8Array, fileExtension: string = '.tcb'): void {
    const potion = new PotionTable()
    potion.readBinaryFrom(load(`Potion${fileExtension}`))
    const sample = new SampleTable()
    sample.readBinaryFrom(load(`Sample${fileExtension}`))
    const marker = new MarkerTable()
    marker.readBinaryFrom(load(`Marker${fileExtension}`))
    const access = new AccessTable()
    access.readBinaryFrom(load(`Access${fileExtension}`))
    const line = new LineTable()
    line.readBinaryFrom(load(`Line${fileExtension}`))
    const animation = new AnimationTable()
    animation.readBinaryFrom(load(`Animation${fileExtension}`))
    const wire = new WireTable()
    wire.readBinaryFrom(load(`Wire${fileExtension}`))
    const shop = new ShopTable()
    shop.readBinaryFrom(load(`Shop${fileExtension}`))
    const shopEntry = new ShopEntryTable()
    shopEntry.readBinaryFrom(load(`ShopEntry${fileExtension}`))
    const craft = new CraftTable()
    craft.readBinaryFrom(load(`Craft${fileExtension}`))
    const loot = new LootTable()
    loot.readBinaryFrom(load(`Loot${fileExtension}`))
    const drop = new DropTable()
    drop.readBinaryFrom(load(`Drop${fileExtension}`))
    const spawn = new SpawnTable()
    spawn.readBinaryFrom(load(`Spawn${fileExtension}`))
    const deck = new DeckTable()
    deck.readBinaryFrom(load(`Deck${fileExtension}`))
    const quest = new QuestTable()
    quest.readBinaryFrom(load(`Quest${fileExtension}`))
    const stageReward = new StageRewardTable()
    stageReward.readBinaryFrom(load(`StageReward${fileExtension}`))
    const serverTuning = new ServerTuningTable()
    serverTuning.readBinaryFrom(load(`ServerTuning${fileExtension}`))
    const price = new PriceTable()
    price.readBinaryFrom(load(`Price${fileExtension}`))
    const skill = new SkillTable()
    skill.readBinaryFrom(load(`Skill${fileExtension}`))

    this.publish(potion, sample, marker, access, line, animation, wire, shop, shopEntry, craft, loot, drop, spawn, deck, quest, stageReward, serverTuning, price, skill)
  }

  /**
   * Publishes one whole load.
   *
   * Reading again - a refresh, a downloaded patch - loads into tables of its own and gets
   * here only once every file has been read. A failure anywhere leaves every table holding
   * what it held, which is the answer a running program wants: the data it already had, and
   * an exception saying why the new data was not taken.
   */
  private publish(potion: PotionTable, sample: SampleTable, marker: MarkerTable, access: AccessTable, line: LineTable, animation: AnimationTable, wire: WireTable, shop: ShopTable, shopEntry: ShopEntryTable, craft: CraftTable, loot: LootTable, drop: DropTable, spawn: SpawnTable, deck: DeckTable, quest: QuestTable, stageReward: StageRewardTable, serverTuning: ServerTuningTable, price: PriceTable, skill: SkillTable): void {
    this._potion = potion
    this._sample = sample
    this._marker = marker
    this._access = access
    this._line = line
    this._animation = animation
    this._wire = wire
    this._shop = shop
    this._shopEntry = shopEntry
    this._craft = craft
    this._loot = loot
    this._drop = drop
    this._spawn = spawn
    this._deck = deck
    this._quest = quest
    this._stageReward = stageReward
    this._serverTuning = serverTuning
    this._price = price
    this._skill = skill

    this.solveCrossReferences()
  }

  /**
   * Turns the stored keys into the rows they name, once every table is in memory.
   *
   * A `foreign` column travels as the target row's primary key, so a table read on its own
   * has the key and not the row - which is why this runs from `publish` and not from a
   * table's own read. A zero means the sheet left the cell empty and is left unresolved.
   */
  private solveCrossReferences(): void {
    for (const record of this._shopEntry.records) {
      if (record._shopId_Shop_index > 0) {
        const target = this._shop.getByIndexOrThrow(
          record._shopId_Shop_index)
        record.setReference_shopId_INTERNAL(target)
      }
      if (record._potionId_Potion_index > 0) {
        const target = this._potion.getByIndexOrThrow(
          record._potionId_Potion_index)
        record.setReference_potionId_INTERNAL(target)
      }
    }

    for (const record of this._craft.records) {
      if (record._result_Potion_index > 0) {
        const target = this._potion.getByIndexOrThrow(
          record._result_Potion_index)
        record.setReference_result_INTERNAL(target)
      }
      if (record._resultName_Potion_index > 0) {
        const target = this._potion.getByIndexOrThrow(
          record._resultName_Potion_index)
        record.setReference_resultName_INTERNAL(target.name)
      }
      for (let i = 0; i < record._parts_Potion_index.length; i++) {
        if (record._parts_Potion_index[i] > 0) {
          const target = this._potion.getByIndexOrThrow(
            record._parts_Potion_index[i])
          record.setReference_parts_INTERNAL(i, target)
        }
      }
      if (record._substitute_Potion_index > 0) {
        const target = this._potion.getByIndexOrThrow(
          record._substitute_Potion_index)
        record.setReference_substitute_INTERNAL(target)
      }
    }
  }
}
