/* ------------------------------------------------------------------------------
 * Generated by Tabbit. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#ifndef MULTI_TARGET_ENUM_HOLDER_WIDE_TARGET_H
#define MULTI_TARGET_ENUM_HOLDER_WIDE_TARGET_H

/* Generated from test/fixtures/xlsx/multi-target/multi-target.xlsx : Holders : E4
 *
 * Which table `Holder.Wide` points at. The column carries one id and the tables it may be a row of take separate id bands, so exactly one of them answers.
 */
typedef enum MultiTarget_HolderWideTarget_t {
  /* No row of any of them. */
  MULTI_TARGET_HOLDER_WIDE_TARGET_NONE = 0,
  /* A row of `Weapon`. */
  MULTI_TARGET_HOLDER_WIDE_TARGET_WEAPON = 1,
  /* A row of `Armour`. */
  MULTI_TARGET_HOLDER_WIDE_TARGET_ARMOUR = 2,
  /* A row of `Trinket`. */
  MULTI_TARGET_HOLDER_WIDE_TARGET_TRINKET = 3,
  /* A row of `Mount`. */
  MULTI_TARGET_HOLDER_WIDE_TARGET_MOUNT = 4,
  /* A row of `Banner`. */
  MULTI_TARGET_HOLDER_WIDE_TARGET_BANNER = 5,
} MultiTarget_HolderWideTarget_t;

#endif /* MULTI_TARGET_ENUM_HOLDER_WIDE_TARGET_H */
