// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package tabbit.fixtures.compositekey;

import java.nio.file.Path;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import tabbit.TcbReader;

/** Every row of Beast. */
public final class BeastTable implements Iterable<BeastRecord> {
    private List<BeastRecord> records = new ArrayList<>();
    private Map<String, BeastRecord> byIndex = new HashMap<>();

    /**
     * Every row, in the order the sheet declared them.
     *
     * The list a read published, not one a read fills. A refresh replaces the reference
     * rather than the contents, so whoever holds this holds one whole load.
     */
    public List<BeastRecord> records() {
        return records;
    }

    /** How many rows the table holds. */
    public int size() {
        return records.size();
    }

    /**
     * The rows, in the order the file wrote them.
     *
     * The list reference is read once, here. A refresh replaces the reference rather than
     * its contents, so a loop already running keeps the rows it started with.
     */
    @Override
    public Iterator<BeastRecord> iterator() {
        return records.iterator();
    }

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public BeastRecord findByIndex(String key) {
        return byIndex.get(key);
    }

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex(key).name() at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public BeastRecord getByIndexOrThrow(String key) {
        BeastRecord record = byIndex.get(key);

        if (record == null) {
            throw new TcbReader.RecordNotFoundException(
                "there is no record in table `Beast` that corresponds to field "
                + "`Index` value " + key);
        }

        return record;
    }

    /** Whether the table holds a row with this Index. */
    public boolean containsIndex(String key) {
        return byIndex.containsKey(key);
    }


    /**
     * Each row with the Index it is keyed by -
     * `for (var entry : table.entries())`.
     *
     * What this saves a caller is not the key value - the row carries it - but having to
     * know which column the key is: Index here, something else in the next
     * table.
     *
     * The rows come in the order the file wrote them rather than the order the map holds
     * them, which makes this and iterating the table agree. Only the primary key has this:
     * a table keyed by several columns together has no single key value to pair a row with.
     */
    public Iterable<Map.Entry<String, BeastRecord>> entries() {
        final List<BeastRecord> rows = records;

        return () -> new Iterator<Map.Entry<String, BeastRecord>>() {
            private final Iterator<BeastRecord> source = rows.iterator();

            @Override
            public boolean hasNext() {
                return source.hasNext();
            }

            @Override
            public Map.Entry<String, BeastRecord> next() {
                final BeastRecord row = source.next();

                return new AbstractMap.SimpleImmutableEntry<>(row.index, row);
            }
        };
    }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public void read(Path filename) {
        // Opened unconditionally, and with whatever CompositeKeyAccessor.encryptionKey and
        // CompositeKeyAccessor.macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from this untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/wire/tcb-mac-and-signature.md.
        TcbReader reader = new TcbReader(TcbReader.open(
            TcbReader.readAllBytes(filename), CompositeKeyAccessor.encryptionKey,
            CompositeKeyAccessor.macKey, CompositeKeyAccessor.verifyMac));
        TcbReader.Header header = TcbReader.readTableHeader(reader);
        int count = header.rowCount;
        TcbReader.ColumnCursor cursor;

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        List<BeastRecord> loaded = new ArrayList<>(count);
        Map<String, BeastRecord> loadedByIndex = new HashMap<>(count * 2);

        for (int i = 0; i < count; i++) {
            loaded.add(new BeastRecord());
        }

        for (TcbReader.Column column : header.columns) {
            int blockEnd = reader.position() + column.byteLength;

            switch (column.tag) {
                case 1: {
                    TcbReader.checkColumn(column, "Beast.Index", TcbReader.KIND_SCALAR, false, TcbReader.ELEMENT_STRING);
                    cursor = new TcbReader.ColumnCursor(reader, column, count, "Beast.Index");
                    for (int i = 0; i < count; ) {
                        int n = cursor.nextSameString(count - i);
                        for (; n > 0; n--, i++) {
                            loaded.get(i).index = cursor.runSameText;
                        }
                    }
                    break;
                }
                case 2: {
                    TcbReader.checkColumn(column, "Beast.Name", TcbReader.KIND_SCALAR, false, TcbReader.ELEMENT_STRING);
                    cursor = new TcbReader.ColumnCursor(reader, column, count, "Beast.Name");
                    for (int i = 0; i < count; ) {
                        int n = cursor.nextSameString(count - i);
                        for (; n > 0; n--, i++) {
                            loaded.get(i).name = cursor.runSameText;
                        }
                    }
                    break;
                }
                case 3: {
                    TcbReader.checkColumn(column, "Beast.Pad1", TcbReader.KIND_SCALAR, false, TcbReader.ELEMENT_I32, TcbReader.ELEMENT_VARINT);
                    cursor = new TcbReader.ColumnCursor(reader, column, count, "Beast.Pad1");
                    for (int i = 0; i < count; ) {
                        int n = cursor.nextSameI32(count - i);
                        for (; n > 0; n--, i++) {
                            loaded.get(i).pad1 = cursor.runSameValue;
                        }
                    }
                    break;
                }
                default:
                    // A column added after this code was generated.
                    reader.skip(column.byteLength);
                    break;
            }

            TcbReader.checkBlockEnd(reader, column, blockEnd);
        }

        for (BeastRecord record : loaded) {
            loadedByIndex.put(record.index, record);
        }

        // Published, now that every column read.
        records = loaded;
        byIndex = loadedByIndex;
    }
}
