// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

@file:Suppress("unused", "RedundantVisibilityModifier", "UNUSED_IMPORT")

package tabbit.fixtures.declared

import java.io.File
import tabbit.TcbReader
import tabbit.RecordNotFoundException
import tabbit.Uuid
import tabbit.readAllBytes
import tabbit.open
import tabbit.readTableHeader
import tabbit.checkColumn
import tabbit.checkColumnWithElements
import tabbit.checkBlockEnd
import tabbit.readPresence
import tabbit.readElementPresence
import tabbit.isPresent
import tabbit.TcbException
import tabbit.ColumnCursor
import tabbit.ELEMENT_VARINT
import tabbit.ELEMENT_BOOL
import tabbit.ELEMENT_I32
import tabbit.ELEMENT_I64
import tabbit.ELEMENT_F32
import tabbit.ELEMENT_F64
import tabbit.ELEMENT_STRING
import tabbit.ELEMENT_UUID
import tabbit.KIND_SCALAR
import tabbit.KIND_ARRAY

// Generated from test/fixtures/xlsx/declared/declared.xlsx : Declared : B24
/** A second table whose group the same declaration types. */
class ChestRecord {
    /** primary index */
    var index: Int = 0
    /** Which item, as that table's key. */
    var prize: Reward = Reward()


}

/** Every row of Chest. */
class ChestTable : Iterable<ChestRecord> {

    /**
     * Every row, in the order the sheet declared them.
     *
     * The list a read published, not one a read fills. A refresh replaces the reference
     * rather than the contents, so whoever holds this holds one whole load.
     */
    var records: MutableList<ChestRecord> = ArrayList()
        private set

    /** How many rows the table holds. */
    val size: Int
        get() = records.size

    /**
     * The rows, in the order the file wrote them.
     *
     * The list reference is read once, here. A refresh replaces the reference rather than
     * its contents, so a loop already running keeps the rows it started with.
     */
    override fun iterator(): Iterator<ChestRecord> = records.iterator()

    private var byIndex: HashMap<Int, ChestRecord> = HashMap()

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    fun findByIndex(key: Int): ChestRecord? = byIndex[key]

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex(key).name at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    fun getByIndexOrThrow(key: Int): ChestRecord =
        byIndex[key] ?: throw RecordNotFoundException(
            "there is no record in table `Chest` that corresponds to " +
                "field `Index` value $key")

    /** Whether the table holds a row with this Index. */
    fun containsIndex(key: Int): Boolean = byIndex.containsKey(key)


    /**
     * The row with this Index, or null when the table has none.
     *
     * findByIndex under the spelling Kotlin uses for a keyed collection. It
     * answers with null because that is what Map does here, and the type says so - a
     * language whose own map throws generates a subscript that throws.
     * spec/targets/table-collection-surface.md section 5.7.
     *
     * This is the key, not the row's position. `table[0]` is the row whose
     * Index is 0, not the first row - the rows in order are `records`.
     */
    operator fun get(key: Int): ChestRecord? = findByIndex(key)


    /**
     * Each row with the Index it is keyed by -
     * `for ((key, row) in table.entries)`.
     *
     * What this saves a caller is not the key value - the row carries it - but having to
     * know which column the key is: Index here, something else in the next
     * table.
     *
     * The rows come in the order the file wrote them rather than the order the map holds
     * them, which makes this and iterating the table agree. Only the primary key has this:
     * a table keyed by several columns together has no single key value to pair a row with.
     */
    val entries: Sequence<Pair<Int, ChestRecord>>
        get() = records.asSequence().map { record -> record.index to record }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    fun read(filename: String) {
        // Opened unconditionally, and with whatever DeclaredAccessor.encryptionKey and
        // DeclaredAccessor.macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from this untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/wire/tcb-mac-and-signature.md.
        val reader = TcbReader(open(
            readAllBytes(filename), DeclaredAccessor.encryptionKey,
            DeclaredAccessor.macKey, DeclaredAccessor.verifyMac))
        val header = readTableHeader(reader)
        val count = header.rowCount

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        val loaded = ArrayList<ChestRecord>(count)
        val loadedByIndex = HashMap<Int, ChestRecord>(count * 2)

        repeat(count) { loaded.add(ChestRecord()) }

        for (column in header.columns) {
            val blockEnd = reader.position + column.byteLength

            when (column.tag) {
                1 -> {
                    checkColumn(column, "Chest.Index", KIND_SCALAR, false, ELEMENT_I32, ELEMENT_VARINT)
                    val cursor = ColumnCursor(reader, column, count, "Chest.Index")
                    var at = 0
                    while (at < count) {
                        var n = cursor.nextSameI32(count - at)
                        while (n > 0) {
                            val i = at
                            loaded[i].index = cursor.runSameValue
                            at++
                            n--
                        }
                    }
                }
                2 -> {
                    checkColumn(column, "Chest.Prize.ItemId", KIND_SCALAR, false, ELEMENT_I32, ELEMENT_VARINT)
                    val cursor = ColumnCursor(reader, column, count, "Chest.Prize.ItemId")
                    var at = 0
                    while (at < count) {
                        var n = cursor.nextSameI32(count - at)
                        while (n > 0) {
                            val i = at
                            loaded[i].prize.itemId = cursor.runSameValue
                            at++
                            n--
                        }
                    }
                }
                3 -> {
                    checkColumn(column, "Chest.Prize.Count", KIND_SCALAR, false, ELEMENT_I32, ELEMENT_VARINT)
                    val cursor = ColumnCursor(reader, column, count, "Chest.Prize.Count")
                    var at = 0
                    while (at < count) {
                        var n = cursor.nextSameI32(count - at)
                        while (n > 0) {
                            val i = at
                            loaded[i].prize.count = cursor.runSameValue
                            at++
                            n--
                        }
                    }
                }
                4 -> {
                    checkColumn(column, "Chest.Prize.Icon", KIND_SCALAR, false, ELEMENT_STRING)
                    val cursor = ColumnCursor(reader, column, count, "Chest.Prize.Icon")
                    var at = 0
                    while (at < count) {
                        var n = cursor.nextSameString(count - at)
                        while (n > 0) {
                            val i = at
                            loaded[i].prize.icon = cursor.runSameText
                            at++
                            n--
                        }
                    }
                }
                else ->
                    // A column added after this code was generated.
                    reader.skip(column.byteLength)
            }

            checkBlockEnd(reader, column, blockEnd)
        }

        for (record in loaded) {
            loadedByIndex[record.index] = record
        }

        // Published, now that every column read.
        records = loaded
        byIndex = loadedByIndex
    }
}
