/* ------------------------------------------------------------------------------
 * Generated by Tabbit. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#ifndef MULTI_TARGET_HOLDER_H
#define MULTI_TARGET_HOLDER_H

#include "tabbit/tabbit_tcb_reader.h"

#include "MultiTarget_Forward.h"
#include "enums/MultiTarget_EnumHolderPickTarget.h"
#include "enums/MultiTarget_EnumHolderWideTarget.h"
#include "enums/MultiTarget_EnumHolderMaybeTarget.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Generated from test/fixtures/xlsx/multi-target/multi-target.xlsx : Holders : B2
 *
 * One column per case the spec states.
 */
struct MultiTarget_HolderRecord_t {
  /* primary index */
  int32_t index;
  /* two targets - the ordinary case */
  int32_t pick;
  /* five targets, and the value picks one */
  int32_t wide;
  /* the same notation with one name */
  const MultiTarget_WeaponRecord_t* only;
  int32_t only_index;
  /* two targets, and `-` is none of them */
  int32_t maybe;
  /* Whether this row has a value for maybe. The value member keeps its type and
   * holds the type's empty value when the row had none; this says which it was. */
  bool has_maybe;
  /* The row pick names, as whichever of its target tables holds it. Read it
   * through the functions below rather than directly: they check the discriminator first. */
  const void* pick_row;

  /* Which table pick is a row of. */
  MultiTarget_HolderPickTarget_t pick_target;
  /* The row wide names, as whichever of its target tables holds it. Read it
   * through the functions below rather than directly: they check the discriminator first. */
  const void* wide_row;

  /* Which table wide is a row of. */
  MultiTarget_HolderWideTarget_t wide_target;
  /* The row maybe names, as whichever of its target tables holds it. Read it
   * through the functions below rather than directly: they check the discriminator first. */
  const void* maybe_row;

  /* Which table maybe is a row of. */
  MultiTarget_HolderMaybeTarget_t maybe_target;
};

/* The MultiTarget_WeaponRecord_t row pick names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_WeaponRecord_t* MultiTarget_HolderPickAsWeapon(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_ArmourRecord_t row pick names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_ArmourRecord_t* MultiTarget_HolderPickAsArmour(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_WeaponRecord_t row wide names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_WeaponRecord_t* MultiTarget_HolderWideAsWeapon(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_ArmourRecord_t row wide names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_ArmourRecord_t* MultiTarget_HolderWideAsArmour(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_TrinketRecord_t row wide names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_TrinketRecord_t* MultiTarget_HolderWideAsTrinket(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_MountRecord_t row wide names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_MountRecord_t* MultiTarget_HolderWideAsMount(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_BannerRecord_t row wide names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_BannerRecord_t* MultiTarget_HolderWideAsBanner(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_WeaponRecord_t row maybe names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_WeaponRecord_t* MultiTarget_HolderMaybeAsWeapon(const MultiTarget_HolderRecord_t* record);

/* The MultiTarget_ArmourRecord_t row maybe names, or NULL when it names a row of
 * one of the others. */
const MultiTarget_ArmourRecord_t* MultiTarget_HolderMaybeAsArmour(const MultiTarget_HolderRecord_t* record);

/* Every row of Holder.
 *
 * The arena owns every string and every array the records point into, so the
 * whole table is released in one call and no record's pointer outlives it. */
typedef struct MultiTarget_HolderTable_t {
  MultiTarget_HolderRecord_t* records;
  int32_t count;

  tb_index_entry* by_index;
  tb_arena arena;
} MultiTarget_HolderTable_t;

/* Loads the table from a .tcb file written by Tabbit.
 *
 * Returns false and leaves the table empty when the file is missing, truncated
 * or malformed; the reason goes to `error` when one is passed. */
bool MultiTarget_HolderLoad(MultiTarget_HolderTable_t* table, const char* filename,
                   char* error, size_t error_size);

/* Releases everything the table owns. Safe on a zeroed table, and safe twice. */
void MultiTarget_HolderFree(MultiTarget_HolderTable_t* table);

/* The row with the given Index, or NULL when the table has none.
 *
 * The lookup to reach for when a missing row is an ordinary answer - an optional
 * reference, a key that came from user input. C has nothing to throw, so a caller
 * that needs the row to be there checks this NULL and says so itself. */
const MultiTarget_HolderRecord_t* MultiTarget_HolderFindByIndex(
  const MultiTarget_HolderTable_t* table, int32_t key);

/* Whether the table holds a row with this Index. */
bool MultiTarget_HolderContainsIndex(
  const MultiTarget_HolderTable_t* table, int32_t key);

#ifdef __cplusplus
}
#endif

#endif /* MULTI_TARGET_HOLDER_H */
