/* ------------------------------------------------------------------------------
 * Generated by Tabbit. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#include "tables/MultiTarget_Fitting.h"

#include <string.h>

static bool MultiTarget_FittingParse(MultiTarget_FittingTable_t* table, tb_reader* reader) {
  int32_t row;
  int32_t at;
  tb_column* columns = NULL;
  int32_t column_count = 0;
  tb_cursor cursor;

  if (!tb_read_table_header(reader, &table->count, &columns, &column_count))
    return false;

  if (table->count > 0) {
    table->records = (MultiTarget_FittingRecord_t*)tb_arena_alloc(
      &table->arena, (size_t)table->count * sizeof *table->records);

    if (table->records == NULL)
      return tb_fail_with(reader, "out of memory allocating the rows");

    table->by_index = (tb_index_entry*)tb_arena_alloc(
      &table->arena, (size_t)table->count * sizeof *table->by_index);

    if (table->by_index == NULL)
      return tb_fail_with(reader, "out of memory allocating the Index index");
  }

  /* Column by column, matched by tag rather than by position: a column this build has
   * no member for is skipped by its declared length, and one whose type no longer fits
   * the member stops the read naming the field. Rows arrive with every member at an
   * empty value, so one the file has nothing for keeps it. */
  for (at = 0; at < column_count && !tb_failed(reader); ++at) {
    const tb_column* column = &columns[at];
    int32_t block_end = reader->position + column->byte_length;

    switch (column->tag) {

    case 1:
      (void)tb_check_column(reader, column, "Fitting.Index", TB_KIND_SCALAR, 1, false, TB_ELEMENT_MASK(TB_ELEMENT_I32) | TB_ELEMENT_MASK(TB_ELEMENT_VARINT));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Fitting.Index");

      {
        int32_t run_length = 0;
        int32_t value = 0;

        row = 0;

        while (row < table->count && !tb_failed(reader)) {
          if (!tb_cursor_next_same_i32(&cursor, table->count - row, &run_length, &value))
            break;

          for (; run_length > 0; --run_length, ++row)
            table->records[row].index = value;
        }
      }
      break;

    case 2:
      (void)tb_check_column(reader, column, "Fitting.Main.Pick", TB_KIND_SCALAR, 1, false, TB_ELEMENT_MASK(TB_ELEMENT_I32) | TB_ELEMENT_MASK(TB_ELEMENT_VARINT));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Fitting.Main.Pick");

      {
        int32_t run_length = 0;
        int32_t value = 0;

        row = 0;

        while (row < table->count && !tb_failed(reader)) {
          if (!tb_cursor_next_same_i32(&cursor, table->count - row, &run_length, &value))
            break;

          for (; run_length > 0; --run_length, ++row)
            table->records[row].main.pick = value;
        }
      }
      break;

    case 3:
      (void)tb_check_column(reader, column, "Fitting.Main.Count", TB_KIND_SCALAR, 1, false, TB_ELEMENT_MASK(TB_ELEMENT_I32) | TB_ELEMENT_MASK(TB_ELEMENT_VARINT));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Fitting.Main.Count");

      {
        int32_t run_length = 0;
        int32_t value = 0;

        row = 0;

        while (row < table->count && !tb_failed(reader)) {
          if (!tb_cursor_next_same_i32(&cursor, table->count - row, &run_length, &value))
            break;

          for (; run_length > 0; --run_length, ++row)
            table->records[row].main.count = value;
        }
      }
      break;

    case 4:
      (void)tb_check_column(reader, column, "Fitting.Pad", TB_KIND_SCALAR, 1, false, TB_ELEMENT_MASK(TB_ELEMENT_I32) | TB_ELEMENT_MASK(TB_ELEMENT_VARINT));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Fitting.Pad");

      {
        int32_t run_length = 0;
        int32_t value = 0;

        row = 0;

        while (row < table->count && !tb_failed(reader)) {
          if (!tb_cursor_next_same_i32(&cursor, table->count - row, &run_length, &value))
            break;

          for (; run_length > 0; --run_length, ++row)
            table->records[row].pad = value;
        }
      }
      break;

    case 5:
      (void)tb_check_column(reader, column, "Fitting.Pad2", TB_KIND_SCALAR, 1, false, TB_ELEMENT_MASK(TB_ELEMENT_I32) | TB_ELEMENT_MASK(TB_ELEMENT_VARINT));

      (void)tb_cursor_init(&cursor, reader, column, table->count, "Fitting.Pad2");

      {
        int32_t run_length = 0;
        int32_t value = 0;

        row = 0;

        while (row < table->count && !tb_failed(reader)) {
          if (!tb_cursor_next_same_i32(&cursor, table->count - row, &run_length, &value))
            break;

          for (; run_length > 0; --run_length, ++row)
            table->records[row].pad2 = value;
        }
      }
      break;

    default:
      /* A column this build has no member for: added to the schema after the code
       * was generated, or removed from the code while the data still carries it.
       * The block's declared length is the whole of what skipping needs to know. */
      (void)tb_skip(reader, column->byte_length);
      break;
    }

    if (!tb_check_block_end(reader, column, block_end))
      return false;
  }

  if (tb_failed(reader))
    return false;

  /* The keys can only be gathered once every column has been read: the column that
   * carries one arrives wherever the file happens to put it. */
  for (row = 0; row < table->count; ++row) {
    table->by_index[row].key = table->records[row].index;
    table->by_index[row].position = row;
  }

  tb_index_sort(table->by_index, table->count);

  return true;
}

bool MultiTarget_FittingLoad(MultiTarget_FittingTable_t* table, const char* filename,
                   char* error, size_t error_size) {
  uint8_t* bytes = NULL;
  int32_t length = 0;
  const uint8_t* opened = NULL;
  int32_t opened_length = 0;
  tb_reader reader;
  bool ok;

  /* Loaded beside whatever the table is already holding, arena and all, and swapped in
   * only if it worked. That is what makes a reload safe: reading a patched file that
   * turns out to be truncated - or to carry a column this build cannot read - leaves the
   * rows the caller has pointers to exactly where they were.
   *
   * It also has to be this way round for the memory. The table owns its arena, and
   * zeroing the table before reading - which is what this did - dropped that arena
   * without freeing it, so every reload leaked the whole of the previous load. */
  MultiTarget_FittingTable_t loaded;

  memset(&loaded, 0, sizeof loaded);

  if (!tb_read_all_bytes(filename, &bytes, &length)) {
    tb_copy_error(error, error_size, filename, "cannot be read");
    return false;
  }

  /* Opened unconditionally, with whatever MultiTarget_EncryptionKey and
   * MultiTarget_MacKey hold - NULL unless the project set them. A file that is
   * neither encrypted nor signed comes back from this untouched, so the load path is the
   * same either way and there is no condition here that could be the wrong way round.
   * spec/tcb-mac-and-signature.md.
   *
   * What comes back is a window onto `bytes` rather than a copy of it, which is why the
   * buffer is still what tb_free_bytes is given below. */
  if (!tb_open(bytes, length, MultiTarget_EncryptionKey,
        MultiTarget_EncryptionKeyLength, MultiTarget_MacKey,
        MultiTarget_MacKeyLength, MultiTarget_VerifyMac,
        &opened, &opened_length, error, error_size)) {
    tb_free_bytes(bytes);
    return false;
  }

  tb_reader_init(&reader, opened, opened_length, &loaded.arena);

  ok = MultiTarget_FittingParse(&loaded, &reader);

  if (ok) {
    /* The previous load goes now, and not before: its arena holds the strings and
     * arrays the caller was reading up to this line. */
    MultiTarget_FittingFree(table);
    *table = loaded;
  } else {
    tb_copy_error(error, error_size, filename, tb_error(&reader));

    /* Nothing half-read is kept, and the table is untouched. */
    MultiTarget_FittingFree(&loaded);
  }

  /* The strings were copied into the arena, so the file buffer goes either way. */
  tb_free_bytes(bytes);

  return ok;
}

void MultiTarget_FittingFree(MultiTarget_FittingTable_t* table) {
  tb_arena_free(&table->arena);

  memset(table, 0, sizeof *table);
}

const MultiTarget_FittingRecord_t* MultiTarget_FittingFindByIndex(
  const MultiTarget_FittingTable_t* table, int32_t key) {
  int32_t position = tb_index_find(table->by_index, table->count, key);

  return position < 0 ? NULL : &table->records[position];
}

bool MultiTarget_FittingContainsIndex(
  const MultiTarget_FittingTable_t* table, int32_t key) {
  return tb_index_find(table->by_index, table->count, key) >= 0;
}
