<?php

// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace Tabbit\Fixtures\DocShowcase;

require_once __DIR__ . '/../tabbit/TcbReader.php';
require_once __DIR__ . '/../enums/Rarity.php';
require_once __DIR__ . '/../DocShowcaseAccessor.php';

use Tabbit\TcbReader;
use Tabbit\TcbColumnCursor;
use Tabbit\RecordNotFoundException;
use Tabbit\Uuid;

/**
 * Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Sides : B2
 *
 * Neither key column is unique alone.
 */
final class StageRewardRecord
{
    /** which stage */
    public int $stage = 0;
    /** finishing rank */
    public Rarity $rank = Rarity::None;
    /** gold paid */
    public int $gold = 0;
    /** drop table */
    public string $dropTable = '';
}

/** Every row of StageReward. */
final class StageRewardTable implements \Countable, \IteratorAggregate
{
    /** @var list<StageRewardRecord> */
    public array $records = [];

    /** How many rows the table holds. */
    public function count(): int
    {
        return count($this->records);
    }

    /**
     * The rows, in the order the file wrote them.
     *
     * The array is read once, here. A refresh replaces it rather than its contents, so a
     * loop already running keeps the rows it started with.
     *
     * @return \Traversable<int, StageRewardRecord>
     */
    public function getIterator(): \Traversable
    {
        return new \ArrayIterator($this->records);
    }

    /** @var array<string, StageRewardRecord> */
    private array $byStageAndRank = [];

    /** Joins the columns of the Stage and Rank key into the text the map is keyed by. */
    private static function keyOfStageAndRank(int $stageKey, Rarity $rankKey): string
    {
        $parts = [
            (string)(int)$stageKey,
            (string)$rankKey->value,
        ];

        $text = "";

        foreach ($parts as $part) {
            $text .= strlen($part) . ":" . $part;
        }

        return $text;
    }

    /**
     * The row with this Stage and Rank, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public function findByStageAndRank(int $stageKey, Rarity $rankKey): ?StageRewardRecord
    {
        return $this->byStageAndRank[self::keyOfStageAndRank($stageKey, $rankKey)] ?? null;
    }

    /**
     * The row with this Stage and Rank, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByStageAndRank($key)->name at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public function getByStageAndRankOrThrow(int $stageKey, Rarity $rankKey): StageRewardRecord
    {
        $record = $this->byStageAndRank[self::keyOfStageAndRank($stageKey, $rankKey)] ?? null;

        if ($record === null) {
            throw new RecordNotFoundException(
                "There is no record in table `StageReward` that corresponds to " .
                sprintf("field `Stage and Rank` value (%s, %s).", $stageKey, $rankKey));
        }

        return $record;
    }

    /** Whether the table holds a row with this Stage and Rank. */
    public function containsStageAndRank(int $stageKey, Rarity $rankKey): bool
    {
        return isset($this->byStageAndRank[self::keyOfStageAndRank($stageKey, $rankKey)]);
    }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public function read(string $filename): void
    {
        // The keys go to fromFile because reading and opening are one call here: the
        // reader's constructor takes the whole file and opens the envelope itself. It does
        // so unconditionally, and with whatever DocShowcaseAccessor::$encryptionKey and
        // DocShowcaseAccessor::$macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from that untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/wire/tcb-mac-and-signature.md.
        $reader = TcbReader::fromFile(
            $filename, DocShowcaseAccessor::$encryptionKey,
            DocShowcaseAccessor::$macKey, DocShowcaseAccessor::$verifyMac);
        [$count, $columns] = $reader->readTableHeader();

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        $records = [];
        $byStageAndRank = [];

        for ($i = 0; $i < $count; $i++) {
            $records[] = new StageRewardRecord();
        }

        foreach ($columns as $column) {
            $blockEnd = $reader->position() + $column['byteLength'];

            switch ($column['tag']) {
                case 1:
                    TcbReader::checkColumn($column, 'StageReward.Stage', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'StageReward.Stage');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->stage = $value;
                        }
                    }
                    break;

                case 2:
                    TcbReader::checkColumn($column, 'StageReward.Rank', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'StageReward.Rank');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->rank = Rarity::tryFrom($value) ?? Rarity::None;
                        }
                    }
                    break;

                case 3:
                    TcbReader::checkColumn($column, 'StageReward.Gold', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'StageReward.Gold');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->gold = $value;
                        }
                    }
                    break;

                case 4:
                    TcbReader::checkColumn($column, 'StageReward.DropTable', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'StageReward.DropTable');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameString($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->dropTable = $value;
                        }
                    }
                    break;

                default:
                    // A column added after this code was generated.
                    $reader->skip($column['byteLength']);
                    break;
            }

            $reader->checkBlockEnd($column, $blockEnd);
        }

        foreach ($records as $record) {
            $byStageAndRank[self::keyOfStageAndRank($record->stage, $record->rank)] = $record;
        }

        // Published, now that every column read.
        $this->records = $records;
        $this->byStageAndRank = $byStageAndRank;
    }
}
