// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------


// Tables
export { GuideRecord } from './tables/guide'
export { GuideTable } from './tables/guide'

export { Tables } from './tables'
