// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

use std::collections::HashMap;
use std::path::Path;
use crate::tabbit;

// Generated from test/fixtures/xlsx/nullable-elements/nullable-elements.xlsx : Arrays : J2
/// Numbered columns that fold into one array whose elements may be absent.
#[derive(Clone, Debug, Default)]
pub struct FoldedRecord {
    /// primary index
    pub index: i32,
    /// element 1 - and the group's answer
    pub tag: Vec<String>,
    /// Which of `tag`'s elements have a value. Empty where the file did not
    /// carry the column, and then every index is out of range anyway.
    pub has_tag_at: Vec<bool>,
}

impl FoldedRecord {
}

/// Every row of Folded.
#[derive(Clone, Debug, Default)]
pub struct FoldedTable {
    records: Vec<FoldedRecord>,
    by_index: HashMap<i32, usize>,
}

impl FoldedTable {
    /// Every row, in the order the sheet declared them.
    pub fn records(&self) -> &[FoldedRecord] {
        &self.records
    }

    /// The row with this Index, or None when the table has none.
    ///
    /// The lookup to reach for when a missing row is an ordinary answer - an optional
    /// reference, a key that came from user input.
    pub fn find_by_index(&self, key: i32) -> Option<&FoldedRecord> {
        self.by_index.get(&key).map(|position| &self.records[*position])
    }

    /// The row with this Index, or an error naming what was missing.
    ///
    /// For a key that has to be there - one from another table, or a constant. Rust has no
    /// exception to throw, so where the other languages name a throw this one names the
    /// error it returns.
    pub fn get_by_index_or_error(&self, key: i32) -> tabbit::Result<&FoldedRecord> {
        self.by_index
            .get(&key)
            .map(|position| &self.records[*position])
            .ok_or_else(|| tabbit::Error::RecordNotFound {
                table: "Folded",
                field: "Index",
                key: format!("{:?}", key),
            })
    }

    /// Whether the table holds a row with this Index.
    pub fn contains_index(&self, key: i32) -> bool {
        self.by_index.contains_key(&key)
    }

    /// Loads the table from a .tcb file written by Tabbit.
    pub fn read(&mut self, filename: &Path) -> tabbit::Result<()> {
        // Mutable, and it outlives the reader on purpose: opening the envelope decrypts in
        // place and hands back a borrow of these same bytes rather than a copy of them.
        let mut data = tabbit::read_all_bytes(filename)?;

        // Unconditionally, and with whatever `ENCRYPTION_KEY` and `MAC_KEY` hold - which is
        // unset unless the project set them. A file that is neither encrypted nor signed
        // comes back from this untouched, so the load path is the same either way and there
        // is no condition here that could be the wrong way round.
        // spec/tcb-mac-and-signature.md.
        let key: &[u8] = crate::ENCRYPTION_KEY.get().map(Vec::as_slice).unwrap_or(&[]);
        let mac_key: &[u8] = crate::MAC_KEY.get().map(Vec::as_slice).unwrap_or(&[]);

        let mut reader = tabbit::Reader::new(tabbit::open(
            &mut data,
            key,
            mac_key,
            crate::VERIFY_MAC.load(std::sync::atomic::Ordering::Relaxed),
        )?);

        // Column by column, matched by tag rather than position: a column this build
        // does not know is skipped by its block length, and one whose type changed
        // incompatibly fails naming the field.
        let header = tabbit::read_table_header(&mut reader)?;
        let count = header.row_count.max(0) as usize;

        // Read into rows of its own and assigned at the end. Reading a table that is
        // already loaded is a refresh, and one that turns out to be unreadable has to
        // leave the rows already there alone - `?` returns before anything is replaced.
        let mut records = vec![FoldedRecord::default(); count];

        for column in &header.columns {
            let block_end = reader.position() + column.byte_length.max(0) as usize;

            match column.tag {
                1 => {
                    tabbit::check_column(column, "Folded.Index", tabbit::KIND_SCALAR, false, &[tabbit::ELEMENT_I32, tabbit::ELEMENT_VARINT])?;
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Folded.Index")?;
                    let mut at = 0usize;
                    while at < records.len() {
                        let (n, value) = cursor.next_same_i32((records.len() - at) as i32)?;
                        for _ in 0..n {
                            records[at].index = value;
                            at += 1;
                        }
                    }
                }
                2 => {
                    tabbit::check_column_with_elements(column, "Folded.Tag", tabbit::KIND_ARRAY, false, &[tabbit::ELEMENT_STRING])?;
                    let element_presence = tabbit::read_element_presence(&mut reader, column)?;
                    let mut element_at: usize = 0;
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Folded.Tag")?;
                    for record in records.iter_mut() {
                        let element_count = cursor.next_length()?.max(0) as usize;
                        record.tag = Vec::with_capacity(element_count.min(65536));
                        record.has_tag_at =
                            Vec::with_capacity(element_count.min(65536));
                        for _ in 0..element_count {
                            record.tag.push(cursor.next_string()?);
                            record.has_tag_at
                                .push(tabbit::is_present(&element_presence, element_at));
                            element_at += 1;
                        }
                    }
                }
                _ => {
                    // A column added after this code was generated.
                    reader.skip(column.byte_length)?;
                }
            }

            tabbit::check_block_end(&reader, column, block_end)?;
        }

        let by_index = records
            .iter()
            .enumerate()
            .map(|(position, record)| (record.index.clone(), position))
            .collect();

        // Published, now that every column read.
        self.records = records;
        self.by_index = by_index;

        Ok(())
    }
}
