// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

#ifndef TABBIT_GENERATED_RECORDREFACCESSOR_MOUNT_H
#define TABBIT_GENERATED_RECORDREFACCESSOR_MOUNT_H

#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include "tabbit/tcb_reader.h"
#include "RecordRefAccessor_forward.h"

namespace record_ref {
// Generated from test/fixtures/xlsx/record-ref/record-ref.xlsx : Records : AH2
/// A record inside MountRecord::rig.
struct MountRecord_rig_entryCore {
  /// element 1, two levels in
  const ItemRecord* item_id = nullptr;
  std::int32_t item_id_index = 0;
  /// its sibling at that level
  std::int32_t count = 0;
};

/// One element of MountRecord::rig.
struct MountRecord_rig_entry {
  /// element 1, two levels in
  MountRecord_rig_entryCore core;
};

/// A reference inside a record inside a record.
struct MountRecord {
  /// primary index
  std::int32_t index = 0;
  /// element 1, two levels in
  std::vector<MountRecord_rig_entry> rig;
};

/// A reference inside a record inside a record.
class MountTable {
 public:
  const std::vector<MountRecord>& records() const { return records_; }

  /// The row with this Index, or nullptr when the table has none.
  ///
  /// The lookup to reach for when a missing row is an ordinary answer - an optional
  /// reference, a key that came from user input.
  const MountRecord* find_by_index(std::int32_t key) const {
    const auto it = by_index_.find(key);
    return it == by_index_.end() ? nullptr : &records_[it->second];
  }

  /// The row with this Index, or a thrown exception naming what was missing.
  ///
  /// For a key that has to be there - one from another table, or a constant. The name says
  /// it throws, because a caller reading `get_by_index(key)->name` at a glance
  /// cannot otherwise tell whether the next line is a null check or a catch.
  const MountRecord& get_by_index_or_throw(std::int32_t key) const {
    const MountRecord* found = find_by_index(key);

    if (found == nullptr) {
      throw tabbit::RecordNotFound(
        std::string("there is no record in table `Mount` that corresponds to "
                    "field `Index` value ") + std::to_string(key));
    }

    return *found;
  }

  /// Whether the table holds a row with this Index.
  bool contains_index(std::int32_t key) const {
    return by_index_.find(key) != by_index_.end();
  }

  /// Loads the table from a .tcb file written by Tabbit.
  void read(const std::string& filename) {
    // Not const, and it outlives the reader on purpose: opening the envelope decrypts in
    // place and hands back a window onto these same bytes rather than a copy of them.
    std::vector<std::uint8_t> buffer = tabbit::read_all_bytes(filename);

    // Unconditionally, and with whatever `encryption_key` and `mac_key` hold - which is
    // empty unless the project set them. A file that is neither encrypted nor signed comes
    // back from this untouched, so the load path is the same either way and there is no
    // condition here that could be the wrong way round. spec/tcb-mac-and-signature.md.
    const std::pair<const std::uint8_t*, std::size_t> bytes =
      tabbit::open(buffer, encryption_key, mac_key, verify_mac);

    tabbit::TcbReader reader(bytes.first, bytes.second);

    // Column by column, matched by tag rather than position: a column this build
    // does not know is skipped by its block length, and one whose type changed
    // incompatibly fails naming the field.
    const tabbit::Header header = tabbit::read_table_header(reader);
    const std::size_t row_count = static_cast<std::size_t>(header.row_count);

    // Read into storage of its own and swapped in at the end: reading a table that is
    // already loaded is a refresh, and one that throws part way through - a truncated
    // file, a column this build cannot read - has to leave the rows already there.
    std::vector<MountRecord> records;
    records.resize(row_count);

    for (const tabbit::Column& column : header.columns) {
      const std::size_t block_end = reader.position() + static_cast<std::size_t>(column.byte_length);

      switch (column.tag) {
        case 1: {
          tabbit::check_column(column, "Mount.Index", tabbit::kKindScalar, false, {tabbit::kElementI32, tabbit::kElementVarint});
          tabbit::TcbColumnCursor cursor(reader, column, header.row_count, "Mount.Index");
          std::int32_t value{};
          for (std::size_t i = 0; i < row_count; ) {
            std::int32_t n = cursor.next_same_i32(
                static_cast<std::int32_t>(row_count - i), value);
            for (; n > 0; --n, ++i) {
              records[i].index = value;
            }
          }
          break;
        }
        case 2: {
          tabbit::check_column(column, "Mount.Rig.Core.ItemId", tabbit::kKindArray, false, {tabbit::kElementI32});
          tabbit::TcbColumnCursor cursor(reader, column, header.row_count, "Mount.Rig.Core.ItemId");
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            const std::int32_t element_count = cursor.next_length();
            record.rig.assign(static_cast<std::size_t>(element_count), MountRecord_rig_entry());
            for (std::int32_t j = 0; j < element_count; ++j) {
              record.rig[static_cast<std::size_t>(j)].core.item_id_index = cursor.next_i32();
            }
          }
          break;
        }
        case 3: {
          tabbit::check_column(column, "Mount.Rig.Core.Count", tabbit::kKindArray, false, {tabbit::kElementI32, tabbit::kElementVarint});
          tabbit::TcbColumnCursor cursor(reader, column, header.row_count, "Mount.Rig.Core.Count");
          for (std::size_t i = 0; i < row_count; ++i) {
            auto& record = records[i];
            const std::int32_t element_count = cursor.next_length();
            if (record.rig.size() != static_cast<std::size_t>(element_count)) {
              throw tabbit::TcbError(
                  "Mount.rig: the file gives this row a different "
                  "element count for one member of the record than for another; every member of a "
                  "record carries the same count, so the file is damaged");
            }
            for (std::int32_t j = 0; j < element_count; ++j) {
              record.rig[static_cast<std::size_t>(j)].core.count = cursor.next_i32();
            }
          }
          break;
        }
        default:
          // A column added after this code was generated.
          reader.skip(column.byte_length);
          break;
      }

      tabbit::check_block_end(reader, column, block_end);
    }

    publish(std::move(records));
  }

 private:
  friend class RecordRefAccessor;

  /// One whole load, in place of the previous one.
  ///
  /// The indexes are built here rather than by the caller, because they have to arrive
  /// with the rows: a table holding this load's rows and the last one's index would
  /// answer a lookup with a row that is no longer at that position.
  void publish(std::vector<MountRecord>&& records) {
    std::unordered_map<std::int32_t, std::size_t> index_map;
    index_map.reserve(records.size());
    for (std::size_t i = 0; i < records.size(); ++i) {
      index_map.emplace(records[i].index, i);
    }

    records_ = std::move(records);
    by_index_ = std::move(index_map);
  }

  std::vector<MountRecord> records_;
  std::unordered_map<std::int32_t, std::size_t> by_index_;
};

}  // namespace record_ref

#endif  // TABBIT_GENERATED_RECORDREFACCESSOR_MOUNT_H
