<?php

// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace Tabbit\Fixtures\RecordTrim;

require_once __DIR__ . '/../tabbit/TcbReader.php';
require_once __DIR__ . '/../RecordTrimAccessor.php';

use Tabbit\TcbReader;
use Tabbit\TcbColumnCursor;
use Tabbit\RecordNotFoundException;
use Tabbit\Uuid;

/** One element of LootRecord::$slot. */
final class LootSlotEntry
{
    /** element 1 */
    public int $id = 0;
    /** element 1 */
    public int $count = 0;
    /** element 1 - a string, so the element factory has to fill it */
    public string $label = '';
}

/** One element of LootRecord::$pos. */
final class LootPosEntry
{
    /** single record, not an array */
    public int $x = 0;
    /** second member of it */
    public int $y = 0;
}

/**
 * Generated from test/fixtures/xlsx/record-trim/record-trim.xlsx : Trim : B2
 *
 * A record array trimmed at the last element the row filled in.
 */
final class LootRecord
{
    /** primary index */
    public int $index = 0;
    /** plain column, must not move */
    public string $name = '';
    /** element 1 */
    /** @var list<LootSlotEntry> */
    public array $slot = [];
    /** single record, not an array */
    public LootPosEntry $pos;
    /** scalar serial array, element 1 - required, so the array is never empty */
    /** @var list<string> */
    public array $tag = [];


    /**
     * A row with its record groups built.
     *
     * They cannot be built at the declaration: a PHP property initializer has to be a
     * constant expression, and `new SlotEntry()` is not one.
     */
    public function __construct()
    {
        $this->pos = new LootPosEntry();
    }
}

/** Every row of Loot. */
final class LootTable implements \Countable, \IteratorAggregate, \ArrayAccess
{
    /** @var list<LootRecord> */
    public array $records = [];

    /** How many rows the table holds. */
    public function count(): int
    {
        return count($this->records);
    }

    /**
     * The rows, in the order the file wrote them.
     *
     * The array is read once, here. A refresh replaces it rather than its contents, so a
     * loop already running keeps the rows it started with.
     *
     * @return \Traversable<int, LootRecord>
     */
    public function getIterator(): \Traversable
    {
        return new \ArrayIterator($this->records);
    }

    /** @var array<int, LootRecord> */
    private array $byIndex = [];

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public function findByIndex(int $key): ?LootRecord
    {
        return $this->byIndex[$key] ?? null;
    }

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex($key)->name at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public function getByIndexOrThrow(int $key): LootRecord
    {
        $record = $this->byIndex[$key] ?? null;

        if ($record === null) {
            throw new RecordNotFoundException(
                "There is no record in table `Loot` that corresponds to " .
                "field `Index` value " . $key . ".");
        }

        return $record;
    }

    /** Whether the table holds a row with this Index. */
    public function containsIndex(int $key): bool
    {
        return isset($this->byIndex[$key]);
    }


    /**
     * Whether the table holds a row with this Index - `isset($table[$key])`.
     */
    public function offsetExists(mixed $offset): bool
    {
        return $this->containsIndex($offset);
    }

    /**
     * The row with this Index, or null when the table has none.
     *
     * findByIndex under the spelling PHP uses for a keyed collection. It
     * answers with null because that is what array access does here; a language whose own
     * map throws generates a subscript that throws.
     * spec/targets/table-collection-surface.md section 5.7.
     *
     * This is the key, not the row's position. `$table[0]` is the row whose
     * Index is 0, not the first row - the rows in order are ->records.
     *
     * Only a key of one column has this: PHP's array access takes one offset.
     */
    public function offsetGet(mixed $offset): ?LootRecord
    {
        return $this->findByIndex($offset);
    }

    /** The table is read-only: a row comes from the file, not from an assignment. */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        throw new \LogicException('LootTable is read-only.');
    }

    /** The table is read-only: a row comes from the file, not from an assignment. */
    public function offsetUnset(mixed $offset): void
    {
        throw new \LogicException('LootTable is read-only.');
    }


    /**
     * Each row with the Index it is keyed by -
     * `foreach ($table->entries() as $key => $row)`.
     *
     * What this saves a caller is not the key value - the row carries it - but having to
     * know which column the key is: Index here, something else in the next
     * table.
     *
     * The rows come in the order the file wrote them rather than the order the map holds
     * them, which makes this and iterating the table agree. Only the primary key has this:
     * a table keyed by several columns together has no single key value to pair a row with.
     *
     * @return \Generator<int, LootRecord>
     */
    public function entries(): \Generator
    {
        foreach ($this->records as $record) {
            yield $record->index => $record;
        }
    }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public function read(string $filename): void
    {
        // The keys go to fromFile because reading and opening are one call here: the
        // reader's constructor takes the whole file and opens the envelope itself. It does
        // so unconditionally, and with whatever RecordTrimAccessor::$encryptionKey and
        // RecordTrimAccessor::$macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from that untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/wire/tcb-mac-and-signature.md.
        $reader = TcbReader::fromFile(
            $filename, RecordTrimAccessor::$encryptionKey,
            RecordTrimAccessor::$macKey, RecordTrimAccessor::$verifyMac);
        [$count, $columns] = $reader->readTableHeader();

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        $records = [];
        $byIndex = [];

        for ($i = 0; $i < $count; $i++) {
            $records[] = new LootRecord();
        }

        foreach ($columns as $column) {
            $blockEnd = $reader->position() + $column['byteLength'];

            switch ($column['tag']) {
                case 1:
                    TcbReader::checkColumn($column, 'Loot.Index', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Index');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->index = $value;
                        }
                    }
                    break;

                case 2:
                    TcbReader::checkColumn($column, 'Loot.Name', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Name');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameString($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->name = $value;
                        }
                    }
                    break;

                case 3:
                    TcbReader::checkColumn($column, 'Loot.Slot.Id', TcbReader::KIND_ARRAY, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Slot.Id');
                    foreach ($records as $record) {
                        $elementCount = $cursor->nextLength();
                        // The first member builds the list; the rest check. Building it
                        // again would discard what the members before it wrote, and taking
                        // the shorter of two counts would shift every value after it.
                        $record->slot = [];
                        for ($j = 0; $j < $elementCount; $j++) {
                            $record->slot[] = new LootSlotEntry();
                        }
                        for ($j = 0; $j < $elementCount; $j++) {
                            $record->slot[$j]->id = $cursor->nextI32();
                        }
                    }
                    break;

                case 4:
                    TcbReader::checkColumn($column, 'Loot.Slot.Count', TcbReader::KIND_ARRAY, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Slot.Count');
                    foreach ($records as $record) {
                        $elementCount = $cursor->nextLength();
                        if (\count($record->slot) !== $elementCount) {
                            throw new \Tabbit\TcbException(
                                'Loot.slot: the file gives one member of '
                                . 'this record a different element count than another.');
                        }
                        for ($j = 0; $j < $elementCount; $j++) {
                            $record->slot[$j]->count = $cursor->nextI32();
                        }
                    }
                    break;

                case 5:
                    TcbReader::checkColumn($column, 'Loot.Slot.Label', TcbReader::KIND_ARRAY, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Slot.Label');
                    foreach ($records as $record) {
                        $elementCount = $cursor->nextLength();
                        if (\count($record->slot) !== $elementCount) {
                            throw new \Tabbit\TcbException(
                                'Loot.slot: the file gives one member of '
                                . 'this record a different element count than another.');
                        }
                        for ($j = 0; $j < $elementCount; $j++) {
                            $record->slot[$j]->label = $cursor->nextString();
                        }
                    }
                    break;

                case 6:
                    TcbReader::checkColumn($column, 'Loot.Pos.X', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Pos.X');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->pos->x = $value;
                        }
                    }
                    break;

                case 7:
                    TcbReader::checkColumn($column, 'Loot.Pos.Y', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Pos.Y');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->pos->y = $value;
                        }
                    }
                    break;

                case 8:
                    TcbReader::checkColumn($column, 'Loot.Tag', TcbReader::KIND_ARRAY, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loot.Tag');
                    foreach ($records as $record) {
                        $elementCount = $cursor->nextLength();
                        $record->tag = [];
                        for ($j = 0; $j < $elementCount; $j++) {
                            $record->tag[] = $cursor->nextString();
                        }
                    }
                    break;

                default:
                    // A column added after this code was generated.
                    $reader->skip($column['byteLength']);
                    break;
            }

            $reader->checkBlockEnd($column, $blockEnd);
        }

        foreach ($records as $record) {
            $byIndex[$record->index] = $record;
        }

        // Published, now that every column read.
        $this->records = $records;
        $this->byIndex = $byIndex;
    }
}
