# ------------------------------------------------------------------------------
# Generated by Tabbit. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

require_relative '../tabbit/tcb_reader'

require_relative '../structs/effect'


module GameData
  # One element of SkillRecord#effect.
  class SkillEffectEntry
    attr_accessor :type, :chance, :damage, :pierces, :element_id, :element_by_element_id, :amount, :band

    def initialize
      @type = 0
      @chance = 0
      @damage = 0
      @pierces = false
      @element_id = 0
      @element_by_element_id = nil
      @amount = 0
      @band = 0
    end
  end

  # Generated from test/fixtures/xlsx/polymorphism/polymorphism.xlsx : Polymorphism : F2
  # Skills whose effect is one of several shapes.
  class SkillRecord
    attr_accessor :index, :name, :effect

    def initialize
      @index = 0
      @name = ''
      @effect = SkillEffectEntry.new


    # What this row's Effect is. Narrow it with +is_a?+.
    def effect_of
      built = @effect_value
      return built unless built.nil?

      built = effect_element(effect)

      @effect_value = built
      built
    end

    # Builds one value from the entry the read filled.
    def effect_element(entry)
      case entry.type
      when 1
        built = DamageEffect.new
        built.chance = entry.chance
        built.damage = entry.damage
        built.pierces = entry.pierces
        built.element_id = entry.element_id
        built.element_by_element_id = entry.element_by_element_id
      when 2
        built = HealEffect.new
        built.chance = entry.chance
        built.amount = entry.amount
        built.band = entry.band
      when 3
        built = NoEffect.new
        built.chance = entry.chance
      else
        raise TcbError,
              "Effect: no variant is numbered "               "#{ entry.type }"
      end

      built
    end
    end

  end

  # Every row of Skill.
  class SkillTable
    attr_accessor :records

    def initialize
      @records = []
      @by_index = {}
    end

    # The row with this Index, or nil when the table has none.
    #
    # The lookup to reach for when a missing row is an ordinary answer - an optional
    # reference, a key that came from user input.
    def find_by_index(key)
      @by_index[key]
    end

    # The row with this Index, or a raised error naming what was missing.
    #
    # For a key that has to be there - one from another table, or a constant. The name
    # says it raises, because a caller reading `get_by_index(key).name` at a
    # glance cannot otherwise tell whether the next line is a check or a rescue.
    def get_by_index_or_throw(key)
      record = @by_index[key]

      if record.nil?
        raise Tabbit::RecordNotFoundError,
              "there is no record in table `Skill` that corresponds to " \
              "field `Index` value #{key.inspect}"
      end

      record
    end

    # Whether the table holds a row with this Index.
    def contains_index?(key)
      @by_index.key?(key)
    end

    # Loads the table from a .tcb file written by Tabbit.
    # Column by column, matched by tag rather than position: a column this build does
    # not know is skipped by its block length, and one whose type changed incompatibly
    # fails naming the field.
    def read(filename)
      # Opened unconditionally, and with whatever Tables.encryption_key and Tables.mac_key
      # hold - which is nil unless the project set them. A file that is neither encrypted
      # nor signed comes back from this untouched, so the load path is the same either way
      # and there is no condition here that could be the wrong way round.
      # spec/tcb-mac-and-signature.md.
      reader = Tabbit::Reader.new(
        Tabbit.open(Tabbit.read_all_bytes(filename), Tables.encryption_key,
                      Tables.mac_key, verify_mac: Tables.verify_mac)
      )
      count, columns = Tabbit.read_table_header(reader)

      # Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
      records = Array.new(count) { SkillRecord.new }

      columns.each do |column|
        block_end = reader.position + column.byte_length

        case column.tag
        when 1
          Tabbit.check_column(column, 'Skill.Index', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Index')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].index = value
            end
            at += n
          end
        when 2
          Tabbit.check_column(column, 'Skill.Name', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_STRING])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Name')
          at = 0
          while at < count
            n, value = cursor.next_same_string(count - at)
            (at...(at + n)).each do |i|
              records[i].name = value
            end
            at += n
          end
        when 3
          Tabbit.check_column(column, 'Skill.Effect.Type', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Effect.Type')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].effect.type = value
            end
            at += n
          end
        when 4
          Tabbit.check_column(column, 'Skill.Effect.Chance', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Effect.Chance')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].effect.chance = value
            end
            at += n
          end
        when 5
          Tabbit.check_column(column, 'Skill.Effect.Damage', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Effect.Damage')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].effect.damage = value
            end
            at += n
          end
        when 6
          Tabbit.check_column(column, 'Skill.Effect.Pierces', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_BOOL])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Effect.Pierces')
          records.each do |record|
            record.effect.pierces = cursor.next_bool
          end
        when 7
          Tabbit.check_column(column, 'Skill.Effect.ElementId', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Effect.ElementId')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].effect.element_id = value
            end
            at += n
          end
        when 8
          Tabbit.check_column(column, 'Skill.Effect.Amount', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Effect.Amount')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].effect.amount = value
            end
            at += n
          end
        when 9
          Tabbit.check_column(column, 'Skill.Effect.Band', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Skill.Effect.Band')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].effect.band = value
            end
            at += n
          end
        else
          # A column added after this code was generated.
          reader.skip(column.byte_length)
        end

        Tabbit.check_block_end(reader, column, block_end)
      end

      by_index = records.to_h { |record| [record.index, record] }

      # Published, now that every column read.
      @records = records
      @by_index = by_index
    end
  end
end
