// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

import * as fs from 'fs'
import * as tabbit from '../tabbit/tcb-reader'

// The accessor, for the encryption key it holds. `tables` imports this module back, and
// that cycle is only ever read from inside a method - by which point both modules have
// finished evaluating - so neither one is half built when the binding is used.
import { Tables } from '../tables'

// Automatically import to handle external type references.
import { Affinity } from '../enums/affinity'
import { ElementChartColumnTable } from './element-chart-column'

/** A type for handling rows when parsing .json. */
interface IDataRow {
  attacker: Affinity
  rate: number[]
}

// Generated from test/fixtures/xlsx/matrix/matrix.xlsx : Grids : B11
/** How much an element does to another. */
export class ElementChartRecord {
  /** Default constructor */
  constructor() {
  }

  public get attacker(): Affinity { return this._attacker }

  public get rate(): number[] { return this._rate }

  public _attacker: Affinity = 0 as Affinity
  public _rate: number[] = []

  /** Populate field values. */
  public populateFieldValues(dataRow: IDataRow): void {
    this._attacker = dataRow.attacker
    this._rate = dataRow.rate.map(v => Math.fround(v))
  }

  /** Populate field values. */
  public populateFieldValuesCompact(dataRow: any[]): void {
    let offset = 0
    this._attacker = dataRow[offset++]
    this._rate = dataRow.slice(offset, offset + 3).map(v => Math.fround(v))
    offset += 3
  }
}

// Generated from test/fixtures/xlsx/matrix/matrix.xlsx : Grids : B11
/** How much an element does to another. */
export class ElementChartTable {
  /** Default constructor. */
  constructor() {
  }

  /** All records. */
  public get records(): ElementChartRecord[] { return this._records }
  private _records: ElementChartRecord[] = []

  /** How many rows the table holds. */
  public get count(): number { return this._records.length }

  /**
   * The rows, in the order the file wrote them.
   *
   * The array reference is read once, here. A refresh replaces the reference rather
   * than its contents, so a loop already running keeps the rows it started with.
   */
  public [Symbol.iterator](): IterableIterator<ElementChartRecord> {
    return this._records[Symbol.iterator]()
  }

  // Indexing by 'attacker'
  public get recordsByAttacker(): Map<Affinity, ElementChartRecord> { return this._recordsByAttacker }
  private _recordsByAttacker: Map<Affinity, ElementChartRecord> = new Map<Affinity, ElementChartRecord>()

  /**
   * The row with this attacker, or undefined when the table has none.
   *
   * The lookup to reach for when a missing row is an ordinary answer.
   */
  public findByAttacker(key: Affinity): ElementChartRecord | undefined {
    return this._recordsByAttacker.get(key)
  }

  /**
   * The row with this attacker, or a thrown Error naming what was missing.
   *
   * For a key that has to be there. The name says it throws, because a caller reading
   * `getByAttacker(id).name` at a glance cannot otherwise tell whether the
   * next line is a check or a catch.
   */
  public getByAttackerOrThrow(key: Affinity): ElementChartRecord {
    const found = this._recordsByAttacker.get(key)
    if (!found)
      throw new Error(`There is no record in table "ElementChart" that corresponds to field "attacker" value ${key}`)

    return found
  }

  /** Whether the table holds a row with this attacker. */
  public containsAttacker(key: Affinity): boolean {
    return this._recordsByAttacker.has(key)
  }


  /**
   * Each row with the attacker it is keyed by -
   * `for (const [key, row] of table.entries())`.
   *
   * What this saves a caller is not the key value - the row carries it - but having to know
   * which column the key is: attacker here, something else in the next table.
   *
   * The rows come in the order the file wrote them rather than the order the map holds
   * them, which makes this and iterating the table agree. Only the primary key has this: a
   * table keyed by several columns together has no single key value to pair a row with.
   */
  public *entries(): IterableIterator<[Affinity, ElementChartRecord]> {
    for (const record of this._records) {
      yield [record.attacker, record]
    }
  }

  // Grid of 'attacker' by 'defender'
  private _columnAxis: ElementChartColumnTable | undefined = undefined

  /**
   * Hands this table the column axis its cells are positioned by.
   *
   * Called by the accessor once both files are read, and the length check is here rather than
   * in the read. A grid is two files, either can be deployed without the other, and a row
   * whose array is a different length from the axis is a row whose cells have moved.
   */
  public linkColumnAxis(columns: ElementChartColumnTable): void {
    for (const record of this._records) {
      if (record.rate.length !== columns.records.length) {
        throw new Error(
          `Table \`ElementChart\` holds ${record.rate.length} cells for \`${record.attacker}\` ` +
          `and its column axis \`ElementChartColumn\` holds ${columns.records.length} keys. ` +
          `The two files are from different builds.`)
      }
    }

    this._columnAxis = columns
  }

  /** The row axis keys, in the order the file wrote them. */
  public get rowKeys(): Affinity[] {
    return this._records.map(record => record.attacker)
  }

  /** The column axis keys, in the order a row holds its cells. */
  public get colKeys(): Affinity[] {
    return this._columnAxis === undefined
      ? []
      : this._columnAxis.records.map(record => record.defender)
  }

  /**
   * One row of cells, or undefined when the grid has no such row.
   *
   * In the order `colKeys` is in, which is what makes a position mean something.
   */
  public row(attacker: Affinity): number[] | undefined {
    return this.findByAttacker(attacker)?.rate
  }

  /**
   * The cell where the two keys meet, or a thrown Error naming the one that missed.
   *
   * It throws rather than answering with the type's empty value, because a grid's empty value
   * is one the sheet can write - `0` in a modifier table is a modifier of zero.
   */
  public at(attacker: Affinity, defender: Affinity): number {
    return this.cellAt(attacker, defender).cell
  }


  /** Both lookups, done once for the readers above. */
  private cellAt(attacker: Affinity, defender: Affinity): { record: ElementChartRecord, at: number, cell: number } {
    if (this._columnAxis === undefined) {
      throw new Error(`Table \`ElementChart\` has no column axis yet. Read \`ElementChartColumn\` before reading a cell.`)
    }

    const record = this.findByAttacker(attacker)

    if (record === undefined) {
      throw new Error(`Table \`ElementChart\` has no row \`${attacker}\`.`)
    }

    const column = this._columnAxis.findByDefender(defender)

    if (column === undefined) {
      throw new Error(`Table \`ElementChart\` has no column \`${defender}\`.`)
    }

    return { record, at: column.at, cell: record.rate[column.at] }
  }

  /** Read a table from specified file. */
  public async read(filename: string): Promise<void> {
    const json = await fs.promises.readFile(filename, "utf8")
    this.readFromJson(json)
  }

  /** Read a table from specified file synchronously. */
  public readSync(filename: string): void {
    const json = fs.readFileSync(filename, "utf8")
    this.readFromJson(json)
  }

  private readFromJson(json: string): void {
    const dataRows: any[] = JSON.parse(json)
    const records: ElementChartRecord[] = []

    if (this.isCompactRowFormatted(dataRows)) {
      for (const dataRow of dataRows) {
        const record = new ElementChartRecord()
        record.populateFieldValuesCompact(dataRow)
        records.push(record)
      }
    } else {
      for (const dataRow of dataRows as IDataRow[]) {
        const record = new ElementChartRecord()
        record.populateFieldValues(dataRow)
        records.push(record)
      }
    }

    this.publish(records)
  }

  private isCompactRowFormatted(rows: any[]): boolean {
    return rows.length > 0 && Array.isArray(rows[0])
  }

  /** Read a table from a binary .tcb file. */
  public readBinarySync(filename: string): void {
    // Unconditionally, and with whatever `Tables.encryptionKey` and `Tables.macKey` hold -
    // which is null unless the project set them. A file that is neither encrypted nor signed
    // comes back from this untouched, so the load path is the same either way and there is
    // no condition here that could be the wrong way round. spec/wire/tcb-mac-and-signature.md.
    this.readBinaryFrom(tabbit.open(
      tabbit.readAllBytes(filename),
      Tables.encryptionKey, Tables.macKey, Tables.verifyMac))
  }

  /**
   * Read a table from binary data already in memory.
   *
   * Column by column, matched by tag rather than position: a column this build does not
   * know is skipped by its block length, and one whose type changed incompatibly fails
   * naming the field.
   */
  public readBinaryFrom(data: Uint8Array): void {
    const reader = new tabbit.TcbReader(data)
    const { rowCount, columns } = tabbit.readTableHeader(reader)
    let cursor: tabbit.TcbColumnCursor

    // Built here and published at the end, so a file that turns out to be truncated - or
    // a column this build cannot read - leaves the rows already loaded exactly as they are.
    const records: ElementChartRecord[] = []
    for (let i = 0; i < rowCount; ++i)
      records.push(new ElementChartRecord())

    for (const column of columns) {
      const blockEnd = reader.position + column.byteLength

      switch (column.tag) {
        case 1:
          tabbit.checkColumn(column, 'ElementChart.Attacker', tabbit.KIND_SCALAR, false, [tabbit.ELEMENT_VARINT])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'ElementChart.Attacker')
          for (let i = 0; i < rowCount; ) {
            const { n, value } = cursor.nextSameI32(rowCount - i)
            for (let left = n; left > 0; --left, ++i)
              records[i]._attacker = value as Affinity
          }
          break
        case 2:
          tabbit.checkColumn(column, 'ElementChart.Rate', tabbit.KIND_ARRAY, false, [tabbit.ELEMENT_F32])
          cursor = new tabbit.TcbColumnCursor(reader, column, rowCount, 'ElementChart.Rate')
          for (let i = 0; i < rowCount; ++i) {
            const record = records[i]
            const elementCount = cursor.nextLength()
            record._rate = []
            for (let j = 0; j < elementCount; ++j) {
              record._rate.push(cursor.nextF32())
            }
          }
          break
        default:
          // A column added after this code was generated.
          reader.skip(column.byteLength)
          break
      }

      tabbit.checkBlockEnd(reader, column, blockEnd)
    }

    this.publish(records)
  }

  /** Index mapping. */
  /**
   * Publishes one whole load: the rows and the lookups built from them, together.
   *
   * Reading a table that is already loaded - a refresh, a patched file - used to mutate what
   * consumers were holding: the rows were appended to or emptied first, so a read that threw
   * partway left the table holding some of the new data and none of the old. Everything above
   * builds its own arrays and gets here only if it finished, and this replaces the references
   * in one step. Whoever took `records` before still has the previous load, whole.
   */
  private publish(records: ElementChartRecord[]): void {
    const recordsByAttacker = new Map<Affinity, ElementChartRecord>()

    for (const record of records) {
      recordsByAttacker.set(record.attacker, record)
    }

    this._records = records
    this._recordsByAttacker = recordsByAttacker
  }
}
