// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections.Generic;
using System.Threading.Tasks;

// Tabbit's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using Tabbit.Binary;

namespace Tabbit.Fixtures.RecordRef
{
    /// <summary>
    /// A record member pointing at a table keyed by a string.
    /// </summary>
    [System.Serializable]
    public partial class PoseTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Values
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;

            /// <summary>
            /// element 1, a string key
            /// </summary>
            public StepEntry[] Step => _step;
            internal const int Step_N = 2;
            #endregion

            /// <summary>One element of <see cref="Step"/>.</summary>
            [System.Serializable]
            public struct StepEntry
            {
                /// element 1, a string key
                public ClipTable.Record ClipId;
                public string ClipId_index;
                public bool ClipId_F;
                /// element 1, an ordinary member
                public int Weight;

                public override string ToString()
                {
                    var sb = new StringBuilder("{");
                    sb.Append("\"ClipId\":"); ToStringHelper.ToString(ClipId, sb);
                    sb.Append(",\"Weight\":"); ToStringHelper.ToString(Weight, sb);
                    sb.Append("}");
                    return sb.ToString();
                }
            }

            #region Storage
            internal int _index;
            internal StepEntry[] _step = new StepEntry[Step_N];
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Step\":"); ToStringHelper.ToString(Step, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Step" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Step });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        /// <remarks>
        /// The list a read publishes, not one a read fills. Whoever holds this reference holds
        /// the rows as they were when they took it, and a refresh underneath them replaces the
        /// reference rather than the contents - so an iteration in progress neither tears nor
        /// throws, and a read that fails leaves the previous rows exactly where they were.
        /// </remarks>
        public List<Record> Records => _records;
        private List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// The row with this `Index`, or null when the table has none.
        /// </summary>
        /// <remarks>
        /// The lookup to reach for when a missing row is an ordinary answer - an optional
        /// reference, a key that came from user input. Every language Tabbit generates has
        /// this one under the same name.
        /// </remarks>
        public Record FindByIndex(int key)
            => _recordsByIndex.TryGetValue(key, out Record record) ? record : null;

        /// <summary>
        /// The row with this `Index`, or a thrown exception naming what was
        /// missing.
        /// </summary>
        /// <remarks>
        /// For a key that has to be there - one from another table, or a constant. The name
        /// says it throws, because a caller reading `GetByIndex(id).Name` at
        /// a glance cannot otherwise tell whether the next line is a null check or a catch.
        /// </remarks>
        public Record GetByIndexOrThrow(int key)
        {
            if (!_recordsByIndex.TryGetValue(key, out Record record))
                throw new TabbitException($"There is no record in table `Pose` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>Whether the table holds a row with this `Index`.</summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await RecordRefAccessor.ReadAllBytesAsync(filename);

            // Unconditionally, and with whatever `RecordRefAccessor.EncryptionKey` and `RecordRefAccessor.MacKey`
            // hold - which is null unless the project set them. A file that is neither
            // encrypted nor signed comes back from this untouched, so the load path is the
            // same either way and there is no condition here that could be the wrong way
            // round. spec/tcb-mac-and-signature.md.
            var reader = new TcbReader(TcbTable.Open(
                bytes, RecordRefAccessor.EncryptionKey, RecordRefAccessor.MacKey, RecordRefAccessor.VerifyMac));

            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(TcbReader reader)
        {
            var columns = TcbTable.ReadHeader(reader, out int count);
            TcbColumnCursor cursor;

            // Read into storage of its own and published at the end, which is what makes a
            // refresh atomic: nothing here touches what the table is currently holding, so a
            // file that turns out to be truncated - or a column this build cannot read -
            // leaves the previous rows in place and reports why.
            //
            // Sized once. The row count was checked against what the columns declare before
            // this point, so it is a number the file could actually hold rows for - and a
            // list that grows into twenty thousand rows reallocates fifteen times to get
            // there, copying everything each time.
            var records = new List<Record>(count);

            for (int i = 0; i < count; i++)
                records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        TcbTable.CheckColumn(column, "Pose.Index", TcbTable.KindScalar, 1, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Pose.Index");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameI32(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._index = value;
                            } while (--n > 0);
                        }
                        break;

                    case 2:
                        TcbTable.CheckColumn(column, "Pose.Step.ClipId", TcbTable.KindFixedArray, 2, false, TcbTable.ElementString);
                        cursor = new TcbColumnCursor(reader, column, count, "Pose.Step.ClipId");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            for (int j = 0; j < Record.Step_N; ++j)
                            {
                                record._step[j].ClipId_index = cursor.NextString();
                                record._step[j].ClipId = default(ClipTable.Record); // will be assigned.
                                record._step[j].ClipId_F = false;
                            }
                        }
                        break;

                    case 3:
                        TcbTable.CheckColumn(column, "Pose.Step.Weight", TcbTable.KindFixedArray, 2, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Pose.Step.Weight");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            for (int j = 0; j < Record.Step_N; ++j)
                            {
                                record._step[j].Weight = cursor.NextI32();
                            }
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                TcbTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping. Sized to the rows, so nothing rehashes on the way in, and a
            // duplicate key throws here - before any of this is visible.
            var recordsByIndex = new Dictionary<int, Record>(count);
            foreach (var record in records)
                recordsByIndex.Add(record.Index, record);

            // Published. Everything above succeeded, and the barrier is what keeps the writes
            // that built these from being seen after the references to them - a reader on
            // another thread gets the whole table or the previous one, never half of either.
            System.Threading.Thread.MemoryBarrier();

            _records = records;
            _recordsByIndex = recordsByIndex;

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }
} // namespace Tabbit.Fixtures.RecordRef
