// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package tabbit.fixtures.matrix;

import tabbit.TcbReader;

// Generated from test/fixtures/xlsx/matrix/matrix.xlsx : Grids : B11
/** How much an element does to another. */
public final class ElementChartRecord {
    public Affinity attacker = Affinity.of(0);
    public float[] rate = new float[0];

}
