// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package tabbit.fixtures.matrix;

import tabbit.TcbReader;

// Generated from test/fixtures/xlsx/matrix/matrix.xlsx : Grids : B2
/** Price modifier by town and goods. */
public final class TownPriceColumnRecord {
    public int goods;
    public GoodsRecord goodsByGoods;
    public int at;

}
