# ------------------------------------------------------------------------------
# Generated by Tabbit. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------


module X
  # Generated from test/fixtures/xlsx/reserved-words/reserved-words.xlsx : ReservedWords : O2
  # Labels that collide with a keyword somewhere.
  module Keyword
    # unset
    NONE = 0
    # Self is a Rust keyword, and the one that is PascalCase
    SELF = 1
    # package is a Java keyword and reserved in strict-mode JavaScript
    PACKAGE = 2
    # type is a keyword in Rust and TypeScript
    TYPE = 3

    # Every declared label, by value.
    NAMES = {
      0 => :none,
      1 => :self_,
      2 => :package,
      3 => :type,
    }.freeze

    # The label's name, or nil when the sheet declared no such value.
    def self.name_of(value)
      NAMES[value]
    end
  end
end
