// ------------------------------------------------------------------------------
// Code generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package keytypes

import (
	"fmt"
	"iter"

	"keytypes/tabbit"
)

// AssetRecord was generated from test/fixtures/xlsx/key-types/key-types.xlsx : Asset : B2.
// Keyed by a uuid, which is what a pipeline that mints ids hands over.
type AssetRecord struct {
	// primary index, a uuid
	Index tabbit.UUID
	// anything
	Path string
	// secondary index, an enum label
	Slot Slot
}

// AssetTable holds every row of Asset.
type AssetTable struct {
	records []AssetRecord
	byIndex map[tabbit.UUID]int
	bySlot map[Slot]int
}

// Records returns every row, in the order the sheet declared them.
func (t *AssetTable) Records() []AssetRecord { return t.records }

// Count returns how many rows the table holds.
func (t *AssetTable) Count() int { return len(t.records) }


// All returns the rows, in the order the file wrote them - `for row := range t.All()`.
//
// The slice header is read once, here. A refresh replaces it rather than its contents, so a
// loop already running keeps the rows it started with.
func (t *AssetTable) All() iter.Seq[*AssetRecord] {
	records := t.records

	return func(yield func(*AssetRecord) bool) {
		for i := range records {
			if !yield(&records[i]) {
				return
			}
		}
	}
}

// FindByIndex returns the row with this Index, or nil when the table has none.
//
// The lookup to reach for when a missing row is an ordinary answer - an optional
// reference, a key that came from user input.
func (t *AssetTable) FindByIndex(key tabbit.UUID) *AssetRecord {
	position, found := t.byIndex[key]
	if !found {
		return nil
	}

	return &t.records[position]
}

// GetByIndexOrError returns the row with this Index, or an error naming
// what was missing.
//
// For a key that has to be there - one from another table, or a constant. Go has no
// exception to throw, so where the other languages name a throw this one names the error
// it returns; either way the call site can tell without going to the definition.
func (t *AssetTable) GetByIndexOrError(key tabbit.UUID) (*AssetRecord, error) {
	position, found := t.byIndex[key]
	if !found {
		return nil, fmt.Errorf(
			"there is no record in table `Asset` that corresponds to field `Index` value %v", key)
	}

	return &t.records[position], nil
}

// ContainsIndex reports whether the table holds a row with this Index.
func (t *AssetTable) ContainsIndex(key tabbit.UUID) bool {
	_, found := t.byIndex[key]
	return found
}


// Entries yields each row with the Index it is keyed by -
// `for key, row := range t.Entries()`.
//
// What this saves a caller is not the key value - the row carries it - but having to know
// which column the key is: Index here, something else in the next table.
//
// The rows come in the order the file wrote them rather than the order a map happens to
// hold them, which makes this and All agree. Only the primary key has this: a table keyed
// by several columns together has no single key value to pair a row with.
func (t *AssetTable) Entries() iter.Seq2[tabbit.UUID, *AssetRecord] {
	records := t.records

	return func(yield func(tabbit.UUID, *AssetRecord) bool) {
		for i := range records {
			if !yield(records[i].Index, &records[i]) {
				return
			}
		}
	}
}

// FindBySlot returns the row with this Slot, or nil when the table has none.
//
// The lookup to reach for when a missing row is an ordinary answer - an optional
// reference, a key that came from user input.
func (t *AssetTable) FindBySlot(key Slot) *AssetRecord {
	position, found := t.bySlot[key]
	if !found {
		return nil
	}

	return &t.records[position]
}

// GetBySlotOrError returns the row with this Slot, or an error naming
// what was missing.
//
// For a key that has to be there - one from another table, or a constant. Go has no
// exception to throw, so where the other languages name a throw this one names the error
// it returns; either way the call site can tell without going to the definition.
func (t *AssetTable) GetBySlotOrError(key Slot) (*AssetRecord, error) {
	position, found := t.bySlot[key]
	if !found {
		return nil, fmt.Errorf(
			"there is no record in table `Asset` that corresponds to field `Slot` value %v", key)
	}

	return &t.records[position], nil
}

// ContainsSlot reports whether the table holds a row with this Slot.
func (t *AssetTable) ContainsSlot(key Slot) bool {
	_, found := t.bySlot[key]
	return found
}

// Read loads the table from a .tcb file written by Tabbit.
func (t *AssetTable) Read(filename string) error {
	data, err := tabbit.ReadAllBytes(filename)
	if err != nil {
		return err
	}

	// Unconditionally, and with whatever EncryptionKey and MacKey hold - which is nil
	// unless the project set them. A file that is neither encrypted nor signed comes back
	// from this untouched, so the load path is the same either way and there is no
	// condition here that could be the wrong way round. spec/wire/tcb-mac-and-signature.md.
	//
	// What comes back is a window onto data rather than a copy of it, which is why data
	// stays in scope for the whole read.
	opened, err := tabbit.Open(data, EncryptionKey, MacKey, VerifyMac)
	if err != nil {
		return err
	}

	reader := tabbit.NewReader(opened)
	count, columns := tabbit.ReadTableHeader(reader)

	// Column by column, matched by tag rather than position: a column this build does
	// not know is skipped by its block length, and one whose type changed incompatibly
	// fails naming the field.
	//
	// Read into rows of its own and assigned at the end. Reading a table that is already
	// loaded is a refresh, and a refresh that turns out to be unreadable has to leave what
	// the table holds alone - the previous rows and an error, not an empty table.
	records := make([]AssetRecord, count)

	for _, column := range columns {
		blockEnd := reader.Position() + int(column.ByteLength)

		switch column.Tag {
		case 1:
			if tabbit.CheckColumn(reader, column, "Asset.Index", tabbit.KindScalar, false, tabbit.ElementUUID) {
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.Index = reader.ReadUUID()
				}
			}
		case 2:
			if tabbit.CheckColumn(reader, column, "Asset.Path", tabbit.KindScalar, false, tabbit.ElementString) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Asset.Path")
				for i := int32(0); i < count; {
					n, value := cursor.NextSameString(count - i)
					for ; n > 0; n-- {
						records[i].Path = value
						i++
					}
				}
			}
		case 3:
			if tabbit.CheckColumn(reader, column, "Asset.Slot", tabbit.KindScalar, false, tabbit.ElementVarint) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Asset.Slot")
				for i := int32(0); i < count; {
					n, value := cursor.NextSameI32(count - i)
					for ; n > 0; n-- {
						records[i].Slot = Slot(value)
						i++
					}
				}
			}
		default:
			// A column added after this code was generated.
			reader.Skip(column.ByteLength)
		}

		tabbit.CheckBlockEnd(reader, column, blockEnd)
	}

	if err := reader.Err(); err != nil {
		return fmt.Errorf("Asset: %w", err)
	}

	byIndex := make(map[tabbit.UUID]int, len(records))
	for i := range records {
		byIndex[records[i].Index] = i
	}

	bySlot := make(map[Slot]int, len(records))
	for i := range records {
		bySlot[records[i].Slot] = i
	}

	// Published, now that every column read and the indexes are built.
	t.records = records
	t.byIndex = byIndex
	t.bySlot = bySlot

	return nil
}
