// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

use std::collections::HashMap;
use std::path::Path;
use crate::tabbit;
use crate::enum_element::Element;
use crate::Reward;

// Generated from test/fixtures/xlsx/declared/declared.xlsx : Declared : B2
/// A record group whose members a schema file declares.
#[derive(Clone, Debug, Default)]
pub struct LoadoutRecord {
    /// primary index
    pub index: i32,
    /// plain column, outside the group
    pub name: String,
    /// Which item, as that table's key.
    pub slot: Vec<Reward>,
    /// an enum the schema file declares
    pub grade: Element,
}

impl LoadoutRecord {
}

/// Every row of Loadout.
#[derive(Clone, Debug, Default)]
pub struct LoadoutTable {
    records: Vec<LoadoutRecord>,
    by_index: HashMap<i32, usize>,
}

impl LoadoutTable {
    /// Every row, in the order the sheet declared them.
    pub fn records(&self) -> &[LoadoutRecord] {
        &self.records
    }

    /// How many rows the table holds.
    pub fn len(&self) -> usize {
        self.records.len()
    }

    /// Whether the table holds no rows.
    ///
    /// Paired with `len` because clippy refuses one without the other, and the generated
    /// crate is built with warnings denied.
    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }

    /// The rows, in the order the file wrote them.
    pub fn iter(&self) -> std::slice::Iter<'_, LoadoutRecord> {
        self.records.iter()
    }

    /// The row with this Index, or None when the table has none.
    ///
    /// The lookup to reach for when a missing row is an ordinary answer - an optional
    /// reference, a key that came from user input.
    pub fn find_by_index(&self, key: i32) -> Option<&LoadoutRecord> {
        self.by_index.get(&key).map(|position| &self.records[*position])
    }

    /// The row with this Index, or an error naming what was missing.
    ///
    /// For a key that has to be there - one from another table, or a constant. Rust has no
    /// exception to throw, so where the other languages name a throw this one names the
    /// error it returns.
    pub fn get_by_index_or_error(&self, key: i32) -> tabbit::Result<&LoadoutRecord> {
        self.by_index
            .get(&key)
            .map(|position| &self.records[*position])
            .ok_or_else(|| tabbit::Error::RecordNotFound {
                table: "Loadout",
                field: "Index",
                key: format!("{:?}", key),
            })
    }

    /// Whether the table holds a row with this Index.
    pub fn contains_index(&self, key: i32) -> bool {
        self.by_index.contains_key(&key)
    }


    /// Each row with the Index it is keyed by.
    ///
    /// What this saves a caller is not the key value - the row carries it - but having to
    /// know which column the key is: Index here, something else in the
    /// next table.
    ///
    /// The rows come in the order the file wrote them rather than the order the map holds
    /// them, which makes this and `iter` agree. Only the primary key has this: a table
    /// keyed by several columns together has no single key value to pair a row with.
    pub fn entries(&self) -> impl Iterator<Item = (&i32, &LoadoutRecord)> + '_ {
        self.records.iter().map(|record| (&record.index, record))
    }

    /// Loads the table from a .tcb file written by Tabbit.
    pub fn read(&mut self, filename: &Path) -> tabbit::Result<()> {
        // Mutable, and it outlives the reader on purpose: opening the envelope decrypts in
        // place and hands back a borrow of these same bytes rather than a copy of them.
        let mut data = tabbit::read_all_bytes(filename)?;

        // Unconditionally, and with whatever `ENCRYPTION_KEY` and `MAC_KEY` hold - which is
        // unset unless the project set them. A file that is neither encrypted nor signed
        // comes back from this untouched, so the load path is the same either way and there
        // is no condition here that could be the wrong way round.
        // spec/wire/tcb-mac-and-signature.md.
        let key: &[u8] = crate::ENCRYPTION_KEY.get().map(Vec::as_slice).unwrap_or(&[]);
        let mac_key: &[u8] = crate::MAC_KEY.get().map(Vec::as_slice).unwrap_or(&[]);

        let mut reader = tabbit::Reader::new(tabbit::open(
            &mut data,
            key,
            mac_key,
            crate::VERIFY_MAC.load(std::sync::atomic::Ordering::Relaxed),
        )?);

        // Column by column, matched by tag rather than position: a column this build
        // does not know is skipped by its block length, and one whose type changed
        // incompatibly fails naming the field.
        let header = tabbit::read_table_header(&mut reader)?;
        let count = header.row_count.max(0) as usize;

        // Read into rows of its own and assigned at the end. Reading a table that is
        // already loaded is a refresh, and one that turns out to be unreadable has to
        // leave the rows already there alone - `?` returns before anything is replaced.
        let mut records = vec![LoadoutRecord::default(); count];

        // A record array whose length is the sheet's column count is created with the row
        // rather than by whichever member column arrives first. `Default` gives an empty
        // vector, so otherwise a file that no longer carries the first member would leave
        // the ones after it indexing past the end.
        for record in records.iter_mut() {
            record.slot = Vec::new();
        }

        for column in &header.columns {
            let block_end = reader.position() + column.byte_length.max(0) as usize;

            match column.tag {
                1 => {
                    tabbit::check_column(column, "Loadout.Index", tabbit::KIND_SCALAR, false, &[tabbit::ELEMENT_I32, tabbit::ELEMENT_VARINT])?;
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Loadout.Index")?;
                    let mut at = 0usize;
                    while at < records.len() {
                        let (n, value) = cursor.next_same_i32((records.len() - at) as i32)?;
                        for _ in 0..n {
                            records[at].index = value;
                            at += 1;
                        }
                    }
                }
                2 => {
                    tabbit::check_column(column, "Loadout.Name", tabbit::KIND_SCALAR, false, &[tabbit::ELEMENT_STRING])?;
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Loadout.Name")?;
                    let mut at = 0usize;
                    while at < records.len() {
                        let (n, value) = cursor.next_same_string((records.len() - at) as i32)?;
                        for _ in 0..n {
                            records[at].name = value.clone();
                            at += 1;
                        }
                    }
                }
                3 => {
                    tabbit::check_column(column, "Loadout.Slot.ItemId", tabbit::KIND_ARRAY, false, &[tabbit::ELEMENT_I32, tabbit::ELEMENT_VARINT])?;
                    let bytes_left = reader.remaining();
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Loadout.Slot.ItemId")?;
                    for record in records.iter_mut() {
                        let element_count = cursor.next_length()?.max(0) as usize;
                        // The count came off the wire, and one element is at least one byte,
                        // so this is checked before anything is allocated for it.
                        if element_count > bytes_left {
                            return Err(tabbit::Error::ColumnMismatch {
                                field: "Loadout.slot",
                                detail: "a record array is longer than the file can hold",
                            });
                        }

                        // The first member allocates; the rest check. Allocating again would
                        // discard what the members before it wrote, and taking the shorter of
                        // two counts would shift every value after it.
                        record.slot = vec![Reward::default(); element_count];
                        for element in 0..element_count {
                            record.slot[element].item_id = cursor.next_i32()?;
                        }
                    }
                }
                4 => {
                    tabbit::check_column(column, "Loadout.Slot.Count", tabbit::KIND_ARRAY, false, &[tabbit::ELEMENT_I32, tabbit::ELEMENT_VARINT])?;
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Loadout.Slot.Count")?;
                    for record in records.iter_mut() {
                        let element_count = cursor.next_length()?.max(0) as usize;
                        if record.slot.len() != element_count {
                            return Err(tabbit::Error::ColumnMismatch {
                                field: "Loadout.slot",
                                detail: "the file gives one member of this record a different \
                                         element count than another",
                            });
                        }
                        for element in 0..element_count {
                            record.slot[element].count = cursor.next_i32()?;
                        }
                    }
                }
                5 => {
                    tabbit::check_column(column, "Loadout.Slot.Icon", tabbit::KIND_ARRAY, false, &[tabbit::ELEMENT_STRING])?;
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Loadout.Slot.Icon")?;
                    for record in records.iter_mut() {
                        let element_count = cursor.next_length()?.max(0) as usize;
                        if record.slot.len() != element_count {
                            return Err(tabbit::Error::ColumnMismatch {
                                field: "Loadout.slot",
                                detail: "the file gives one member of this record a different \
                                         element count than another",
                            });
                        }
                        for element in 0..element_count {
                            record.slot[element].icon = cursor.next_string()?;
                        }
                    }
                }
                6 => {
                    tabbit::check_column(column, "Loadout.Grade", tabbit::KIND_SCALAR, false, &[tabbit::ELEMENT_VARINT])?;
                    let mut cursor = tabbit::TcbColumnCursor::new(&mut reader, column, header.row_count, "Loadout.Grade")?;
                    let mut at = 0usize;
                    while at < records.len() {
                        let (n, value) = cursor.next_same_i32((records.len() - at) as i32)?;
                        for _ in 0..n {
                            records[at].grade = Element::from_value(value).unwrap_or_default();
                            at += 1;
                        }
                    }
                }
                _ => {
                    // A column added after this code was generated.
                    reader.skip(column.byte_length)?;
                }
            }

            tabbit::check_block_end(&reader, column, block_end)?;
        }

        let by_index = records
            .iter()
            .enumerate()
            .map(|(position, record)| (record.index.clone(), position))
            .collect();

        // Published, now that every column read.
        self.records = records;
        self.by_index = by_index;

        Ok(())
    }
}

/// Lets a borrow of the table be iterated directly - `for record in &table`.
///
/// Separate from `iter` rather than instead of it, because a method is what an iterator
/// chain starts from and the trait is what a `for` reaches for; a crate that has one and
/// not the other reads as unfinished from whichever side the caller came in on.
impl<'a> IntoIterator for &'a LoadoutTable {
    type Item = &'a LoadoutRecord;
    type IntoIter = std::slice::Iter<'a, LoadoutRecord>;

    fn into_iter(self) -> Self::IntoIter {
        self.records.iter()
    }
}
