<?php

// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace Tabbit\Fixtures\MultiTarget;

require_once __DIR__ . '/../tabbit/TcbReader.php';
require_once __DIR__ . '/../enums/HolderPickTarget.php';
require_once __DIR__ . '/../enums/HolderWideTarget.php';
require_once __DIR__ . '/../enums/HolderMaybeTarget.php';
require_once __DIR__ . '/../MultiTargetAccessor.php';

use Tabbit\TcbReader;
use Tabbit\TcbColumnCursor;
use Tabbit\RecordNotFoundException;
use Tabbit\Uuid;

/**
 * Generated from test/fixtures/xlsx/multi-target/multi-target.xlsx : Holders : B2
 *
 * One column per case the spec states.
 */
final class HolderRecord
{
    /** primary index */
    public int $index = 0;
    /** two targets - the ordinary case */
    public int $pick = 0;
    /** five targets, and the value picks one */
    public int $wide = 0;
    /** the same notation with one name */
    public ?WeaponRecord $only = null;

    public int $onlyIndex = 0;
    /** two targets, and `-` is none of them */
    public int $maybe = 0;

    public bool $hasMaybe = false;
    /** The row this column names, as whichever of its targets holds it. Read it through the methods below. */
    public ?object $pickRow = null;
    /** Which table this column is a row of. */
    public HolderPickTarget $pickTarget = HolderPickTarget::None;
    /** The row this column names, as whichever of its targets holds it. Read it through the methods below. */
    public ?object $wideRow = null;
    /** Which table this column is a row of. */
    public HolderWideTarget $wideTarget = HolderWideTarget::None;
    /** The row this column names, as whichever of its targets holds it. Read it through the methods below. */
    public ?object $maybeRow = null;
    /** Which table this column is a row of. */
    public HolderMaybeTarget $maybeTarget = HolderMaybeTarget::None;


    /** The WeaponRecord row this column names, or null when it names a row of one of the others. */
    public function weaponByPick(): ?WeaponRecord
    {
        if ($this->pickTarget !== HolderPickTarget::Weapon) {
            return null;
        }

        return $this->pickRow;
    }

    /** The ArmourRecord row this column names, or null when it names a row of one of the others. */
    public function armourByPick(): ?ArmourRecord
    {
        if ($this->pickTarget !== HolderPickTarget::Armour) {
            return null;
        }

        return $this->pickRow;
    }


    /** The WeaponRecord row this column names, or null when it names a row of one of the others. */
    public function weaponByWide(): ?WeaponRecord
    {
        if ($this->wideTarget !== HolderWideTarget::Weapon) {
            return null;
        }

        return $this->wideRow;
    }

    /** The ArmourRecord row this column names, or null when it names a row of one of the others. */
    public function armourByWide(): ?ArmourRecord
    {
        if ($this->wideTarget !== HolderWideTarget::Armour) {
            return null;
        }

        return $this->wideRow;
    }

    /** The TrinketRecord row this column names, or null when it names a row of one of the others. */
    public function trinketByWide(): ?TrinketRecord
    {
        if ($this->wideTarget !== HolderWideTarget::Trinket) {
            return null;
        }

        return $this->wideRow;
    }

    /** The MountRecord row this column names, or null when it names a row of one of the others. */
    public function mountByWide(): ?MountRecord
    {
        if ($this->wideTarget !== HolderWideTarget::Mount) {
            return null;
        }

        return $this->wideRow;
    }

    /** The BannerRecord row this column names, or null when it names a row of one of the others. */
    public function bannerByWide(): ?BannerRecord
    {
        if ($this->wideTarget !== HolderWideTarget::Banner) {
            return null;
        }

        return $this->wideRow;
    }


    /** The WeaponRecord row this column names, or null when it names a row of one of the others. */
    public function weaponByMaybe(): ?WeaponRecord
    {
        if ($this->maybeTarget !== HolderMaybeTarget::Weapon) {
            return null;
        }

        return $this->maybeRow;
    }

    /** The ArmourRecord row this column names, or null when it names a row of one of the others. */
    public function armourByMaybe(): ?ArmourRecord
    {
        if ($this->maybeTarget !== HolderMaybeTarget::Armour) {
            return null;
        }

        return $this->maybeRow;
    }
}

/** Every row of Holder. */
final class HolderTable
{
    /** @var list<HolderRecord> */
    public array $records = [];

    /** @var array<int, HolderRecord> */
    private array $byIndex = [];

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public function findByIndex(int $key): ?HolderRecord
    {
        return $this->byIndex[$key] ?? null;
    }

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex($key)->name at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public function getByIndexOrThrow(int $key): HolderRecord
    {
        $record = $this->byIndex[$key] ?? null;

        if ($record === null) {
            throw new RecordNotFoundException(
                "There is no record in table `Holder` that corresponds to " .
                "field `Index` value " . $key . ".");
        }

        return $record;
    }

    /** Whether the table holds a row with this Index. */
    public function containsIndex(int $key): bool
    {
        return isset($this->byIndex[$key]);
    }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public function read(string $filename): void
    {
        // The keys go to fromFile because reading and opening are one call here: the
        // reader's constructor takes the whole file and opens the envelope itself. It does
        // so unconditionally, and with whatever MultiTargetAccessor::$encryptionKey and
        // MultiTargetAccessor::$macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from that untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/tcb-mac-and-signature.md.
        $reader = TcbReader::fromFile(
            $filename, MultiTargetAccessor::$encryptionKey,
            MultiTargetAccessor::$macKey, MultiTargetAccessor::$verifyMac);
        [$count, $columns] = $reader->readTableHeader();

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        $records = [];
        $byIndex = [];

        for ($i = 0; $i < $count; $i++) {
            $records[] = new HolderRecord();
        }

        foreach ($columns as $column) {
            $blockEnd = $reader->position() + $column['byteLength'];

            switch ($column['tag']) {
                case 1:
                    TcbReader::checkColumn($column, 'Holder.Index', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Holder.Index');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->index = $value;
                        }
                    }
                    break;

                case 2:
                    TcbReader::checkColumn($column, 'Holder.Pick', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Holder.Pick');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->pick = $value;
                        }
                    }
                    break;

                case 3:
                    TcbReader::checkColumn($column, 'Holder.Wide', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Holder.Wide');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->wide = $value;
                        }
                    }
                    break;

                case 4:
                    TcbReader::checkColumn($column, 'Holder.Only', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Holder.Only');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->onlyIndex = $value;
                        }
                    }
                    break;

                case 5:
                    TcbReader::checkColumn($column, 'Holder.Maybe', TcbReader::KIND_SCALAR, true, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    // The bitmap is at the front of the block, so it is read before the
                    // values. The values are written for every row either way, which is what
                    // lets the read shapes below stay as they are.
                    $presence = $reader->readPresence($column, $count);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Holder.Maybe');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->maybe = $value;
                        }
                    }

                    // A pass of its own rather than a line inside each read shape, so the row
                    // index is worked out once. The block carries a value for every row, so
                    // an absent one has just been given whatever was there; putting the empty
                    // value back is what makes this path agree with the JSON one.
                    foreach ($records as $row => $record) {
                        $record->hasMaybe = TcbReader::isPresent($presence, $row);

                        if (!$record->hasMaybe) {
                            $record->maybe = 0;
                        }
                    }
                    break;

                default:
                    // A column added after this code was generated.
                    $reader->skip($column['byteLength']);
                    break;
            }

            $reader->checkBlockEnd($column, $blockEnd);
        }

        foreach ($records as $record) {
            $byIndex[$record->index] = $record;
        }

        // Published, now that every column read.
        $this->records = $records;
        $this->byIndex = $byIndex;
    }
}
