<?php

// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace Tabbit\Fixtures\MultiTarget;

require_once __DIR__ . '/../tabbit/TcbReader.php';
require_once __DIR__ . '/../enums/RackSlotsPickTarget.php';
require_once __DIR__ . '/../MultiTargetAccessor.php';

use Tabbit\TcbReader;
use Tabbit\TcbColumnCursor;
use Tabbit\RecordNotFoundException;
use Tabbit\Uuid;

/** One element of RackRecord::$slots. */
final class RackSlotsEntry
{
    /** element 1 of the member */
    /** @var list<int> */
    public array $pick = [];

    /** @var list<?object> The rows this member names, as whichever of its targets holds each. */
    public array $pickRow = [];

    /** @var list<RackSlotsPickTarget> Which table each element is a row of. */
    public array $pickTarget = [];
    /** element 1 beside it */
    /** @var int[] */
    public array $count = [];

    /**
     * What cannot be built at a declaration: the levels below, and the lists whose positions
     * have to be there before anything fills one.
     *
     * A PHP property initializer has to be a constant expression, and a typed property left
     * unset is an error to read.
     */
    public function __construct()
    {
        $this->pickRow = array_fill(0, 2, null);
        $this->pickTarget = array_fill(0, 2, RackSlotsPickTarget::None);
    }

    /** The WeaponRecord row element `$at` of $pick names, or null when that element names a row of one of the others. */
    public function weaponByPick(int $at): ?WeaponRecord
    {
        if ($this->pickTarget[$at] !== RackSlotsPickTarget::Weapon) {
            return null;
        }

        return $this->pickRow[$at];
    }

    /** The ArmourRecord row element `$at` of $pick names, or null when that element names a row of one of the others. */
    public function armourByPick(int $at): ?ArmourRecord
    {
        if ($this->pickTarget[$at] !== RackSlotsPickTarget::Armour) {
            return null;
        }

        return $this->pickRow[$at];
    }
}

/**
 * Generated from test/fixtures/xlsx/multi-target/multi-target.xlsx : Groups : R2
 *
 * One record whose members are arrays, one of them reaching several.
 */
final class RackRecord
{
    /** primary index */
    public int $index = 0;
    /** element 1 of the member */
    public RackSlotsEntry $slots;


    /**
     * A row with its record groups built.
     *
     * They cannot be built at the declaration: a PHP property initializer has to be a
     * constant expression, and `new SlotEntry()` is not one.
     */
    public function __construct()
    {
        $this->slots = new RackSlotsEntry();
    }
}

/** Every row of Rack. */
final class RackTable
{
    /** @var list<RackRecord> */
    public array $records = [];

    /** @var array<int, RackRecord> */
    private array $byIndex = [];

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public function findByIndex(int $key): ?RackRecord
    {
        return $this->byIndex[$key] ?? null;
    }

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex($key)->name at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public function getByIndexOrThrow(int $key): RackRecord
    {
        $record = $this->byIndex[$key] ?? null;

        if ($record === null) {
            throw new RecordNotFoundException(
                "There is no record in table `Rack` that corresponds to " .
                "field `Index` value " . $key . ".");
        }

        return $record;
    }

    /** Whether the table holds a row with this Index. */
    public function containsIndex(int $key): bool
    {
        return isset($this->byIndex[$key]);
    }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public function read(string $filename): void
    {
        // The keys go to fromFile because reading and opening are one call here: the
        // reader's constructor takes the whole file and opens the envelope itself. It does
        // so unconditionally, and with whatever MultiTargetAccessor::$encryptionKey and
        // MultiTargetAccessor::$macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from that untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/tcb-mac-and-signature.md.
        $reader = TcbReader::fromFile(
            $filename, MultiTargetAccessor::$encryptionKey,
            MultiTargetAccessor::$macKey, MultiTargetAccessor::$verifyMac);
        [$count, $columns] = $reader->readTableHeader();

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        $records = [];
        $byIndex = [];

        for ($i = 0; $i < $count; $i++) {
            $records[] = new RackRecord();
        }

        foreach ($columns as $column) {
            $blockEnd = $reader->position() + $column['byteLength'];

            switch ($column['tag']) {
                case 1:
                    TcbReader::checkColumn($column, 'Rack.Index', TcbReader::KIND_SCALAR, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Rack.Index');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->index = $value;
                        }
                    }
                    break;

                case 2:
                    TcbReader::checkColumn($column, 'Rack.Slots.Pick', TcbReader::KIND_ARRAY, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Rack.Slots.Pick');
                    foreach ($records as $record) {
                        $elementCount = $cursor->nextLength();
                        $record->slots->pick = [];
                        for ($j = 0; $j < $elementCount; $j++) {
                            $record->slots->pick[$j] = $cursor->nextI32();
                        }
                    }
                    break;

                case 3:
                    TcbReader::checkColumn($column, 'Rack.Slots.Count', TcbReader::KIND_ARRAY, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Rack.Slots.Count');
                    foreach ($records as $record) {
                        $elementCount = $cursor->nextLength();
                        $record->slots->count = [];
                        for ($j = 0; $j < $elementCount; $j++) {
                            $record->slots->count[$j] = $cursor->nextI32();
                        }
                    }
                    break;

                default:
                    // A column added after this code was generated.
                    $reader->skip($column['byteLength']);
                    break;
            }

            $reader->checkBlockEnd($column, $blockEnd);
        }

        foreach ($records as $record) {
            $byIndex[$record->index] = $record;
        }

        // Published, now that every column read.
        $this->records = $records;
        $this->byIndex = $byIndex;
    }
}
