# ------------------------------------------------------------------------------
# Generated by Tabbit. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

import enum
import os

from . import tabbit
from .enum_slot import Slot


class LoadoutRecord:
    """Generated from test/fixtures/xlsx/composite-key/composite-key.xlsx : Loadout : B2.

    One row per stage and slot; neither column is unique on its own.
    """

    __slots__ = ("stage", "slot", "power", "label")

    def __init__(self):
        self.stage = 0
        self.slot = Slot(0)
        self.power = 0
        self.label = ""

    def __repr__(self):
        return "LoadoutRecord(stage=%r, slot=%r, power=%r, label=%r)" % (self.stage, self.slot, self.power, self.label)


class LoadoutTable:
    """Every row of Loadout."""

    __slots__ = ("records", "by_stage_and_slot")

    def __init__(self):
        self.records = []
        self.by_stage_and_slot = {}

    @staticmethod
    def _key_of_stage_and_slot(stage_key, slot_key):
        """Joins the columns of the Stage and Slot key into the text the map is keyed by."""
        parts = [
            str(int(stage_key)),
            str(int(slot_key)),
        ]

        return "".join("%d:%s" % (len(part), part) for part in parts)

    def find_by_stage_and_slot(self, stage_key, slot_key):
        """The row with this Stage and Slot, or None when the table has none.

        The lookup to reach for when a missing row is an ordinary answer - an optional
        reference, a key that came from user input.
        """
        return self.by_stage_and_slot.get(self._key_of_stage_and_slot(stage_key, slot_key))

    def get_by_stage_and_slot_or_throw(self, stage_key, slot_key):
        """The row with this Stage and Slot, or a raised error naming what was missing.

        For a key that has to be there - one from another table, or a constant. The name
        says it raises, because a caller reading `get_by_stage_and_slot(key).name` at a
        glance cannot otherwise tell whether the next line is a check or a try.
        """
        record = self.by_stage_and_slot.get(self._key_of_stage_and_slot(stage_key, slot_key))

        if record is None:
            raise tabbit.RecordNotFoundError(
                "there is no record in table `Loadout` that corresponds to "
                "field `Stage and Slot` value (%r, %r)" % (stage_key, slot_key,))

        return record

    def contains_stage_and_slot(self, stage_key, slot_key):
        """Whether the table holds a row with this Stage and Slot."""
        return self._key_of_stage_and_slot(stage_key, slot_key) in self.by_stage_and_slot

    def read(self, filename):
        """Loads the table from a .tcb file written by Tabbit.

        Column by column, matched by tag rather than position: a column this build does
        not know is skipped by its block length, and one whose type changed incompatibly
        fails naming the field.
        """
        # Imported here rather than at the top: `tables` imports this module,
        # so at import time it is half built and at call time it is not.
        from .tables import Tables

        # Opened unconditionally, and with whatever `Tables.encryption_key` and
        # `Tables.mac_key` hold - which is None unless the project set them. A file that is
        # neither encrypted nor signed comes back from this untouched, so the load path is
        # the same either way and there is no condition here that could be the wrong way
        # round. spec/wire/tcb-mac-and-signature.md.
        reader = tabbit.Reader(tabbit.open(
            tabbit.read_all_bytes(filename), Tables.encryption_key,
            Tables.mac_key, Tables.verify_mac))
        count, columns = tabbit.read_table_header(reader)

        # Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        records = [LoadoutRecord() for _ in range(count)]

        for column in columns:
            block_end = reader.position + column.byte_length
            if column.tag == 1:
                tabbit.check_column(column, "Loadout.Stage", tabbit.KIND_SCALAR, False, (tabbit.ELEMENT_I32, tabbit.ELEMENT_VARINT))
                cursor = tabbit.ColumnCursor(reader, column, count, "Loadout.Stage")
                at = 0
                while at < count:
                    n, value = cursor.next_same_i32(count - at)
                    for i in range(at, at + n):
                        records[i].stage = value
                    at += n
            elif column.tag == 2:
                tabbit.check_column(column, "Loadout.Slot", tabbit.KIND_SCALAR, False, (tabbit.ELEMENT_VARINT,))
                cursor = tabbit.ColumnCursor(reader, column, count, "Loadout.Slot")
                at = 0
                while at < count:
                    n, value = cursor.next_same_i32(count - at)
                    for i in range(at, at + n):
                        records[i].slot = Slot(value)
                    at += n
            elif column.tag == 3:
                tabbit.check_column(column, "Loadout.Power", tabbit.KIND_SCALAR, False, (tabbit.ELEMENT_I32, tabbit.ELEMENT_VARINT))
                cursor = tabbit.ColumnCursor(reader, column, count, "Loadout.Power")
                at = 0
                while at < count:
                    n, value = cursor.next_same_i32(count - at)
                    for i in range(at, at + n):
                        records[i].power = value
                    at += n
            elif column.tag == 4:
                tabbit.check_column(column, "Loadout.Label", tabbit.KIND_SCALAR, False, (tabbit.ELEMENT_STRING,))
                cursor = tabbit.ColumnCursor(reader, column, count, "Loadout.Label")
                at = 0
                while at < count:
                    n, value = cursor.next_same_string(count - at)
                    for i in range(at, at + n):
                        records[i].label = value
                    at += n
            else:
                # A column added after this code was generated.
                reader.skip(column.byte_length)

            tabbit.check_block_end(reader, column, block_end)

        by_stage_and_slot = {
            self._key_of_stage_and_slot(record.stage, record.slot): record
            for record in records
        }

        # Published, now that every column read.
        self.records = records
        self.by_stage_and_slot = by_stage_and_slot
