// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

@file:Suppress("unused", "RedundantVisibilityModifier", "UNUSED_IMPORT")

package tabbit.fixtures.docshowcase

import java.io.File
import tabbit.TcbReader
import tabbit.RecordNotFoundException
import tabbit.Uuid
import tabbit.readAllBytes
import tabbit.open
import tabbit.readTableHeader
import tabbit.checkColumn
import tabbit.checkColumnWithElements
import tabbit.checkBlockEnd
import tabbit.readPresence
import tabbit.readElementPresence
import tabbit.isPresent
import tabbit.TcbException
import tabbit.ColumnCursor
import tabbit.ELEMENT_VARINT
import tabbit.ELEMENT_BOOL
import tabbit.ELEMENT_I32
import tabbit.ELEMENT_I64
import tabbit.ELEMENT_F32
import tabbit.ELEMENT_F64
import tabbit.ELEMENT_STRING
import tabbit.ELEMENT_UUID
import tabbit.KIND_SCALAR
import tabbit.KIND_ARRAY

// Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Basics : G2
/** What a potion is made of. */
enum class Element(val value: Int) {
    /** no element */
    NONE(0),
    /** burns */
    FIRE_BALL(1),
    /** chills */
    ICE_SHARD(2);

    companion object {
        /**
         * The label with this value, or the default when the sheet declared no such label.
         *
         * A fallback rather than a throw, matching the other generated readers.
         */
        fun of(value: Int): Element =
            entries.firstOrNull { it.value == value } ?: Element.NONE
    }
}
