/* ------------------------------------------------------------------------------
 * Generated by Tabbit. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#ifndef COMPOSITE_KEY_GRID_H
#define COMPOSITE_KEY_GRID_H

#include "tabbit/tabbit_tcb_reader.h"

#include "CompositeKey_Forward.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Generated from test/fixtures/xlsx/composite-key/composite-key.xlsx : Grid : B2
 *
 * Three columns taken together, so two is not the only width that works.
 */
struct CompositeKey_GridRecord_t {
  /* column */
  int32_t x;
  /* row */
  int32_t y;
  /* layer */
  const char* z;
  /* anything */
  const char* name;
};

/* Every row of Grid.
 *
 * The arena owns every string and every array the records point into, so the
 * whole table is released in one call and no record's pointer outlives it. */
typedef struct CompositeKey_GridTable_t {
  CompositeKey_GridRecord_t* records;
  int32_t count;

  tb_string_index_entry* by_x_and_y_and_z;
  tb_arena arena;
} CompositeKey_GridTable_t;

/* Loads the table from a .tcb file written by Tabbit.
 *
 * Returns false and leaves the table empty when the file is missing, truncated
 * or malformed; the reason goes to `error` when one is passed. */
bool CompositeKey_GridLoad(CompositeKey_GridTable_t* table, const char* filename,
                   char* error, size_t error_size);

/* Releases everything the table owns. Safe on a zeroed table, and safe twice. */
void CompositeKey_GridFree(CompositeKey_GridTable_t* table);

/* The row with the given X and Y and Z, or NULL when the table has none.
 *
 * The lookup to reach for when a missing row is an ordinary answer - an optional
 * reference, a key that came from user input. C has nothing to throw, so a caller
 * that needs the row to be there checks this NULL and says so itself. */
const CompositeKey_GridRecord_t* CompositeKey_GridFindByXAndYAndZ(
  const CompositeKey_GridTable_t* table, int32_t x_key, int32_t y_key, const char* z_key);

/* Whether the table holds a row with this X and Y and Z. */
bool CompositeKey_GridContainsXAndYAndZ(
  const CompositeKey_GridTable_t* table, int32_t x_key, int32_t y_key, const char* z_key);

#ifdef __cplusplus
}
#endif

#endif /* COMPOSITE_KEY_GRID_H */
