<?php

// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace Tabbit\Fixtures\Nested;

require_once __DIR__ . '/../tabbit/TcbReader.php';
require_once __DIR__ . '/../NestedAccessor.php';

use Tabbit\TcbReader;
use Tabbit\TcbColumnCursor;
use Tabbit\RecordNotFoundException;
use Tabbit\Uuid;

/** One element of LoadoutRecord::$pos. */
final class LoadoutPosEntry
{
    /** record with no number */
    public float $x = 0.0;
    /** second member of the same record */
    public float $y = 0.0;
}

/** One element of LoadoutRecord::$slot. */
final class LoadoutSlotEntry
{
    /** element 1, first member */
    public int $id = 0;
    /** element 1, second member */
    public string $label = '';
}

/**
 * Generated from test/fixtures/xlsx/nested/nested.xlsx : Nested : B2
 *
 * Columns folded into records by the Group.Member notation.
 */
final class LoadoutRecord
{
    /** primary index */
    public int $index = 0;
    /** plain column, between two groups */
    public string $name = '';
    /** record with no number */
    public LoadoutPosEntry $pos;
    /** element 1, first member */
    /** @var list<LoadoutSlotEntry> */
    public array $slot = [];
    /** plain column inside the group's span */
    public string $note = '';
    /** scalar serial field */
    /** @var list<string> */
    public array $tagArray = [];


    /**
     * A row with its record groups built.
     *
     * They cannot be built at the declaration: a PHP property initializer has to be a
     * constant expression, and `new SlotEntry()` is not one.
     */
    public function __construct()
    {
        $this->pos = new LoadoutPosEntry();
        for ($i = 0; $i < 2; $i++) {
            $this->slot[] = new LoadoutSlotEntry();
        }
    }
}

/** Every row of Loadout. */
final class LoadoutTable
{
    /** @var list<LoadoutRecord> */
    public array $records = [];

    /** @var array<int, LoadoutRecord> */
    private array $byIndex = [];

    /**
     * The row with this Index, or null when the table has none.
     *
     * The lookup to reach for when a missing row is an ordinary answer - an optional
     * reference, a key that came from user input.
     */
    public function findByIndex(int $key): ?LoadoutRecord
    {
        return $this->byIndex[$key] ?? null;
    }

    /**
     * The row with this Index, or a thrown exception naming what was missing.
     *
     * For a key that has to be there - one from another table, or a constant. The name says
     * it throws, because a caller reading getByIndex($key)->name at a glance
     * cannot otherwise tell whether the next line is a null check or a catch.
     */
    public function getByIndexOrThrow(int $key): LoadoutRecord
    {
        $record = $this->byIndex[$key] ?? null;

        if ($record === null) {
            throw new RecordNotFoundException(
                "There is no record in table `Loadout` that corresponds to " .
                "field `Index` value " . $key . ".");
        }

        return $record;
    }

    /** Whether the table holds a row with this Index. */
    public function containsIndex(int $key): bool
    {
        return isset($this->byIndex[$key]);
    }

    /** Loads the table from a .tcb file written by Tabbit. */
    /**
     * Column by column, matched by tag rather than position: a column this build does not
     * know is skipped by its block length, and one whose type changed incompatibly fails
     * naming the field.
     */
    public function read(string $filename): void
    {
        // The keys go to fromFile because reading and opening are one call here: the
        // reader's constructor takes the whole file and opens the envelope itself. It does
        // so unconditionally, and with whatever NestedAccessor::$encryptionKey and
        // NestedAccessor::$macKey hold - which is null unless the project set them. A
        // file that is neither encrypted nor signed comes back from that untouched, so the
        // load path is the same either way and there is no condition here that could be the
        // wrong way round. spec/tcb-mac-and-signature.md.
        $reader = TcbReader::fromFile(
            $filename, NestedAccessor::$encryptionKey,
            NestedAccessor::$macKey, NestedAccessor::$verifyMac);
        [$count, $columns] = $reader->readTableHeader();

        // Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
        $records = [];
        $byIndex = [];

        for ($i = 0; $i < $count; $i++) {
            $records[] = new LoadoutRecord();
        }

        foreach ($columns as $column) {
            $blockEnd = $reader->position() + $column['byteLength'];

            switch ($column['tag']) {
                case 1:
                    TcbReader::checkColumn($column, 'Loadout.Index', TcbReader::KIND_SCALAR, 1, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Index');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameI32($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->index = $value;
                        }
                    }
                    break;

                case 2:
                    TcbReader::checkColumn($column, 'Loadout.Name', TcbReader::KIND_SCALAR, 1, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Name');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameString($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->name = $value;
                        }
                    }
                    break;

                case 3:
                    TcbReader::checkColumn($column, 'Loadout.Pos.X', TcbReader::KIND_SCALAR, 1, false, [TcbReader::ELEMENT_F32]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Pos.X');
                    foreach ($records as $record) {
                        $record->pos->x = $cursor->nextF32();
                    }
                    break;

                case 4:
                    TcbReader::checkColumn($column, 'Loadout.Pos.Y', TcbReader::KIND_SCALAR, 1, false, [TcbReader::ELEMENT_F32]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Pos.Y');
                    foreach ($records as $record) {
                        $record->pos->y = $cursor->nextF32();
                    }
                    break;

                case 5:
                    TcbReader::checkColumn($column, 'Loadout.Slot.Id', TcbReader::KIND_FIXED_ARRAY, 2, false, [TcbReader::ELEMENT_I32, TcbReader::ELEMENT_VARINT]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Slot.Id');
                    foreach ($records as $record) {
                        for ($j = 0; $j < 2; $j++) {
                            $record->slot[$j]->id = $cursor->nextI32();
                        }
                    }
                    break;

                case 6:
                    TcbReader::checkColumn($column, 'Loadout.Slot.Label', TcbReader::KIND_FIXED_ARRAY, 2, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Slot.Label');
                    foreach ($records as $record) {
                        for ($j = 0; $j < 2; $j++) {
                            $record->slot[$j]->label = $cursor->nextString();
                        }
                    }
                    break;

                case 7:
                    TcbReader::checkColumn($column, 'Loadout.Note', TcbReader::KIND_SCALAR, 1, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Note');
                    for ($i = 0; $i < $count; ) {
                        [$n, $value] = $cursor->nextSameString($count - $i);
                        for (; $n > 0; $n--, $i++) {
                            $records[$i]->note = $value;
                        }
                    }
                    break;

                case 8:
                    TcbReader::checkColumn($column, 'Loadout.Tag_array', TcbReader::KIND_FIXED_ARRAY, 2, false, [TcbReader::ELEMENT_STRING]);
                    $cursor = new TcbColumnCursor($reader, $column, $count, 'Loadout.Tag_array');
                    foreach ($records as $record) {
                        $record->tagArray = [];
                        for ($j = 0; $j < 2; $j++) {
                            $record->tagArray[] = $cursor->nextString();
                        }
                    }
                    break;

                default:
                    // A column added after this code was generated.
                    $reader->skip($column['byteLength']);
                    break;
            }

            $reader->checkBlockEnd($column, $blockEnd);
        }

        foreach ($records as $record) {
            $byIndex[$record->index] = $record;
        }

        // Published, now that every column read.
        $this->records = $records;
        $this->byIndex = $byIndex;
    }
}
