// ------------------------------------------------------------------------------
// Code generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package declareddata

import (
	"strconv"
)

// Affinity was generated from loadout.tbs(38,6).
// What a reward is made of.
//
// Declared here rather than in a sheet, so the type cell that names it is reading a
// declaration this run read from a file.
type Affinity int32

const (
	// Burns.
	AffinityFire Affinity = 1
	// Freezes.
	AffinityIce Affinity = 2
)

// String names the label, or renders the number when the value has none.
func (v Affinity) String() string {
	switch v {
	case AffinityFire:
		return "Fire"
	case AffinityIce:
		return "Ice"
	}

	return strconv.FormatInt(int64(v), 10)
}
