/* ------------------------------------------------------------------------------
 * Generated by Tabbit. DO NOT EDIT.
 *
 * Changes to this file may cause incorrect behavior and will be lost if the code is
 * regenerated.
 * ------------------------------------------------------------------------------
 */

#ifndef DOC_SHOWCASE_SAMPLE_H
#define DOC_SHOWCASE_SAMPLE_H

#include "tabbit/tabbit_tcb_reader.h"

#include "DocShowcase_Forward.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Types : B2
 *
 * One column per scalar type.
 */
struct DocShowcase_SampleRecord_t {
  /* primary index */
  int32_t index;
  /* 64 bit */
  int64_t count;
  /* 32 bit */
  float ratio;
  /* 64 bit */
  double precise;
  /* Y or N */
  bool enabled;
  /* text */
  const char* label;
  /* a moment */
  int64_t at;
  /* a length */
  int64_t span;
  /* an identifier */
  tb_uuid id;
};

/* Every row of Sample.
 *
 * The arena owns every string and every array the records point into, so the
 * whole table is released in one call and no record's pointer outlives it. */
typedef struct DocShowcase_SampleTable_t {
  DocShowcase_SampleRecord_t* records;
  int32_t count;

  tb_index_entry* by_index;
  tb_arena arena;
} DocShowcase_SampleTable_t;

/* Loads the table from a .tcb file written by Tabbit.
 *
 * Returns false and leaves the table empty when the file is missing, truncated
 * or malformed; the reason goes to `error` when one is passed. */
bool DocShowcase_SampleLoad(DocShowcase_SampleTable_t* table, const char* filename,
                   char* error, size_t error_size);

/* Releases everything the table owns. Safe on a zeroed table, and safe twice. */
void DocShowcase_SampleFree(DocShowcase_SampleTable_t* table);

/* The row with the given Index, or NULL when the table has none.
 *
 * The lookup to reach for when a missing row is an ordinary answer - an optional
 * reference, a key that came from user input. C has nothing to throw, so a caller
 * that needs the row to be there checks this NULL and says so itself. */
const DocShowcase_SampleRecord_t* DocShowcase_SampleFindByIndex(
  const DocShowcase_SampleTable_t* table, int32_t key);

/* Whether the table holds a row with this Index. */
bool DocShowcase_SampleContainsIndex(
  const DocShowcase_SampleTable_t* table, int32_t key);

#ifdef __cplusplus
}
#endif

#endif /* DOC_SHOWCASE_SAMPLE_H */
