-- ------------------------------------------------------------------------------
-- Generated by Tabbit. DO NOT EDIT.
--
-- Changes to this file may cause incorrect behavior and will be lost if the code is
-- regenerated.
-- ------------------------------------------------------------------------------

local _root = (...):match("^(.-)[^%.]+%.[^%.]+$")
local tcb = require(_root .. "tabbit.tcb_reader")

-- Generated from test/fixtures/xlsx/polymorphism/polymorphism.xlsx : Polymorphism : B2.
-- What a damaging effect is made of.
---@class ElementRecord
---@field code integer
---@field name string
local ElementRecordMeta = tcb.strictType("a `Element` row", { "code", "name" })

---@return ElementRecord
local function newElementRecord()
  return setmetatable({
    code = 0,
    name = "",
  }, ElementRecordMeta)
end

---@class ElementTable
---@field records ElementRecord[]
local ElementTable = {}

local ElementTableMeta = tcb.strictInstance("the `Element` table", ElementTable, { "records", "byCode" })

function ElementTable.new()
  return setmetatable({
    records = {},
    byCode = {},
  }, ElementTableMeta)
end

-- How many rows the table holds.
--
-- A method rather than `#table`: LuaJIT 2.1 does not call `__len` on a table, so the
-- operator would answer on 5.3+ and not on the other runtime this output has to run on.
function ElementTable:count()
  return #self.records
end

-- The rows, in the order the file wrote them - `for row in table:iter() do`.
--
-- The list is read once, here. A refresh replaces it rather than its contents, so a loop
-- already running keeps the rows it started with.
function ElementTable:iter()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    return records[i]
  end
end

-- The row with this Code, or nil when the table has none: the lookup to
-- reach for when a missing row is an ordinary answer.
function ElementTable:findByCode(key)
  return self.byCode[key]
end

-- The row with this Code, or a raised error naming what was missing -
-- for a key that has to be there.
function ElementTable:getByCodeOrThrow(key)
  local record = self:findByCode(key)

  if record == nil then
    tcb.fail("there is no record in table `Element` that corresponds to " ..
      "field `Code` value %s", tostring(key))
  end

  return record
end

-- Whether the table holds a row with this Code.
function ElementTable:containsCode(key)
  return self:findByCode(key) ~= nil
end


-- Each row with the Code it is keyed by -
-- `for key, row in table:entries() do`.
--
-- What this saves a caller is not the key value - the row carries it - but having to know
-- which column the key is: Code here, something else in the next table.
--
-- The rows come in the order the file wrote them rather than the order the map holds them,
-- which makes this and `iter` agree. Only the primary key has this: a table keyed by
-- several columns together has no single key value to pair a row with.
function ElementTable:entries()
  local records = self.records
  local i = 0

  return function()
    i = i + 1
    local record = records[i]

    if record == nil then
      return nil
    end

    return record.code, record
  end
end


-- Loads the table from the bytes of a .tcb file written by Tabbit. Column by column,
-- matched by tag rather than position: a column this build does not know is skipped by
-- its block length, and one whose type changed incompatibly fails naming the field.
function ElementTable:readBytes(data)
  -- Required here rather than at the top: the accessor requires this module, so at load
  -- time it is half built and at call time it is not.
  local accessor = require(_root .. "tables")

  -- Opened unconditionally, with whatever keys the accessor holds - nil unless the
  -- project set them. A file that is neither encrypted nor signed comes back untouched,
  -- so the load path is the same either way. spec/wire/tcb-mac-and-signature.md.
  local reader = tcb.newReader(tcb.open(
    data, accessor.encryptionKey, accessor.macKey, accessor.verifyMac))
  local count, columns = tcb.readTableHeader(reader)

  -- Read into storage of its own and published at the end: reading a table that is
  -- already loaded is a refresh, and one that turns out to be unreadable has to leave
  -- the rows already there alone.
  local records = {}

  for i = 1, count do
    records[i] = newElementRecord()
  end

  for c = 1, #columns do
    local column = columns[c]
    local blockEnd = reader.position + column.byteLength

    if column.tag == 1 then
      tcb.checkColumn(column, "Element.Code", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Element.Code")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].code = value
        end

        at = at + n
      end
    elseif column.tag == 2 then
      tcb.checkColumn(column, "Element.Name", tcb.KIND_SCALAR, false, { tcb.ELEMENT_STRING })
      local cursor = tcb.newCursor(reader, column, count, "Element.Name")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameString(count - at)

        for i = at + 1, at + n do
          records[i].name = value
        end

        at = at + n
      end
    else
      -- A column added after this code was generated.
      reader:skip(column.byteLength)
    end

    tcb.checkBlockEnd(reader, column, blockEnd)
  end

  local byCode = {}

  for i = 1, #records do
    byCode[records[i].code] = records[i]
  end

  -- Published, now that every column read.
  self.records = records
  self.byCode = byCode
end

-- The same load from a file on disk.
function ElementTable:read(filename)
  self:readBytes(tcb.readAllBytes(filename))
end

return ElementTable
