// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

part of '../tables.dart';
// Generated from loadout.tbs(38,6)
/// What a reward is made of.
///
/// Declared here rather than in a sheet, so the type cell that names it is reading a
/// declaration this run read from a file.
enum Affinity {
  /// Burns.
  fire(1),
  /// Freezes.
  ice(2);

  const Affinity(this.value);

  /// The declared value, which is what travels on the wire.
  final int value;

  /// The label with this value, or the default when the sheet declared no such label.
  static Affinity of(int value) {
    for (final candidate in Affinity.values) {
      if (candidate.value == value) return candidate;
    }

    return Affinity.fire;
  }
}
