# ------------------------------------------------------------------------------
# Generated by Tabbit. DO NOT EDIT.
#
# Changes to this file may cause incorrect behavior and will be lost if the code is
# regenerated.
# ------------------------------------------------------------------------------

require_relative '../tabbit/tcb_reader'


module RecordTrim
  # One element of LootRecord#slot.
  class LootSlotEntry
    attr_accessor :id, :count, :label

    def initialize
      @id = 0
      @count = 0
      @label = ''
    end
  end

  # One element of LootRecord#pos.
  class LootPosEntry
    attr_accessor :x, :y

    def initialize
      @x = 0
      @y = 0
    end
  end

  # Generated from test/fixtures/xlsx/record-trim/record-trim.xlsx : Trim : B2
  # A record array trimmed at the last element the row filled in.
  class LootRecord
    attr_accessor :index, :name, :slot, :pos, :tag

    def initialize
      @index = 0
      @name = ''
      @slot = []
      @pos = LootPosEntry.new
      @tag = []
    end

  end

  # Every row of Loot.
  class LootTable
    include Enumerable

    attr_accessor :records

    # How many rows the table holds.
    def size
      @records.size
    end

    # The rows, in the order the file wrote them. Including Enumerable on top of this
    # is what gives the table `map` - `select` - `find` - `sort_by` without any of them
    # being written here.
    #
    # The array reference is read once, here. A refresh replaces the reference rather
    # than its contents, so a loop already running keeps the rows it started with.
    def each(&block)
      @records.each(&block)
    end

    def initialize
      @records = []
      @by_index = {}
    end

    # The row with this Index, or nil when the table has none.
    #
    # The lookup to reach for when a missing row is an ordinary answer - an optional
    # reference, a key that came from user input.
    def find_by_index(key)
      @by_index[key]
    end

    # The row with this Index, or a raised error naming what was missing.
    #
    # For a key that has to be there - one from another table, or a constant. The name
    # says it raises, because a caller reading `get_by_index(key).name` at a
    # glance cannot otherwise tell whether the next line is a check or a rescue.
    def get_by_index_or_throw(key)
      record = @by_index[key]

      if record.nil?
        raise Tabbit::RecordNotFoundError,
              "there is no record in table `Loot` that corresponds to " \
              "field `Index` value #{key.inspect}"
      end

      record
    end

    # Whether the table holds a row with this Index.
    def contains_index?(key)
      @by_index.key?(key)
    end


    # The row with this Index, or nil when the table has none.
    #
    # find_by_index under the spelling Ruby uses for a keyed collection. It
    # answers with nil because that is what Hash does here; a language whose own map raises
    # generates a subscript that raises.
    # spec/targets/table-collection-surface.md section 5.7.
    #
    # This is the key, not the row's position. `table[0]` is the row whose
    # Index is 0, not the first row - the rows in order are `records`.
    def [](key)
      find_by_index(key)
    end


    # Each row with the Index it is keyed by -
    # `table.each_pair { |key, row| ... }`.
    #
    # What this saves a caller is not the key value - the row carries it - but having to
    # know which column the key is: Index here, something else in the next
    # table.
    #
    # The rows come in the order the file wrote them rather than the order the hash holds
    # them, which makes this and `each` agree. Only the primary key has this: a table keyed
    # by several columns together has no single key value to pair a row with.
    def each_pair
      return to_enum(:each_pair) unless block_given?

      @records.each { |record| yield record.index, record }
      self
    end

    # Loads the table from a .tcb file written by Tabbit.
    # Column by column, matched by tag rather than position: a column this build does
    # not know is skipped by its block length, and one whose type changed incompatibly
    # fails naming the field.
    def read(filename)
      # Opened unconditionally, and with whatever Tables.encryption_key and Tables.mac_key
      # hold - which is nil unless the project set them. A file that is neither encrypted
      # nor signed comes back from this untouched, so the load path is the same either way
      # and there is no condition here that could be the wrong way round.
      # spec/wire/tcb-mac-and-signature.md.
      reader = Tabbit::Reader.new(
        Tabbit.open(Tabbit.read_all_bytes(filename), Tables.encryption_key,
                      Tables.mac_key, verify_mac: Tables.verify_mac)
      )
      count, columns = Tabbit.read_table_header(reader)

      # Read into storage of its own and published at the end: reading a table that is already loaded is a refresh, and one that turns out to be unreadable has to leave the rows already there alone.
      records = Array.new(count) { LootRecord.new }

      columns.each do |column|
        block_end = reader.position + column.byte_length

        case column.tag
        when 1
          Tabbit.check_column(column, 'Loot.Index', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Index')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].index = value
            end
            at += n
          end
        when 2
          Tabbit.check_column(column, 'Loot.Name', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_STRING])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Name')
          at = 0
          while at < count
            n, value = cursor.next_same_string(count - at)
            (at...(at + n)).each do |i|
              records[i].name = value
            end
            at += n
          end
        when 3
          Tabbit.check_column(column, 'Loot.Slot.Id', Tabbit::KIND_ARRAY, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Slot.Id')
          records.each do |record|
            element_count = cursor.next_length
            # The first member builds the array; the rest check. Building it again would
            # discard what the members before it wrote, and taking the shorter of two counts
            # would shift every value after it.
            record.slot = Array.new(element_count) { LootSlotEntry.new }
            element_count.times do |element|
              record.slot[element].id = cursor.next_i32
            end
          end
        when 4
          Tabbit.check_column(column, 'Loot.Slot.Count', Tabbit::KIND_ARRAY, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Slot.Count')
          records.each do |record|
            element_count = cursor.next_length
            if record.slot.length != element_count
              raise Tabbit::TcbError,
                    'Loot.slot: the file gives one member of this ' \
                    'record a different element count than another'
            end
            element_count.times do |element|
              record.slot[element].count = cursor.next_i32
            end
          end
        when 5
          Tabbit.check_column(column, 'Loot.Slot.Label', Tabbit::KIND_ARRAY, false, [Tabbit::ELEMENT_STRING])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Slot.Label')
          records.each do |record|
            element_count = cursor.next_length
            if record.slot.length != element_count
              raise Tabbit::TcbError,
                    'Loot.slot: the file gives one member of this ' \
                    'record a different element count than another'
            end
            element_count.times do |element|
              record.slot[element].label = cursor.next_string
            end
          end
        when 6
          Tabbit.check_column(column, 'Loot.Pos.X', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Pos.X')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].pos.x = value
            end
            at += n
          end
        when 7
          Tabbit.check_column(column, 'Loot.Pos.Y', Tabbit::KIND_SCALAR, false, [Tabbit::ELEMENT_I32, Tabbit::ELEMENT_VARINT])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Pos.Y')
          at = 0
          while at < count
            n, value = cursor.next_same_i32(count - at)
            (at...(at + n)).each do |i|
              records[i].pos.y = value
            end
            at += n
          end
        when 8
          Tabbit.check_column(column, 'Loot.Tag', Tabbit::KIND_ARRAY, false, [Tabbit::ELEMENT_STRING])
          cursor = Tabbit::ColumnCursor.new(reader, column, count, 'Loot.Tag')
          records.each do |record|
            element_count = cursor.next_length
            record.tag = Array.new(element_count) { cursor.next_string }
          end
        else
          # A column added after this code was generated.
          reader.skip(column.byte_length)
        end

        Tabbit.check_block_end(reader, column, block_end)
      end

      by_index = records.to_h { |record| [record.index, record] }

      # Published, now that every column read.
      @records = records
      @by_index = by_index
    end
  end
end
