// ------------------------------------------------------------------------------
// <auto-generated>
//     THIS CODE WAS GENERATED BY Tabbit.
//
//     CHANGES TO THIS FILE MAY CAUSE INCORRECT BEHAVIOR AND WILL BE LOST IF
//     THE CODE IS REGENERATED.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Text;
using System.Collections.Generic;
using System.Threading.Tasks;

// Tabbit's binary reader, written into this directory beside the accessor.
// Nothing has to be installed for the generated code to compile.
using Tabbit.Binary;

namespace Tabbit.Fixtures.MultiTarget
{
    /// <summary>
    /// One record whose members are arrays, one of them reaching several.
    /// </summary>
    [System.Serializable]
    public partial class RackTable
    {
        #region Record
        [System.Serializable]
        public partial class Record
        {
            #region Values
            /// <summary>
            /// primary index
            /// </summary>
            public int Index => _index;

            /// <summary>
            /// element 1 of the member
            /// </summary>
            public SlotsEntry Slots => _slots;
            #endregion

            /// <summary>One element of <see cref="Slots"/>.</summary>
            [System.Serializable]
            public struct SlotsEntry
            {
                /// element 1 of the member
                public int[] Pick;
                public object[] Pick_row;
                public RackSlotsPickTarget[] Pick_target;
                /// element 1 beside it
                public int[] Count;
                /// <summary>
                /// Element <paramref name="at"/> of <c>Pick</c> as a
                /// <c>WeaponTable.Record</c>, or null when it is a row of one of the others.
                /// </summary>
                public WeaponTable.Record WeaponByPick(int at)
                    => Pick_target[at] == RackSlotsPickTarget.Weapon
                        ? (WeaponTable.Record)Pick_row[at]
                        : null;
                /// <summary>
                /// Element <paramref name="at"/> of <c>Pick</c> as a
                /// <c>ArmourTable.Record</c>, or null when it is a row of one of the others.
                /// </summary>
                public ArmourTable.Record ArmourByPick(int at)
                    => Pick_target[at] == RackSlotsPickTarget.Armour
                        ? (ArmourTable.Record)Pick_row[at]
                        : null;

                public override string ToString()
                {
                    var sb = new StringBuilder("{");
                    sb.Append("\"Pick\":"); ToStringHelper.ToString(Pick, sb);
                    sb.Append(",\"Count\":"); ToStringHelper.ToString(Count, sb);
                    sb.Append("}");
                    return sb.ToString();
                }
            }

            private static SlotsEntry NewSlotsEntry()
            {
                var result = default(SlotsEntry);
                result.Pick = new int[2];
                result.Pick_row = new object[2];
                result.Pick_target = new RackSlotsPickTarget[2];
                result.Count = new int[2];
                return result;
            }

            #region Storage
            internal int _index;
            internal SlotsEntry _slots = NewSlotsEntry();
            #endregion

            #region ToString
            public override string ToString()
            {
                var sb = new StringBuilder("{");
                sb.Append("\"Index\":"); ToStringHelper.ToString(Index, sb);
                sb.Append(",\"Slots\":"); ToStringHelper.ToString(Slots, sb);
                sb.Append("}");
                return sb.ToString();
            }
            #endregion
        }
        #endregion

        /// <summary>
        /// Field names.
        /// </summary>
        public static readonly string[] FieldNames = { "Index", "Slots" };

        /// <summary>
        /// Build object value map.
        /// </summary>
        public List<object[]> BuildObjectValueMap()
        {
            var result = new List<object[]>();
            foreach (var r in _records)
                result.Add(new object[] { r.Index, r.Slots });

            return result;
        }

        /// <summary>
        /// All records.
        /// </summary>
        /// <remarks>
        /// The list a read publishes, not one a read fills. Whoever holds this reference holds
        /// the rows as they were when they took it, and a refresh underneath them replaces the
        /// reference rather than the contents - so an iteration in progress neither tears nor
        /// throws, and a read that fails leaves the previous rows exactly where they were.
        /// </remarks>
        public List<Record> Records => _records;
        private List<Record> _records = new List<Record>();

        #region Indexing by 'Index'
        public Dictionary<int, Record> RecordsByIndex => _recordsByIndex;
        private Dictionary<int, Record> _recordsByIndex = new Dictionary<int, Record>();

        /// <summary>
        /// The row with this `Index`, or null when the table has none.
        /// </summary>
        /// <remarks>
        /// The lookup to reach for when a missing row is an ordinary answer - an optional
        /// reference, a key that came from user input. Every language Tabbit generates has
        /// this one under the same name.
        /// </remarks>
        public Record FindByIndex(int key)
            => _recordsByIndex.TryGetValue(key, out Record record) ? record : null;

        /// <summary>
        /// The row with this `Index`, or a thrown exception naming what was
        /// missing.
        /// </summary>
        /// <remarks>
        /// For a key that has to be there - one from another table, or a constant. The name
        /// says it throws, because a caller reading `GetByIndex(id).Name` at
        /// a glance cannot otherwise tell whether the next line is a null check or a catch.
        /// </remarks>
        public Record GetByIndexOrThrow(int key)
        {
            if (!_recordsByIndex.TryGetValue(key, out Record record))
                throw new TabbitException($"There is no record in table `Rack` that corresponds to field `Index` value {key}");

            return record;
        }

        /// <summary>Whether the table holds a row with this `Index`.</summary>
        public bool ContainsIndex(int key) => _recordsByIndex.ContainsKey(key);
        #endregion // Indexing by `Index`

        /// <summary>
        /// Read a table from specified file.
        /// </summary>
        public async Task ReadAsync(string filename)
        {
            var bytes = await MultiTargetAccessor.ReadAllBytesAsync(filename);

            // Unconditionally, and with whatever `MultiTargetAccessor.EncryptionKey` and `MultiTargetAccessor.MacKey`
            // hold - which is null unless the project set them. A file that is neither
            // encrypted nor signed comes back from this untouched, so the load path is the
            // same either way and there is no condition here that could be the wrong way
            // round. spec/tcb-mac-and-signature.md.
            var reader = new TcbReader(TcbTable.Open(
                bytes, MultiTargetAccessor.EncryptionKey, MultiTargetAccessor.MacKey, MultiTargetAccessor.VerifyMac));

            await ReadAsync(reader);
        }

        /// <summary>
        /// Read a table from specified reader.
        /// </summary>
        /// <remarks>
        /// Column by column, matched by tag rather than position. A column this build does
        /// not know is skipped by its block length; one it knows but cannot read - the type
        /// changed incompatibly - fails naming the field. Order, names and columns added or
        /// removed on either side are therefore all survivable.
        /// </remarks>
        public Task ReadAsync(TcbReader reader)
        {
            var columns = TcbTable.ReadHeader(reader, out int count);
            TcbColumnCursor cursor;

            // Read into storage of its own and published at the end, which is what makes a
            // refresh atomic: nothing here touches what the table is currently holding, so a
            // file that turns out to be truncated - or a column this build cannot read -
            // leaves the previous rows in place and reports why.
            //
            // Sized once. The row count was checked against what the columns declare before
            // this point, so it is a number the file could actually hold rows for - and a
            // list that grows into twenty thousand rows reallocates fifteen times to get
            // there, copying everything each time.
            var records = new List<Record>(count);

            for (int i = 0; i < count; i++)
                records.Add(new Record());

            foreach (var column in columns)
            {
                int blockEnd = reader.Position + column.ByteLength;

                switch (column.Tag)
                {
                    case 1:
                        TcbTable.CheckColumn(column, "Rack.Index", TcbTable.KindScalar, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Rack.Index");
                        for (int i = 0; i < count; )
                        {
                            // One call per run of equal values, not one per row - over a
                            // run-length encoded column this is most of the decode.
                            int n = cursor.NextSameI32(count - i, out var value);
                            do
                            {
                                var record = records[i++];
                                record._index = value;
                            } while (--n > 0);
                        }
                        break;

                    case 2:
                        TcbTable.CheckColumn(column, "Rack.Slots.Pick", TcbTable.KindArray, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Rack.Slots.Pick");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            int elementCount;
                            elementCount = cursor.NextLength();
                            record._slots.Pick =
                                new int[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._slots.Pick[j] = cursor.NextI32();
                            }
                        }
                        break;

                    case 3:
                        TcbTable.CheckColumn(column, "Rack.Slots.Count", TcbTable.KindArray, false, TcbTable.ElementI32, TcbTable.ElementVarint);
                        cursor = new TcbColumnCursor(reader, column, count, "Rack.Slots.Count");
                        for (int i = 0; i < count; i++)
                        {
                            var record = records[i];
                            int elementCount;
                            elementCount = cursor.NextLength();
                            record._slots.Count =
                                new int[elementCount];
                            for (int j = 0; j < elementCount; ++j)
                            {
                                record._slots.Count[j] = cursor.NextI32();
                            }
                        }
                        break;

                    default:
                        // A column added after this code was generated. Its block length
                        // says how far to move on.
                        reader.Skip(column.ByteLength);
                        break;
                }

                TcbTable.CheckBlockEnd(reader, column, blockEnd);
            }

            // Index mapping. Sized to the rows, so nothing rehashes on the way in, and a
            // duplicate key throws here - before any of this is visible.
            var recordsByIndex = new Dictionary<int, Record>(count);
            foreach (var record in records)
                recordsByIndex.Add(record.Index, record);

            // Published. Everything above succeeded, and the barrier is what keeps the writes
            // that built these from being seen after the references to them - a reader on
            // another thread gets the whole table or the previous one, never half of either.
            System.Threading.Thread.MemoryBarrier();

            _records = records;
            _recordsByIndex = recordsByIndex;

            return Task.CompletedTask;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            ToStringHelper.ToString(_records, sb);
            return sb.ToString();
        }
    }
} // namespace Tabbit.Fixtures.MultiTarget
