-- ------------------------------------------------------------------------------
-- Generated by Tabbit. DO NOT EDIT.
--
-- Changes to this file may cause incorrect behavior and will be lost if the code is
-- regenerated.
-- ------------------------------------------------------------------------------

local _root = (...):match("^(.-)[^%.]+%.[^%.]+$")
local tcb = require(_root .. "tabbit.tcb_reader")
local HolderPickTarget = require(_root .. "enums.enum_holder_pick_target")
local HolderWideTarget = require(_root .. "enums.enum_holder_wide_target")
local HolderMaybeTarget = require(_root .. "enums.enum_holder_maybe_target")

-- Generated from test/fixtures/xlsx/multi-target/multi-target.xlsx : Holders : B2.
-- One column per case the spec states.
---@class HolderRecord
---@field index integer
---@field pick integer
---@field wide integer
---@field only WeaponRecord|nil
---@field onlyIndex integer
---@field maybe integer
---@field hasMaybe boolean
---@field pickRow any
---@field pickTarget integer
---@field wideRow any
---@field wideTarget integer
---@field maybeRow any
---@field maybeTarget integer
local HolderRecord = {}

-- The WeaponRecord row `pick` names, or nil when it names a row of
-- one of the others.
---@return WeaponRecord|nil
function HolderRecord:weaponByPick()
  if self.pickTarget ~= HolderPickTarget.weapon then
    return nil
  end

  return self.pickRow
end

-- The ArmourRecord row `pick` names, or nil when it names a row of
-- one of the others.
---@return ArmourRecord|nil
function HolderRecord:armourByPick()
  if self.pickTarget ~= HolderPickTarget.armour then
    return nil
  end

  return self.pickRow
end

-- The WeaponRecord row `wide` names, or nil when it names a row of
-- one of the others.
---@return WeaponRecord|nil
function HolderRecord:weaponByWide()
  if self.wideTarget ~= HolderWideTarget.weapon then
    return nil
  end

  return self.wideRow
end

-- The ArmourRecord row `wide` names, or nil when it names a row of
-- one of the others.
---@return ArmourRecord|nil
function HolderRecord:armourByWide()
  if self.wideTarget ~= HolderWideTarget.armour then
    return nil
  end

  return self.wideRow
end

-- The TrinketRecord row `wide` names, or nil when it names a row of
-- one of the others.
---@return TrinketRecord|nil
function HolderRecord:trinketByWide()
  if self.wideTarget ~= HolderWideTarget.trinket then
    return nil
  end

  return self.wideRow
end

-- The MountRecord row `wide` names, or nil when it names a row of
-- one of the others.
---@return MountRecord|nil
function HolderRecord:mountByWide()
  if self.wideTarget ~= HolderWideTarget.mount then
    return nil
  end

  return self.wideRow
end

-- The BannerRecord row `wide` names, or nil when it names a row of
-- one of the others.
---@return BannerRecord|nil
function HolderRecord:bannerByWide()
  if self.wideTarget ~= HolderWideTarget.banner then
    return nil
  end

  return self.wideRow
end

-- The WeaponRecord row `maybe` names, or nil when it names a row of
-- one of the others.
---@return WeaponRecord|nil
function HolderRecord:weaponByMaybe()
  if self.maybeTarget ~= HolderMaybeTarget.weapon then
    return nil
  end

  return self.maybeRow
end

-- The ArmourRecord row `maybe` names, or nil when it names a row of
-- one of the others.
---@return ArmourRecord|nil
function HolderRecord:armourByMaybe()
  if self.maybeTarget ~= HolderMaybeTarget.armour then
    return nil
  end

  return self.maybeRow
end

local HolderRecordMeta = tcb.strictInstance("a `Holder` row", HolderRecord, { "index", "pick", "wide", "only", "onlyIndex", "maybe", "hasMaybe", "pickRow", "pickTarget", "wideRow", "wideTarget", "maybeRow", "maybeTarget" })

---@return HolderRecord
local function newHolderRecord()
  return setmetatable({
    index = 0,
    pick = 0,
    wide = 0,
    onlyIndex = 0,
    maybe = 0,
    hasMaybe = false,
    pickRow = nil,
    pickTarget = HolderPickTarget.none,
    wideRow = nil,
    wideTarget = HolderWideTarget.none,
    maybeRow = nil,
    maybeTarget = HolderMaybeTarget.none,
  }, HolderRecordMeta)
end

---@class HolderTable
---@field records HolderRecord[]
local HolderTable = {}

local HolderTableMeta = tcb.strictInstance("the `Holder` table", HolderTable, { "records", "byIndex" })

function HolderTable.new()
  return setmetatable({
    records = {},
    byIndex = {},
  }, HolderTableMeta)
end

-- The row with this Index, or nil when the table has none: the lookup to
-- reach for when a missing row is an ordinary answer.
function HolderTable:findByIndex(key)
  return self.byIndex[key]
end

-- The row with this Index, or a raised error naming what was missing -
-- for a key that has to be there.
function HolderTable:getByIndexOrThrow(key)
  local record = self:findByIndex(key)

  if record == nil then
    tcb.fail("there is no record in table `Holder` that corresponds to " ..
      "field `Index` value %s", tostring(key))
  end

  return record
end

-- Whether the table holds a row with this Index.
function HolderTable:containsIndex(key)
  return self:findByIndex(key) ~= nil
end

-- Loads the table from the bytes of a .tcb file written by Tabbit. Column by column,
-- matched by tag rather than position: a column this build does not know is skipped by
-- its block length, and one whose type changed incompatibly fails naming the field.
function HolderTable:readBytes(data)
  -- Required here rather than at the top: the accessor requires this module, so at load
  -- time it is half built and at call time it is not.
  local accessor = require(_root .. "tables")

  -- Opened unconditionally, with whatever keys the accessor holds - nil unless the
  -- project set them. A file that is neither encrypted nor signed comes back untouched,
  -- so the load path is the same either way. spec/tcb-mac-and-signature.md.
  local reader = tcb.newReader(tcb.open(
    data, accessor.encryptionKey, accessor.macKey, accessor.verifyMac))
  local count, columns = tcb.readTableHeader(reader)

  -- Read into storage of its own and published at the end: reading a table that is
  -- already loaded is a refresh, and one that turns out to be unreadable has to leave
  -- the rows already there alone.
  local records = {}

  for i = 1, count do
    records[i] = newHolderRecord()
  end

  for c = 1, #columns do
    local column = columns[c]
    local blockEnd = reader.position + column.byteLength

    if column.tag == 1 then
      tcb.checkColumn(column, "Holder.Index", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Holder.Index")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].index = value
        end

        at = at + n
      end
    elseif column.tag == 2 then
      tcb.checkColumn(column, "Holder.Pick", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Holder.Pick")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].pick = value
        end

        at = at + n
      end
    elseif column.tag == 3 then
      tcb.checkColumn(column, "Holder.Wide", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      local cursor = tcb.newCursor(reader, column, count, "Holder.Wide")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].wide = value
        end

        at = at + n
      end
    elseif column.tag == 4 then
      tcb.checkColumn(column, "Holder.Only", tcb.KIND_SCALAR, false, { tcb.ELEMENT_I32 })
      local cursor = tcb.newCursor(reader, column, count, "Holder.Only")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].onlyIndex = value
        end

        at = at + n
      end
    elseif column.tag == 5 then
      tcb.checkColumn(column, "Holder.Maybe", tcb.KIND_SCALAR, true, { tcb.ELEMENT_I32, tcb.ELEMENT_VARINT })
      -- The bitmap is at the front of the block, so it is read before the values. The
      -- values are written for every row either way, which is what lets the read shapes
      -- below stay as they are.
      local presence = tcb.readPresence(reader, column, count)
      local cursor = tcb.newCursor(reader, column, count, "Holder.Maybe")
      local at = 0

      while at < count do
        local n, value = cursor:nextSameI32(count - at)

        for i = at + 1, at + n do
          records[i].maybe = value
        end

        at = at + n
      end

      -- A pass of its own rather than a line inside each read shape, so the row index
      -- is worked out once. The block carries a value for every row, so an absent one
      -- has just been given whatever was there; putting the empty value back is what
      -- makes this path agree with the JSON one.
      for i = 1, count do
        local record = records[i]

        record.hasMaybe = tcb.isPresent(presence, i - 1)

        if not record.hasMaybe then
          record.maybe = 0
        end
      end
    else
      -- A column added after this code was generated.
      reader:skip(column.byteLength)
    end

    tcb.checkBlockEnd(reader, column, blockEnd)
  end

  local byIndex = {}

  for i = 1, #records do
    byIndex[records[i].index] = records[i]
  end

  -- Published, now that every column read.
  self.records = records
  self.byIndex = byIndex
end

-- The same load from a file on disk.
function HolderTable:read(filename)
  self:readBytes(tcb.readAllBytes(filename))
end

return HolderTable
