<?php

// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

declare(strict_types=1);

namespace Tabbit\Fixtures\DocShowcase;

use Tabbit\TcbReader;
use Tabbit\TcbColumnCursor;
use Tabbit\RecordNotFoundException;
use Tabbit\Uuid;

/**
 * Generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Basics : G2
 *
 * What a potion is made of.
 */
enum Element: int
{
    /** no element */
    case None = 0;
    /** burns */
    case FireBall = 1;
    /** chills */
    case IceShard = 2;
}
