// ------------------------------------------------------------------------------
// Generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------


// Tables
export { AnimationRecord } from './tables/animation'
export { AnimationTable } from './tables/animation'

export { Tables } from './tables'
