// ------------------------------------------------------------------------------
// Code generated by Tabbit. DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is
// regenerated.
// ------------------------------------------------------------------------------

package docshowcase

import (
	"fmt"
	"iter"

	"docshowcase/tabbit"
)

// SampleRecord was generated from test/fixtures/xlsx/doc-showcase/doc-showcase.xlsx : Types : B2.
// One column per scalar type.
type SampleRecord struct {
	// primary index
	Index int32
	// 64 bit
	Count int64
	// 32 bit
	Ratio float32
	// 64 bit
	Precise float64
	// Y or N
	Enabled bool
	// text
	Label string
	// a moment
	At int64
	// a length
	Span int64
	// an identifier
	Id tabbit.UUID
}

// SampleTable holds every row of Sample.
type SampleTable struct {
	records []SampleRecord
	byIndex map[int32]int
}

// Records returns every row, in the order the sheet declared them.
func (t *SampleTable) Records() []SampleRecord { return t.records }

// Count returns how many rows the table holds.
func (t *SampleTable) Count() int { return len(t.records) }

// All returns the rows, in the order the file wrote them - `for row := range t.All()`.
//
// The slice header is read once, here. A refresh replaces it rather than its contents, so a
// loop already running keeps the rows it started with.
func (t *SampleTable) All() iter.Seq[*SampleRecord] {
	records := t.records

	return func(yield func(*SampleRecord) bool) {
		for i := range records {
			if !yield(&records[i]) {
				return
			}
		}
	}
}

// FindByIndex returns the row with this Index, or nil when the table has none.
//
// The lookup to reach for when a missing row is an ordinary answer - an optional
// reference, a key that came from user input.
func (t *SampleTable) FindByIndex(key int32) *SampleRecord {
	position, found := t.byIndex[key]
	if !found {
		return nil
	}

	return &t.records[position]
}

// GetByIndexOrError returns the row with this Index, or an error naming
// what was missing.
//
// For a key that has to be there - one from another table, or a constant. Go has no
// exception to throw, so where the other languages name a throw this one names the error
// it returns; either way the call site can tell without going to the definition.
func (t *SampleTable) GetByIndexOrError(key int32) (*SampleRecord, error) {
	position, found := t.byIndex[key]
	if !found {
		return nil, fmt.Errorf(
			"there is no record in table `Sample` that corresponds to field `Index` value %v", key)
	}

	return &t.records[position], nil
}

// ContainsIndex reports whether the table holds a row with this Index.
func (t *SampleTable) ContainsIndex(key int32) bool {
	_, found := t.byIndex[key]
	return found
}

// Entries yields each row with the Index it is keyed by -
// `for key, row := range t.Entries()`.
//
// What this saves a caller is not the key value - the row carries it - but having to know
// which column the key is: Index here, something else in the next table.
//
// The rows come in the order the file wrote them rather than the order a map happens to
// hold them, which makes this and All agree. Only the primary key has this: a table keyed
// by several columns together has no single key value to pair a row with.
func (t *SampleTable) Entries() iter.Seq2[int32, *SampleRecord] {
	records := t.records

	return func(yield func(int32, *SampleRecord) bool) {
		for i := range records {
			if !yield(records[i].Index, &records[i]) {
				return
			}
		}
	}
}

// Read loads the table from a .tcb file written by Tabbit.
func (t *SampleTable) Read(filename string) error {
	data, err := tabbit.ReadAllBytes(filename)
	if err != nil {
		return err
	}

	// Unconditionally, and with whatever EncryptionKey and MacKey hold - which is nil
	// unless the project set them. A file that is neither encrypted nor signed comes back
	// from this untouched, so the load path is the same either way and there is no
	// condition here that could be the wrong way round. spec/wire/tcb-mac-and-signature.md.
	//
	// What comes back is a window onto data rather than a copy of it, which is why data
	// stays in scope for the whole read.
	opened, err := tabbit.Open(data, EncryptionKey, MacKey, VerifyMac)
	if err != nil {
		return err
	}

	reader := tabbit.NewReader(opened)
	count, columns := tabbit.ReadTableHeader(reader)

	// Column by column, matched by tag rather than position: a column this build does
	// not know is skipped by its block length, and one whose type changed incompatibly
	// fails naming the field.
	//
	// Read into rows of its own and assigned at the end. Reading a table that is already
	// loaded is a refresh, and a refresh that turns out to be unreadable has to leave what
	// the table holds alone - the previous rows and an error, not an empty table.
	records := make([]SampleRecord, count)

	for _, column := range columns {
		blockEnd := reader.Position() + int(column.ByteLength)

		switch column.Tag {
		case 1:
			if tabbit.CheckColumn(reader, column, "Sample.Index", tabbit.KindScalar, false, tabbit.ElementI32, tabbit.ElementVarint) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.Index")
				for i := int32(0); i < count; {
					n, value := cursor.NextSameI32(count - i)
					for ; n > 0; n-- {
						records[i].Index = value
						i++
					}
				}
			}
		case 2:
			if tabbit.CheckColumn(reader, column, "Sample.Count", tabbit.KindScalar, false, tabbit.ElementI64, tabbit.ElementI32, tabbit.ElementVarint) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.Count")
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.Count = cursor.NextI64()
				}
			}
		case 3:
			if tabbit.CheckColumn(reader, column, "Sample.Ratio", tabbit.KindScalar, false, tabbit.ElementF32) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.Ratio")
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.Ratio = cursor.NextF32()
				}
			}
		case 4:
			if tabbit.CheckColumn(reader, column, "Sample.Precise", tabbit.KindScalar, false, tabbit.ElementF64, tabbit.ElementF32, tabbit.ElementI32) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.Precise")
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.Precise = cursor.NextF64()
				}
			}
		case 5:
			if tabbit.CheckColumn(reader, column, "Sample.Enabled", tabbit.KindScalar, false, tabbit.ElementBool) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.Enabled")
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.Enabled = cursor.NextBool()
				}
			}
		case 6:
			if tabbit.CheckColumn(reader, column, "Sample.Label", tabbit.KindScalar, false, tabbit.ElementString) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.Label")
				for i := int32(0); i < count; {
					n, value := cursor.NextSameString(count - i)
					for ; n > 0; n-- {
						records[i].Label = value
						i++
					}
				}
			}
		case 7:
			if tabbit.CheckColumn(reader, column, "Sample.At", tabbit.KindScalar, false, tabbit.ElementI64) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.At")
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.At = cursor.NextI64()
				}
			}
		case 8:
			if tabbit.CheckColumn(reader, column, "Sample.Span", tabbit.KindScalar, false, tabbit.ElementI64) {
				cursor := tabbit.NewColumnCursor(reader, column, count, "Sample.Span")
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.Span = cursor.NextI64()
				}
			}
		case 9:
			if tabbit.CheckColumn(reader, column, "Sample.Id", tabbit.KindScalar, false, tabbit.ElementUUID) {
				for i := int32(0); i < count; i++ {
					r := &records[i]
					r.Id = reader.ReadUUID()
				}
			}
		default:
			// A column added after this code was generated.
			reader.Skip(column.ByteLength)
		}

		tabbit.CheckBlockEnd(reader, column, blockEnd)
	}

	if err := reader.Err(); err != nil {
		return fmt.Errorf("Sample: %w", err)
	}

	byIndex := make(map[int32]int, len(records))
	for i := range records {
		byIndex[records[i].Index] = i
	}

	// Published, now that every column read and the indexes are built.
	t.records = records
	t.byIndex = byIndex

	return nil
}
